cloud-barista/cb-tumblebug

mcism_master/mcism_master.go
Block user message for a moment
=> Block user message for a moment

mcism_server/mcism_mcis.go, mcism_server/mcism_resource_manage_spec.go, mcism_server/mcism_server.go
fix #12 partially.
Add recommendation for MCIS config functionality
=> Add recommendation for MCIS config functionality

mcism_server/mcism_namespace.go
- Related issue: #25 
- MCIS emptiness check logic is not included in this PR.
=> Add NS emptiness check logic

mcism_server/mcism_mcis.go, mcism_server/mcism_namespace.go
fix #22, #21
Apply goroutine for vm parallel creation
=> Apply goroutine for vm parallel creation

mcism_server/mcir_image.go, mcism_server/mcir_network.go, mcism_server/mcir_publicip.go, mcism_server/mcir_securitygroup.go, mcism_server/mcir_sshkey.go, mcism_server/mcir_vnic.go
Done in this PR:
Support for
- All files - `KeyValueList []KeyValue`
- `SecurityHandler.go`
- `SecurityRules *[]SecurityRuleInfo`
- `VNicHandler.go`
- `SecurityGroupIds []string`
TODO:
Support for
- `VMHandler.go`
- `SecurityGroupIds []string`
- `Region       RegionInfo`
=> Update MCIR mgmt codes (2nd update)

mcism_server/mcir_image.go
- Added: `registerImageWithName()`
- Possible alternative: `registerImageWithId()`
=> Add `registerImageWithName` function

mcism_server/mcism_mcis.go, setup.env
CB-Spider integration for MCIS creation.
Initially, for MCIS creation, termination.
=> CB-Spider integration for MCIS creation

mcism_server/mcism_mcis.go
Spider integration for MCIS and individual VM controls
=> Spider integration for MCIS controls

mcism_server/mcism_mcis.go
=> Enhance MCIS life-cycles

mcism_server/mcism_mcis.go, mcism_server/mcism_server.go
Enhancement for MCIR and MCIS collaboration.
Fix a nit for getCspResourceId(). case "spec". retrun content.Id -> content.Name
=> Enhancement for MCIR and MCIS collaboration

src/common/utility.go, src/mcir/spec.go, src/mcir/utility.go, src/mcis/control.go, src/mcis/utility.go
Enhance MCIS cofig recommend functionality
=> Enhance MCIS cofig recommend functionality

src/mcis/control.go
Enhance MCIS and VM info structure
=> Enhance MCIS and VM info structure

src/apiserver/apiserver.go, src/mcis/control.go
Enhance mcis list response,
And include CORS config to allow  all for "allow-origin-access-control"
e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
AllowOrigins: []string{"*"},
AllowMethods: []string{http.MethodGet, http.MethodPut, http.MethodPost, http.MethodDelete},
}))
=> Enhance mcis list response

src/common/namespace.go
Only some commented codes are updated.
There is no actual changes.
Related: #25 #28 #29
=> Update some commented codes

src/apiserver/apiserver.go, src/common/utility.go
=> Add GetConnConfigList func

src/common/namespace.go, src/mcir/common.go, src/mcir/image.go, src/mcir/network.go, src/mcir/publicip.go, src/mcir/securitygroup.go, src/mcir/spec.go, src/mcir/sshkey.go, src/mcir/subnet.go, src/mcir/vnic.go, src/mcis/control.go
=> Change UUID to user give name

src/common/namespace.go, src/common/utility.go, src/mcir/image.go, src/mcir/network.go, src/mcir/publicip.go, src/mcir/securitygroup.go, src/mcir/spec.go, src/mcir/sshkey.go, src/mcir/subnet.go, src/mcis/control.go
I would add GenId() module so that we can apply ID generation rule universally.
=> Add and apply GenId module

src/common/namespace.go, src/mcir/common.go, src/mcir/network.go, src/mcir/publicip.go, src/mcir/securitygroup.go, src/mcir/sshkey.go, src/mcir/subnet.go, src/mcir/vnic.go
Added logics
- Check parameters' emptiness (`checkNs()`, `checkResource()`)
- Check resourceType's validity (`checkResource()`)
=> Minor changes on MCIR and NS

src/apiserver/apiserver.go, src/common/namespace.go, src/mcir/common.go, src/mcis/utility.go
- NS 확인 API (테스트 완료)
- /tumblebug/**checkNs**/:nsId
- MCIS 확인 API (테스트 완료)
- /tumblebug/ns/:nsId/**checkMcis**/:mcisId
- VM 확인 API (VM 만들기 어려워 테스트 하지 않았음)
- /tumblebug/ns/:nsId/mcis/:mcisId/**checkVm**/:vmId
- MCIR 확인 API (테스트 완료)
- /tumblebug/ns/:nsId/**checkResource**/:resourceType/:resourceId
---
GET `{{tb_ip}}:{{tb_port}}/tumblebug/ns/{{ns_id}}/checkResource/image/{{cbImageId}}`
1) 이미 존재하는 경우
```JSON
{
"Exists": true
}
```
2) 존재하지 않는 경우
```JSON
{
"Exists": false
}
```
=> Add checkObject funcs and APIs

go.mod, test/2020-04-29/conf.env
Change conf.env for test
minor changes for test codes
=> Change conf.env for test

src/mcis/control.go, test/2020-04-29/6.mcis/create-mcis.sh, test/2020-04-29/fullTest/clearToZeroBase.sh, test/2020-04-29/fullTest/testFromZeroBase.sh
=> Fix bugs for bench-marking

.gitignore, test/2020-04-29/fullTest/cleanAll-mcis-mcir-cloud.sh, test/2020-04-29/fullTest/test-mcir-ns-cloud.sh, test/2020-04-29/fullTest/testAll-mcis-mcir-ns-cloud.sh
=> Update test detail

src/mcis/control.go
Add get mcis list with current status
related issue : #147
=> Add get mcis list with current status

.gitignore, go.mod, src/apiserver/apiserver.go, src/mcis/control.go, test/official/conf.env, test/official/credentials.conf, test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh, test/official/sequentialFullTest/executionStatus, test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
Enhance benchmarking and remote call
모든 벤치마킹 요소에 대한 평가 수행 기능 추가
- {{tb_ip}}:{{tb_port}}{{tb_prefix}}/ns/{{ns_id}}/benchmarkall/mcis/{{mcis_name}}
결과는 임시 파일로 저장됨. (benchmarking.csv , src/rttmap.csv)
SSH를 통한 MCIS 원격 커맨드 기능은 
현재 접속에 사용되는 user name이 CB-Spider를 통해일관되게 제공되지 않기 때문에
임의의 코드를 사용하여, 다양한 user name을 시도해보고 사용 가능한 것을 자동 선택함. (만약 ssh 가 가능한 username을 못찾으면 Error처리)
=>  Enhance benchmarking and remote call

README.md, src/apiserver/apiserver.go
Update Readme and release information
=> Update Readme and release information

go.mod, src/common/namespace.go, src/grpc/server/server.go, src/mcism.go, src/restapiserver/server.go
`cb-tumblebug/src`
`tree -h`
```
...
├── [4.0K]  grpc
│   ├── [4.0K]  client
│   │   ├── [ 15M]  cb-tb-grpc-client
│   │   ├── [ 813]  client.go
│   │   └── [  99]  Makefile
│   ├── [4.0K]  protobuf
│   │   ├── [ 19K]  cbtumblebug.pb.go
│   │   ├── [ 858]  cbtumblebug.proto
│   │   └── [ 197]  Makefile
│   └── [4.0K]  server
│       ├── [ 21M]  cb-tb-grpc-server
│       ├── [  99]  Makefile
│       └── [1.6K]  server.go
...
└── [4.0K]  restapiserver
└── [9.4K]  server.go
```
Ref: @powerkimhub
=> Apply goroutine for REST server and gRPC server

go.sum, src/api/rest/server.go, src/common/utility.go, src/webadmin/namespace.go, src/webadmin/obsolete/webadmin.go, src/webadmin/spec.go, src/webadmin/webadmin.go
- Endpoint
- http://{tb_ip}:{tb_port}/tumblebug/webadmin
- Implemented features
- Namespace
- List
- Create
- Delete
=> Add webadmin (draft)

src/api/rest/server/common/namespace.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
Change swagger api style.
According to @powerkimhub 's comment. (Use a common tag)
https://cloud-barista.slack.com/archives/CHTRV7LLT/p1593768479036500?thread_ts=1593767824.035200&cid=CHTRV7LLT
=> Change swagger api style

conf/setup.env, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go, test/official/conf.env
This PR provides BasicAuth UI to Swagger API page.
In addition, modified the Default ID/PW for API BasicAuth.
=> Provide BasicAuth UI to Swagger API page

conf/setup.env, src/api/rest/server/mcis/monitor.go, src/api/rest/server/server.go, src/common/common.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go, src/mcis/monitor.go, test/official/9.monitoring/get-cloud.sh, test/official/9.monitoring/install-agent.sh, test/official/9.monitoring/list-cloud.sh, test/official/9.monitoring/setup-agent.sh, test/official/9.monitoring/unregister-cloud.sh, test/official/sequentialFullTest/command-mcis-custom.sh
This PR includes Initial codes for policy management.
Provide a capability for monitoring agent installation by connecting CB-Dragonfly.
You can test like this..
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/9.monitoring$ ./install-agent.sh aws 1 shson
[Test for AWS]
{
"result_array" : [
{
"vm_id" : "aws-us-east-1-shson-01",
"result" : "{\"message\":\"agent installation is finished\"}\n",
"mcis_id" : "aws-us-east-1-shson",
"vm_ip" : "3.85.194.104"
},
{
"mcis_id" : "aws-us-east-1-shson",
"vm_id" : "aws-us-east-1-shson-02",
"result" : "{\"message\":\"agent installation is finished\"}\n",
"vm_ip" : "100.24.29.74"
},
{
"mcis_id" : …
```
=> Initial code for policy management

conf/setup.env
- CBTUMBLEBUG_ROOT 환경변수 추가
- SPIDER_CALL_METHOD 환경변수 추가
=> Add grpc related env

src/api/rest/server/mcis/control.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
Swagger docs preview:
- SwaggerHub: https://app.swaggerhub.com/apis-docs/jihoon-seo/cb-tumblebug/v0.2.0-20200729
- "Dynamic HTML": http://132.145.80.18:8080/v0.2.0-20200729/dynamic-html-documentation-generated/docs/
- "HTML": http://132.145.80.18:8080/v0.2.0-20200729/html-documentation-generated/
- "HTML2": http://132.145.80.18:8080/v0.2.0-20200729/html2-documentation-generated/
=> Update Swagger annotations for MCIS/VM REST functions

test/official/credentials.conf
=> Add credential template

test/official/credentials.conf
Change credentials.conf template
=> Change credentials.conf template

test/official/credentials.conf
Renew test/official/credentials.conf template
=> Renew test/official/credentials.conf template

src/api/grpc/protobuf/Makefile
=> Fix include path

src/core/mcis/control.go
- Issue raised by @jmleefree via Slack
=> Fix bug in func CreateMcis

go.mod, go.sum, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go, src/core/mcis/control.go
- spider api 생성함수 이름 변경 : NewCloudInfoResourceHandler() => NewCloudResourceHandler()
=> changed Go API Handler Name: NewCloudInfoResourceHandler => NewCloudResourceHandler

test/official/8.mcis/add-vm-to-mcis.sh, test/official/8.mcis/create-single-vm-mcis.sh, test/official/8.mcis/status-mcis.sh, test/official/8.mcis/terminate-and-delete-mcis.sh, test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh, test/official/sequentialFullTest/test-cloud.sh, test/official/sequentialFullTest/test-mcir-ns-cloud.sh, test/official/sequentialFullTest/test-ns-cloud.sh, test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
Modify test scripts for all clouds test
This PR provides test script for creating a mcis that consists of VMs from multiple CSP regions.
=> Modify test scripts for all clouds test

src/api/rest/server/mcis/control.go, src/core/mcis/control.go, test/official/conf.env, test/official/sequentialFullTest/deploy-nginx-mcis.sh, test/official/sequentialFullTest/expand-mcis.sh, test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
Add VM to MCIS 기능의 오류를 수정하는 PR 입니다.
기존에 정상 동작하던 코드가 
협업 개발 중에 고장난 케이스인 것 같습니다. 주 기능이 아니다보니, 테스트를 수행하지 않고 머지된 것 같네요.
앞으로, 텀블벅도 컨트리뷰터들에게 기능 테스트 수행 및 결과에 대한 요청이 필요할 수도 있을 것 같습니다.
(향후에는 CI/CD 도입으로 처리되도록하는 것이 좋겠네요)
+ 추가적으로 스크립트를 통한 MCIS 확장 기능을 제공합니다.
=> Fix error for add vm to mcis with test support

test/official/sequentialFullTest/deploy-tumblebug.sh
Add tumblebug auto setup script
=> Add tumblebug auto setup script

src/api/grpc/cbadm/test/official/8.mcis/add-vm-to-mcis.sh, src/api/grpc/cbadm/test/official/8.mcis/create-single-vm-mcis.sh, src/api/grpc/cbadm/test/official/8.mcis/status-mcis.sh, src/api/grpc/cbadm/test/official/8.mcis/terminate-and-delete-mcis.sh, src/api/grpc/cbadm/test/official/conf.env, src/api/grpc/cbadm/test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/deploy-nginx-mcis.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/expand-mcis.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/test-cloud.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/test-mcir-ns-cloud.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/test-ns-cloud.sh, src/api/grpc/cbadm/test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
- rest test scripts 수정 사항을 grpc 에도 적용하여 동기화 함
=> Modify test scripts for grpc

README.md
이 PR은 README.md 의 문구를 
조금 더 명확하게 수정합니다.
=> Update README clearly

go.mod, go.sum, src/api/rest/server/server.go, src/core/common/common.go, src/core/common/namespace_test.go, src/core/mcir/image.go, src/core/mcir/image_test.go, src/core/mcir/spec.go, src/core/mcir/spec_test.go, src/main.go
[DB initializing codes]
- Before: DB initializing codes were in `src/main.go`
- After:
- Functionize DB initializing codes in `src/core/common/common.go`
- OpenSQL()
- SelectDatabase()
- CreateImageTable()
- CreateSpecTable()
- Call those functions in `src/main.go`
[namespace_test.go]
- func TestNs(t *testing.T)
- CreateNs("tb-unit-test")
- GetNs("tb-unit-test")
- CheckNs("tb-unit-test")
- DelNs("tb-unit-test")
[image_test.go]
- func TestImage(t *testing.T)
- CreateNs("tb-unit-test")
- OpenSQL("../../../meta_db/dat/tb-unit-test.s3db")
- SelectDatabase("tb-unit-test")
- CreateImageTable()
- RegisterImageWithInfo(nsName, "tb-unit-test")
- GetResource(nsName, "image", imageName)
- DelResource(nsName, "image", imageName, "false")
- DelNs(nsName)
[spec_test.go]
- func TestSpec(t *testing.T)
- …
=> Add NS, image, and spec gotest codes

go.mod, go.sum, src/core/common/utility.go, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go, test/official/5.sshKey/spider-delete-sshKey.sh, test/official/misc/get-conn-config.sh, test/official/misc/get-region.sh, test/official/misc/list-conn-config.sh, test/official/misc/list-region.sh
- Tested with
- `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
---
[Done]
- src/core/common/utility.go
- func GetConnConfig(ConnConfigName string) (ConnConfig, error)
- func GetConnConfigList() (ConnConfigList, error)
- func GetRegion(RegionName string) (Region, error)
- func GetRegionList() (RegionList, error)
- src/core/mcir/securitygroup.go
- func CreateSecurityGroup(nsId string, u *TbSecurityGroupReq) (TbSecurityGroupInfo, error)
- src/core/mcir/spec.go
- func LookupSpecList(connConfig string) (SpiderSpecList, error)
- func LookupSpec(connConfig string, specName string) (SpiderSpecInfo, error)
- src/core/mcir/sshkey.go
- func CreateSshKey(nsId string, u *TbSshKeyReq) …
=> Use Resty for REST client part

src/api/grpc/cbadm/test/official/README.md, src/api/grpc/cbadm/test/official/conf.env, src/api/grpc/request/test/test_api.go, src/core/common/namespace.go, src/core/common/utility.go, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/obsolete/publicip.go, src/core/mcir/obsolete/subnet.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go, src/core/mcis/control.go, test/obsolete/clear-tools/all_delete.sh, test/obsolete/full_test.sh, test/official/7.spec/unregister-all-specs.sh, test/official/README.md, test/official/conf.env
Resolves #146 
- `GenId()` 함수에 replace 로직 추가
- underscore -> hyphen
- uppercases -> lowercases
- 사용자가 입력한 name 도 `GenId()` 함수를 거쳐 TB object name 으로 사용
- 모든 테스트 스크립트에서 대문자 -> 소문자 (예: `NS-01` -> `ns-01`)
---
Resolves #269 
- 버그 수정
---
테스트 수행 완료
=> Add uppercase and underscore replacing logic in GenId()

src/core/mcir/common.go, src/core/mcis/control.go
=> Fix bug in MCIR functions

go.sum, src/api/rest/server/common/utility.go, src/api/rest/server/mcir/common.go, src/api/rest/server/mcir/image.go, src/api/rest/server/mcir/securitygroup.go, src/api/rest/server/mcir/spec.go, src/api/rest/server/mcir/sshkey.go, src/api/rest/server/mcir/vnet.go, src/api/rest/server/mcis/control.go, src/core/mcir/obsolete/subnet.go
- Related: https://github.com/cloud-barista/cb-ladybug/pull/6#discussion_r508939004
- Resolves #280
=> Fix REST API server functions' HTTP status codes

README.md, src/core/mcis/control.go, src/core/mcis/monitor.go
- Fix: CB-Dragonfly 가 없는 경우 발생하는 서버 오류 수정. (CB-Dragonfly Endpoint가 지정되지 않아도 MCIS 생성 가능)
- Prepare pre-release: Readme 업데이트
- Prepare pre-release: Pre-release를 위한 전체 테스트 결과
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./create-mcis-for-df.sh aws 1 df
[Test for AWS]
[Single excution for a CSP region]
[Test for AWS]
{
"ProviderName" : "AWS",
"DriverLibFileName" : "aws-driver-v1.0.so",
"DriverName" : "aws-driver01"
} …
```
=> Test and fix bug for pre-release

src/api/rest/server/mcir/spec.go, src/api/rest/server/server.go, src/core/common/namespace.go, src/core/mcir/spec.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/7.spec/range-filter-specs.sh, test/official/7.spec/test-update-spec.sh
- Closes #298 
- Resolves #300 
- Resolves #301 
---
[Request]
`cb-tumblebug/test/official/7.spec# ./range-filter-specs.sh | less`
```Shell
curl -H "${AUTH}" -sX GET http://$TumblebugServer/tumblebug/ns/$NS_ID/resources/filterSpecsByRange -H 'Content-Type: application/json' -d \
'{ 
"num_vCPU": {
"min": 2,
"max": 4
}, 
"mem_GiB": {
"min": 4
},
"storage_GiB": {
"max": 400
}
}'
```
---
[Response]
```
{
"spec" : [
{
"num_vCPU" : 2,
"orderInFilteredResult" : 0,
"id" : "aws-us-east-1-a1.large",
"evaluationStatus" : "",
"evaluationScore_01" : 0,
"evaluationScore_09" : 0,
"name" : "aws-us-east-1",
"storage_GiB" : 0,
"num_core" : 0,
"evaluationScore_04" : 0, …
```
=> Add 'FilterSpecsByRange' and 'UpdateSpec' function

src/api/rest/server/mcir/image.go, src/api/rest/server/server.go, src/core/mcir/image.go, src/core/mcir/spec.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/6.image/test-search-image.sh
- Resolves #288 
---
[Request]
`cb-tumblebug/test/official/6.image# ./test-search-image.sh | less`
```
curl -H "${AUTH}" -sX GET http://$TumblebugServer/tumblebug/ns/$NS_ID/resources/searchImage -H 'Content-Type: application/json' -d \
'{ 
"keywords": [
"ubuntu",
"18.04"
]
}'
```
---
[Response]
```
{
"image" : [
{
"cspImageName" : "Deep Learning AMI (Ubuntu 18.04) Version 25.0",
"cspImageId" : "ami-0fbf39ab5a7712f56",
"description" : "MXNet-1.5.0, TensorFlow-1.14, PyTorch-1.2, Keras-2.2, Chainer-6.1,                         configured with NVIDIA CUDA, cuDNN, NCCL, Intel MKL-DNN, Docker & NVIDIA-Docker. For a fully managed experience, check: …
```
=> Add 'SearchImage' function

src/api/rest/server/mcis/orchestration.go, src/api/rest/server/server.go, src/core/common/utility.go, src/core/mcis/control.go, src/core/mcis/orchestration.go, src/core/mcis/utility.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/8.mcis/create-mcis-policy.sh, test/official/8.mcis/delete-mcis-policy-all.sh, test/official/8.mcis/delete-mcis-policy.sh, test/official/8.mcis/get-mcis-policy.sh, test/official/8.mcis/list-mcis-policy.sh
Add skeleton code for policy-based auto mcis control.
Included functions
1. create/get/list/delete mcis policy obj
2. scheduler for periodic checking of mcis policy objs
=> Add skeleton code for policy-based auto mcis control

src/core/common/common.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go, test/official/8.mcis/create-mcis-policy.sh, test/official/8.mcis/delete-mcis-policy.sh
Implement mcis orchestration except actual action control
다음과 같은 auto control 을 위한 state machine 구현 코드 입니다. 
(단, 실재 vm 추가 생성 등의 action은 일어나지 않습니다.)
=> Implement mcis orchestration except actual action control

conf/setup.env, src/core/common/common.go, src/core/common/config.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go, test/official/8.mcis/create-mcis-policy.sh
- MCIS 자동 제어 진단시, 이동평균 적용
- MCIS 자동 제어 정책 주기(duration) 지정을 위한 환경변수 추가
=> Enhance autoControlPolicy checking statistics

src/core/common/config.go, src/core/mcis/orchestration.go, src/main.go, test/official/8.mcis/create-mcis-policy.sh
- Add mcis auto control policy status-stabilizing
=> Add mcis auto control policy status-stabilizing

assets/scripts/runLoadMaker.sh
Update runLoadMaker.sh with minor text change
=> Update runLoadMaker.sh with minor text change

go.sum, src/api/rest/server/mcis/control.go, src/core/mcis/control.go, test/official/8.mcis/create-mcis-policy.sh
Fix error for get mcis status list
=> Fix error for get mcis status list

src/core/mcis/control.go, src/core/mcis/orchestration.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/8.mcis/create-mcis-policy.sh, test/official/8.mcis/create-single-vm-mcis.sh, test/official/8.mcis/delete-mcis-policy.sh, test/official/8.mcis/get-mcis-policy.sh, test/official/8.mcis/status-mcis.sh, test/official/conf.env, test/official/sequentialFullTest/deploy-nginx-mcis-vm-withGivenName.sh
- Multi region script enhancement
- Support execution of a post command after scaleout
- Support multiple auto policy
=> Functional enhancements for auto control policy

src/docs/docs.go, src/docs/swagger.json, src/docs/tbapi-0.2.8.yaml, src/main.go
Update api docs for espresso staging
=> Update api docs for espresso staging

CHANGELOG.md
=> Update changelog for espresso

src/api/rest/server/mcis/control.go, src/core/mcis/control.go, test/official/8.mcis/list-mcis-status.sh
This PR modifies func mcis list to have status detail.
This change is to provide API compatibility to support cb-webtool.
=> Modify func mcis list to have status detail

README.md, src/core/mcis/monitor.go, src/docs/tbapi-0.2.9.yaml, test/official/conf.env
Integration with CB-DF v0.2.8 for v0.3.0 staging
=> Integration with CB-DF v0.2.8 for v0.3.0 staging

src/api/grpc/server/common/namespace.go, src/api/grpc/server/mcir/common.go, src/api/grpc/server/mcis/utility.go, src/api/rest/server/common/namespace.go, src/api/rest/server/mcir/common.go, src/api/rest/server/mcis/utility.go, src/core/common/config.go, src/core/common/namespace.go, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go, src/core/mcis/control.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go, src/core/mcis/utility.go
- Resolves #313 
- `LowerizeAndCheck*` 함수는 주석처리했고,
`Check*` 함수를 되살렸습니다.
- `LowerizeAndCheck*` 함수 호출 부분들을
`ToLower` 호출 + `Check*` 호출 로 분리했습니다.
- 테스트 스크립트로 테스트 했습니다.
- `./testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `./cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
=> Separate LowerizeAndCheck functions

src/core/mcis/control.go
=> Fix duplicated code

.github/workflows/build-and-publish-container-image.yaml
- Resolves #359 
- Ref (How to): https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf
=> Enable [skip ci] for GitHub Actions

README.md
This PR provides `go report` tag in the main readme.
=> Update readme with go report tag

src/core/mcis/orchestration.go
This PR provides some comments in orchestration code according to recommendation of golint.
=> Add comments on orchestration code (lint)

README.md
=> Arrange tags in readme

.github/workflows/publish-multi-arch-container-images.yaml
[Hotfix]
- Delete a condition, if: github.event_name != 'pull_request'
=> Fix docker login failure on workflow

.github/workflows/auto-merge.yml, .github/workflows/build-amd64-container-image.yaml, .github/workflows/prow-commands.yml, .github/workflows/publish-multi-arch-container-images.yaml
=> Specify workflow base image to ubuntu-18.04

README.md
=> Update badges' href, and Add Swagger API Doc badge

README.md, go.mod
Change go version of go.mod to 1.14
to be aligned with Docker image build version.
=> Change go version of go.mod to 1.14

.github/workflows/publish-multi-arch-container-images.yaml
=> Disable multi-arch container image build

.github/workflows/prow-commands.yml
- Update `prow-commands.yml` workflow
- Add `pull_request_review_comment` event on the workflow
- Add types `edited` on both `issue_comment` and `pull_request_review_comment` event
=> Trigger pull_request_review_comment on the prow-commands workflow

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement-request--------.md, .github/ISSUE_TEMPLATE/feature-request----------------.md, .github/ISSUE_TEMPLATE/general-question--------.md
=> Update issue templates

.github/workflows/publish-multi-arch-container-images.yaml
- Resolves #420
> **What would you like to be enhanced**
> : 
> Container image tag: edge => latest
> 
> **Why is this needed**
> : 
> 널리 통용되고 있지 않은 `edge` 라는 태그 대신
> 널리 통용되고 있는 `latest` 라는 태그로 publish 하도록 변경
> (@powerkimhub 님과의 협의를 통해 도출되었습니다.)
=> Change container image tag: edge => latest

test/official/1.configureSpider/get-cloud.sh, test/official/1.configureSpider/register-cloud.sh, test/official/6.image/registerImageWithInfo.sh, test/official/common-functions.sh, test/official/conf.env, test/official/credentials.conf.example, test/official/misc/get-conn-config.sh
[Test result]
`❯ ./testAll-mcis-mcir-ns-cloud.sh mock 1 jhseo`
```
{
"monAgentStatus" : "notInstalled",
"private_ip" : "1.2.3.4",
"targetStatus" : "None",
"name" : "mock-seoul-jhseo-1",
"location" : {
"longitude" : "126.7780",
"cloudType" : "mock",
"latitude" : "37.2665",
"briefAddr" : "Seoul  South Korea",
"nativeRegion" : "default"
},
"status" : "Running",
"public_ip" : "4.3.2.1",
"id" : "mock-seoul-jhseo-1",
"csp_vm_id" : "mock-seoul-jhseo-1",
"targetAction" : "None",
"native_status" : "Running"
},
{
"status" : "Running",
"public_ip" : "4.3.2.1",
"location" : {
"longitude" : "126.7780",
"cloudType" : "mock",
"latitude" : "37.2665",
"briefAddr" : "Seoul  South Korea",
"nativeRegion" : "default"
},
"native_status" : "Running",
"csp_vm_id" : "mock-seoul-jhseo-2",
"id" : …
```
=> Add support for the mock driver

assets/cloudlocation.csv, test/official/1.configureSpider/register-cloud.sh, test/official/common-functions.sh, test/official/conf.env, test/official/credentials.conf.example
To support openstack provider(driver).
Please check test results in detail. https://github.com/cloud-barista/cb-tumblebug/discussions/430
=> Support openstack provider

src/api/rest/server/mcis/control.go, src/api/rest/server/server.go, src/core/mcis/control.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/8.mcis/add-vmgroup-to-mcis.sh, test/official/8.mcis/just-terminate-mcis.sh, test/official/common-functions.sh, test/official/conf.env, test/official/credentials.conf.example, test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh, test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
4종 클라우드 100개 이상의 VM으로 구성된 MCIS를 쉽게 배치할 수 있도록 테스트 코드와 소스 코드 등을 여러측면에서 개선.
===
4종 클라우드(aws, gcp, azure, alibaba)의 글로벌 리젼을 활용한 대규모 MCIS (100개 이상의 VM) 생성 
---
4종 클라우드의 총 13개 리젼을 활용하여, 128개의 VM으로 구성된 MCIS 생성 테스트 완료. (131개 요청 중 128개 정상 동작. GCP쪽 오류)
- MCIS 1회 프로비저닝 테스트 소요 시간: 약 20분 (삭제 시간: 10~20분)
- 불안정한 클라우드 및 연동 동작으로 비정상적인 VM이 가끔 발생함. 빠르게 반복된 API 요청에 의해 발생한 문제일 수 있음.
```
{ { [
....,
{
"native_status" : "Running",
"monAgentStatus" : "notInstalled",
"private_ip" : "192.168.1.7",
"status" : "Running",
"location" : {
"briefAddr" : "Frankfurt  Germany",
"latitude" : "50.1109",
"longitude" : "8.6821",
"cloudType" : "gcp",
"nativeRegion" : "europe-west3"
},
"csp_vm_id" : "gcp-europe-west3-etri-9",
"id" : "gcp-europe-west3-etri-9",
"public_ip" : "ㅌㅌㅌㅌ",
"name" : "gcp-europe-west3-etri-9", …
```
=> Support massive vm deployment with vmgropup enhancement

src/core/mcis/control.go, src/core/mcis/monitor.go, src/core/mcis/utility.go
- Resolves #427
[설명]
- [Spider 변경사항](https://github.com/cloud-barista/cb-spider/issues/334#issuecomment-805572885) 반영
- (Spider 의 REST 응답을 Unmarshal 하는 데에 사용되는) `SpiderVMInfo` struct에 `SSHAccessPoint` 필드 추가
- [Dragonfly 변경사항](https://github.com/cloud-barista/cb-dragonfly/pull/72/files) 반영
- (Dragonfly 에 보낼 API 요청을 만들기 위해 필요한) `MonAgentInstallReq` struct에 `Port` 필드 추가
- Tumblebug 변경
- `TbVmInfo`, `TbVmStatusInfo` struct에 `SSHPort` 필드 추가
- `McisStatusInfo` struct에 `MasterSSHPort` 필드 추가
- `GetVmIp` 함수가 `vmIp` + 추가로 `sshPort` 도 리턴하도록 수정
- `vmIp` 를 인자로 받던 함수들이, `sshPort` 도 인자로 받도록 수정
[테스트 결과]
- Dragonfly agent 설치 성공했음을 Tumblebug 로그 메시지에서 확인
```
Called CB-DRAGONFLY API
HTTP Status code 200
[GetVmObject]aws-ap-southeast-1-jhseo, VM:aws-ap-southeast-1-jhseo-0
result {"message":"agent installation …
```
=> Add codes to handle SSHAccessPoint

src/core/mcis/monitor.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, test/official/sequentialFullTest/deploy-dragonfly-docker.sh
Fix agent installation bug and script update
참고) #436 에 대해 업데이트 되지 않은 API 규격을 문서에 반영함.
=> Fix agent installation bug and script update

test/official/6.image/registerImageWithId.sh, test/official/README.md, test/official/conf.env, test/official/sequentialFullTest/create-mcis-for-df.sh, test/official/sequentialFullTest/test-mcir-ns-cloud.sh, test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
Change script code to avoid system error
image 오브젝트 생성시, cb-spider를 통한 이미지 정보 룩업에 오류가 발생하여,
임시로, 코드를 수정함. #442 가 해결되는 경우, 다시 복구 필요.
+ 리드미 현행화 추가
+ GCP 테스트 스팩 타입을 상향함. (f2-micro는 간단한 테스트시에 메모리 부족 오류가 자주 발생함)
=> Change script code to avoid system error

src/core/common/namespace.go, src/core/mcis/control.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go, test/official/1.configureSpider/register-cloud.sh, test/official/5.sshKey/create-sshKey.sh, test/official/8.mcis/status-mcis.sh, test/official/conf.env
- Sleep code in parallel VM deployment. (for stability)
- Remove some print codes.
- Add CreatedTime in VM obj. (API doc)
---
- Test all GCP regions and make they work.
- Add some alibaba regions in the conf.env of testing.
---
=> Cleanup source with provisioning enhancement

test/official/sequentialFullTest/deploy-weavescope-to-multi-mcis.sh
Usage:
```
❯ ./deploy-weavescope-to-multi-mcis.sh aws-ap-southeast-1-jhseo aws-ca-central-1-jhseo aws-us-west-1-jhseo
```
- [맨 마지막 argument 로 지정한 MCIS 의 MasterVM] 이
대대장 VM 역할을 합니다.
=> Add 'Deploy WVSCOP to multi MCIS' script

test/official/sequentialFullTest/gen-sshKey.sh
[MCIS 생성]
`./createAll-mcis-mcir-ns-cloud.sh all 1 shson03 1 ../testSet.env`
[SSH 키 파일 생성 및 접속 주소 리턴]
`./gen-sshKey.sh all 1 shson03 ../testSet.env`
[결과]
```
[GENERATED PRIVATE KEY (PEM, PPK)]
[MCIS INFO: avengers-shson03]
[VMIP]: 54.151.131.3   [MCISID]: MCISID   [VMID]: aws-ap-southeast-1-shson03-lead-0
./sshkey-tmp/aws-ap-southeast-1-shson03.pem 
./sshkey-tmp/aws-ap-southeast-1-shson03.ppk
[VMIP]: 54.193.48.240   [MCISID]: MCISID   [VMID]: aws-us-west-1-shson03-0
./sshkey-tmp/aws-us-west-1-shson03.pem 
./sshkey-tmp/aws-us-west-1-shson03.ppk
[VMIP]: 3.96.124.148   [MCISID]: MCISID   [VMID]: aws-ca-central-1-shson03-0
./sshkey-tmp/aws-ca-central-1-shson03.pem 
./sshkey-tmp/aws-ca-central-1-shson03.ppk
[SSH COMMAND EXAMPLE]
[VMIP]: 54.151.131.3   [MCISID]: MCISID   [VMID]: …
```
=> Enhance ssh key file generation

test/official/8.mcis/resume-mcis.sh, test/official/sequentialFullTest/command-mcis-custom.sh
다음과 같이 사용하면 됩니다.
~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ 
`./command-mcis-custom.sh all 1 shson04 ../testSet.env "ls -al"`
```
[all CSP regions (AWS, Azure, GCP, Alibaba,  ...)]
{
"result_array": [
{
"mcis_id": "avengers-shson04",
"vm_id": "aws-ap-southeast-1-shson04-lead-0",
"vm_ip": "",
"result": "total 36\ndrwxr-xr-x 5 ubuntu ubuntu 4096 Apr 16 04:11 .\ndrwxr-xr-x 3 root   root   4096 Apr 16 04:02 ..\n-rw------- 1 ubuntu ubuntu   33 Apr 16 04:14 .bash_history\n-rw-r--r-- 1 ubuntu ubuntu  220 Apr  4  2018 .bash_logout\n-rw-r--r-- 1 ubuntu ubuntu 3771 Apr  4  2018 .bashrc\ndrwx------ 2 ubuntu ubuntu 4096 Apr 16 …
```
=> Fix custom remote control script

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/mcis/control.go
=> Cleanup duplicated codes in control.go

src/core/mcis/control.go
MCIS 정보 조회시, 시퀀셜하게 VM 상태 조회를 진행하여 속도가 느렸음.
병렬 처리하여 속도를 향상시킴. (+코드 정리)
=> Enhance Get MCIS info speed

assets/cloudlocation.csv, src/api/rest/server/mcis/control.go, test/official/conf.env, test/official/credentials.conf.example, test/official/testSet.env
Related discussion: #472 (Test for supporting Cloud-Twin)
=> Update scripts to support Cloud-Twin

test/official/credentials.conf.example
=> Fix bug in credentials.conf.example

test/official/sequentialFullTest/deploy-jitsi-to-mcis.sh, test/official/sequentialFullTest/update-dns-for-mcis-ip.sh
How to use
./createAll-mcis-mcir-ns-cloud.sh all 1 shson52 ../testSetCustom.env
**./update-dns-for-mcis-ip.sh** all 1 shson52 ../testSetCustom.env /hostedzone/xxxxxxxxxxxxxWOY9B7T etri.cloud-barista.org
./deploy-jitsi-to-mcis.sh all 1 shson52 ../testSetCustom.env xxx@exxi.re.kr etri.cloud-barista.org
=> Auto DNS update for jitsi

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/mcis/control.go
Resolve https://github.com/cloud-barista/cb-tumblebug/issues/124 partially. 
Thanks to @jihoon-seo for the suggestion :)
=> Remove CorePostMcis func

go.mod, go.sum, src/api/rest/server/common/config.go, src/api/rest/server/server.go, src/core/common/common.go, src/core/common/config.go, src/core/common/namespace_test.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/main.go, src/testclient/scripts/8.mcis/status-mcis.sh
Code cleaning with cb-store0.3.2 cb-sp0.3.7 cb-df0.3.3 integration
fix #486 
1) CB-TB 시스템 실행시, 출력 내용 정리 (fix #486 by cb-store-v0.3.2)
2) Fix wrong request body in API docs (common.ConfigInfo  -> common.ConfigReq in RestGet(All)Config)
3) cb-sp-v0.3.7 cb-df-v0.3.3 integration test
=> Code cleaning with cb-store0.3.2 cb-sp0.3.7 cb-df0.3.3 integration

src/api/rest/server/mcir/spec.go, src/api/rest/server/mcis/orchestration.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
=> Fix api doc for swagger vaildation

src/api/rest/server/mcir/image.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
=> Fix api searchImage for swagger validation

src/testclient/scripts/7.spec/fetch-specs.sh, src/testclient/scripts/7.spec/lookupSpec.sh, src/testclient/scripts/7.spec/lookupSpecList.sh, src/testclient/scripts/7.spec/unregister-all-specs.sh, src/testclient/scripts/common-functions.sh, src/testclient/scripts/testSet.env
Provide elapsed time for spec tests.
```
[DATE: 03/05/2021 16:14:40] [ElapsedTime: 917s (15m:17s)] [Command: ../7.spec/fetch-specs.sh all 1 shson2 ../testSetCustom.env]
```
=> Provide elapsed time for spec tests

src/api/rest/server/mcir/image.go, src/api/rest/server/mcir/spec.go, src/api/rest/server/server.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/testclient/scripts/6.image/fetch-images.sh, src/testclient/scripts/6.image/test-search-image.sh, src/testclient/scripts/7.spec/filter-specs.sh, src/testclient/scripts/7.spec/range-filter-specs.sh
Change get method to post in spec image
fix #489
Get with Query Param (Query URL이 다소 복잡)
**Post with JSON Body (조회인데 Post라 마음이 불편함)**
Get with JSON (기존 방식, Forced, Swagger 에서는 정상 동작하지 않음)
Get with Path Param (리소스 Path에 해당하지 않는 경우 있음. 다른 오류도 발생 가능)
=> Change get method to post in spec image

src/docs/v0.3.5.yaml
Add API doc v0.3.5 for v0.3.5 prerelease
=> Add API doc v0.3.5 for v0.3.5 prerelease

go.mod, go.sum, src/docs/swagger.yaml
Update gomod and swagger for swag v1.7
=> Update gomod and swagger for swag v1.7

src/docs/v0.3.6.yaml
Add v0.3.6.yaml for prerelease staging
=> Add v0.3.6.yaml for prerelease staging

src/testclient/scripts/sequentialFullTest/ansibleAutoConf/README.md, src/testclient/scripts/sequentialFullTest/ansibleAutoConf/deploy-nginx-web-server.yml, src/testclient/scripts/sequentialFullTest/conf-ansible-env.sh
=> Add ansible nginx example

src/testclient/scripts/1.configureSpider/get-cloud.sh, src/testclient/scripts/1.configureSpider/register-cloud.sh, src/testclient/scripts/1.configureSpider/unregister-cloud.sh, src/testclient/scripts/conf.env, src/testclient/scripts/credentials.conf.example
- Update Alibaba Ubuntu image name
- Replace `[INDEX]` with `[$INDEX]` in test scripts
- Fix bug in `credentials.conf.example`
=> Update Alibaba Ubuntu image name

src/api/grpc/cbadm/proc/connectinfos.go
- conn config 가 존재하지 않을 경우 에러 발생하는 버그 수정
=> Fix list conn config

src/core/mcir/image.go, src/core/mcir/spec.go
- Resolves #538
[테스트 결과]
- Image: AWS, Alibaba 에 대해 테스트
```
❯ ./fetch-images.sh
{
"message": "Fetched 8620 images (from 2 connConfigs)"
}
```
- Spec: AWS, Alibaba, GCP, Azure 에 대해 테스트
```
❯ ./fetch-specs.sh
{
"message": "Fetched 2030 specs (from 4 connConfigs)"
}
[DATE: 27/05/2021 16:22:05] [ElapsedTime: 16s (0m:16s)] [Command: ./fetch-specs.sh ]
```
=> Add RefineImageName & RefineSpecName functions

src/api/rest/server/common/utility.go, src/api/rest/server/mcis/control.go, src/api/rest/server/mcis/monitor.go, src/api/rest/server/mcis/orchestration.go, src/api/rest/server/mcis/plan.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
=> Fix API description

conf/setup.env
=> Provide comment to setup.env

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/mcis/control.go
- Change core function name
- Merge duplicated getStatus funcs (CoreGetMcisAction, GetMcisAction)
=> Make up source code

src/core/common/utility.go, src/core/mcir/image.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go, src/core/mcis/control.go
- Fix meaningless error message
- Enhance mcis lifecycle representation (Failed to Partial-Failed)
=> Fix meaningless error message

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/common/utility.go, src/core/mcis/control.go, src/core/mcis/orchestration.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/testclient/scripts/8.mcis/terminate-and-delete-mcis.sh
1) Enhance error handling
2) Delete MCIS force option (remove MCIS object regardless of MCIS status)
=> Enhance error handling

src/docs/v0.3.8.yaml
Add v0.3.8 api doc for staging v0.3.8 pre-release
=> Add v0.3.8 api doc for staging v0.3.8 pre-release

src/api/grpc/cbadm/testclient/scripts/conf.env, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/clean-all.sh, src/api/grpc/cbadm/testclient/scripts/testSet.env, src/testclient/scripts/conf.env, src/testclient/scripts/credentials.conf.example, src/testclient/scripts/testSet.env
- In `src/api/grpc/cbadm/testclient/scripts/`
- `NSID=cb`
- `MCISPREFIX=cb`
- Update Tencent cloud related test configs
=> Update test configs

README.md
@sykim-etri 님께도 확인을 부탁드립니다.. ^^
- Resolves #604
- Related issue: #584
=> Update test script details in README

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/mcis/control.go, src/core/mcis/utility.go, src/docs/v0.3.10.yaml
fix #599
fix #576 
Prepare 0.3.10
=> Fix list object key parsing bug

README.md
=> Update README regarding TB's setup & run

README.md
=> Enhance readme description

src/testclient/scripts/sequentialFullTest/gen-sshKey.sh
Fix typo in gen-sshKey.sh
MCIRID -> MCISID
=> Fix typo in gen-sshKey.sh

.github/workflows/build-amd64-container-image.yaml, .github/workflows/publish-multi-arch-container-images.yaml, README.md, src/api/grpc/cbadm/testclient/scripts/8.mcis/create-mcis-policy.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-dragonfly-docker.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-loadMaker-to-mcis.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-nginx-mcis-vm-withGivenName.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-nginx-mcis-with-loadmaker.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-nginx-mcis.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-spider-docker.sh, src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/deploy-tumblebug.sh, src/api/rest/docs/v0.3.11.yaml, src/core/mcis/monitor.go, src/testclient/scripts/8.mcis/create-mcis-policy.sh, src/testclient/scripts/conf.env, src/testclient/scripts/sequentialFullTest/deploy-dragonfly-docker.sh, src/testclient/scripts/sequentialFullTest/deploy-game-js.sh, src/testclient/scripts/sequentialFullTest/deploy-loadMaker-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-nginx-mcis-vm-withGivenName.sh, src/testclient/scripts/sequentialFullTest/deploy-nginx-mcis-with-loadmaker.sh, src/testclient/scripts/sequentialFullTest/deploy-nginx-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-spider-docker.sh, src/testclient/scripts/sequentialFullTest/deploy-tumblebug.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-mcis-update.sh
- master -> main branch
- Tested with CB-Spider 0.3.15, CB-Dragonfly 0.3.7 (apply api update)
- Prepare API doc for v0.3.11
=> Prepare v0.3.11 pre-release

src/api/grpc/cbadm/testclient/scripts/conf.env, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/core/mcis/control.go, src/core/mcis/monitor.go, src/testclient/scripts/README.md, src/testclient/scripts/conf.env
1) cleanup print
2) Apply CB-DF monitoring installation parameter (cspType)
3) Fix wrong API description for MCIS command and agent installation
=> Prepare v0.3.12 pre-release 

src/api/rest/docs/v0.4.0.yaml
=> Add v0.4.0.yaml API

src/core/mcis/control.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go
- 일부 public 이 필요없는 변수들을 private으로 변경
- 임의의 코멘트 추가
=> Enhance comments and variables for lint

src/main.go
=> Fix error regarding OpenSQL()

src/testclient/scripts/3.vNet/create-vNet.sh
CSP에 따라서 독립적인 CIDR이 가상 네트워크 (VPC 네트워크)에 할당되도록 스크립트 개선
=> Modify net script to isolate vNet CIDR of CSPs

src/core/common/utility.go, src/core/mcis/control.go, src/core/mcis/plan.go
=> Remove dup function (`GetRegionInfo`)

src/testclient/scripts/sequentialFullTest/check-network-performance.sh
Fix #665 partially. 
**사용 방법**
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/sequentialFullTest$ 
1. `./create-all.sh` all 1 shson02 ../testSetCombination.env 로 MCIS 생성.
2. `./check-network-performance.sh` all 1 shson02 ../testSetCombination.env
**출력 결과 예시 (MCIS 내부의 VM들을 PrivateIP 로 Ping 테스트)**
```
[Check jq and putty-tools package (if not, install)]
[GENERATED PRIVATE KEY (PEM, PPK)]
[MCIS INFO: mc-shson02]
IPLIST: 54.255.143.90 52.221.199.111 18.136.103.253 104.155.192.147 35.201.238.215 34.80.168.89
PRIVIPLIST: 192.168.2.200 192.168.2.204 192.168.2.107 192.168.3.4 192.168.3.2 192.168.3.3
IPCOMBLIST: 54.255.143.90 …
```
=> Add check-network-performance.sh

README.md
testscript 활용 방법에 대한 자세한 설명 추가
=> Improve instruction details in readme

README.md
유효하지 않은 링크에 # 을 추가하여 링크 완성 (anchor link)
=> Fix invalid links in README.md (Task 1)

src/testclient/scripts/8.mcis/delete-mcis.sh, src/testclient/scripts/8.mcis/terminate-mcis.sh
=> Fix bug on MCIS test scripts

src/core/common/utility.go
Update comments in core utilty.go
According to golint. (except the rule for abbreviation such as ID)
=> Update comments in core utilty.go

src/api/rest/server/mcis/control.go, src/api/rest/server/server.go
=> Remove unnecessary REST API codes

src/core/mcis/control.go
- Update comments in control.go according to golint
- (minor) Disable McisCmdReqStruct validation for a command (command field doesn't need common.CheckString(u.Command))
=> Update comments in control.go according to golint

README.md
Add contribution guide to readme
ref) #663
=> Add contribution guide to readme

src/testclient/scripts/sequentialFullTest/create-all.sh
I'd like to update `create-all.sh` to apply the following:
- Add recursive confirmation prompt (to ask again for incorrect input)
- Allow uppercase or lowercase letters (Y, y, N, n)
=> Apply recursive confirmation prompt

src/testclient/scripts/common-functions.sh, src/testclient/scripts/sequentialFullTest/create-all.sh
=> Verify cb-tb and cb-sp are ready

src/testclient/scripts/1.configureSpider/get-cloud.sh, src/testclient/scripts/1.configureSpider/list-cloud.sh, src/testclient/scripts/1.configureSpider/register-cloud.sh
- Related PR: #738 
[Region, Zone]
```JSON
{
"RegionName": "mock-seoul",
"ProviderName": "MOCK",
"KeyValueInfoList": [
{
"Key": "Region",
"Value": "default"
},
{
"Key": "Zone",
"Value": "default"
}
]
}
```
이런 형식으로 와서
jq로는 어떻게 하는 것이 좋을지 몰라서
일단 빈 칸으로 두었습니다.
---
`❯ ./register-cloud.sh -n jhseo -c mock -r 1`
```
// POSTFIX:jhseo // TestSetFile:../testSet.env // CSP:mock // REGION:1 // OPTION01: // OPTION02: // OPTION03:
AUTH: Authorization: Basic ZGVmYXVsdDpkZWZhdWx0
TumblebugServer: localhost:1323
NSID: tb01
INDEX: 13
REGION: 1
{CONN_CONFIG[13,1]}: mock-seoul
POSTFIX: jhseo
[Cloud Driver] mock-driver01
DriverName     ProviderName …
```
=> Tablize output of Spider cloud config REST API test scripts

README.md
FIxed the Typos in README as desired
README에 있던 typo를 개선하였습니다.
=> [#748] Typo in README fixed

i18n/README-EN.md
This PR consist following tasks
이 PR은 다음 task들에 대한 PR입니다.
Had problems with PR due to some commits from different branch was applied to this PR so it took some time.
PR중 commit이 꼬여서 다시 작업해서 PR 올립니다
Thank you
감사합니다.
=> [#655] [Enhancement/655] Task 1 and Task 2

docs/designUML/README.md, docs/designUML/seq-create-mcis.puml
For #265
Some references,
- https://plantuml.com/ko/sequence-diagram
- https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
This is still WIP. Needs enhancement ;)
=> Initiate UML design documentation

scripts/runContainer.sh, scripts/runMapUI.sh, scripts/runTumblebug.sh
=> Enhance runContainer scripts

scripts/runContainer.sh, scripts/runTumblebug.sh
=> Add public endpoint retrieve in runTumblebug cont

scripts/runContainer.sh
=> Add message to access container

src/core/mcir/common.go
=> Fix Korean comments in common.go

src/core/mcir/spec.go
=> Fix Korean comments in spec.go

src/core/mcir/sshkey.go
=> Fix comments in sshkey.go

src/core/mcir/image.go
Fix #566 partially.(Task 2)
영어 설정 을 Set으로 변경
=> Fix comments in image.go

src/core/mcir/securitygroup.go, src/core/mcis/control.go
Fix #566 partially. (Task3, 6)
Related files:
- src/core/mcir/securitygroup.go
- src/core/mcis/control.go
=> Translate Korean comments to English

src/core/mcir/common.go
=> Fix comments about TbInspectResourcesResponse in src/core/mcir/common.go

src/core/mcir/common.go
I have modified the file to meet the golint requirement for #783 Task 3.
Thank you
=> [#783] Task 3 Completion

README.md
Fixes #793 
Removed lines 423-424 from the README.md
=> removed misleading content from the README.md

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/core/mcis/control.go, src/core/mcis/monitor.go, src/core/mcis/orchestration.go, src/core/mcis/plan.go, src/core/mcis/sshrun.go, src/core/mcis/utility.go
Resolve #803
- Refine function name of remote command (`CorePostCmdMcis` -> `RemoteCommandToMcis`)
- Enhance remote command speed and stability
- Move SSH-related functions to the single file (`src/core/mcis/sshrun.go`)
- Add license announcement for each file in mcis package
SSH username 확인을 위한 절차를 간소화하고, 속도 저하에 관련된 코드를 개선하였습니다.
다만, ssh 를 실제 수행하기 전, port 가 열려있는지 확인하는 checkConnection 함수가 있는데,
이 함수가 병렬 처리되지 않아서, 향후 개선이 필요합니다.
=> Enhance stability and speed of remote command feature (ssh)

src/core/mcis/remoteCommand.go, src/testclient/scripts/sequentialFullTest/deploy-jitsi-to-mcis.sh
Fix jitsi deployment error with the latest installation guide.
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#uninstall
=> Fix deploy-jitsi-to-mcis.sh 

src/testclient/scripts/conf.env, src/testclient/scripts/sequentialFullTest/check-test-config.sh, src/testclient/scripts/sequentialFullTest/create-all.sh
[new output for test script]
**$ ./create-all.sh -n colortest01 -f ../testSetCustom.env -x 2**
=> Enhance output style of scripts

src/testclient/scripts/conf.env
Resolve #450
- From `ubuntu_18_04_x64_20G_alibase_20210623.vhd` to `ubuntu_18_04_x64_20G_alibase_20210824.vhd`
=> Update Alibaba Cloud VM image ID

src/core/mcis/provisioning.go
Change MCIS provisioning meta data for not assigned IP address #816 issue
src/core/mcis/provisioning.go
Change MCIS meta data for not assigned IP address (Not assigned yet --> empty)
=> Change MCIS meta data for not assigned IP address

README.md, i18n/README-EN.md
I have managed to translate README.md 
Please leave comment if there are any typos or misleading information of the translation.
Thank you
=> [#655] Completion of README.md Translation

src/api/rest/docs/v0.4.11.yaml
=> Staging v0.4.11

scripts/runContainer.sh
Prevent Cannot kill container error
https://javahowtos.com/guides/124-docker/414-solved-cannot-kill-docker-container-permission-denied.html
add `sudo aa-remove-unknown` to script
=> Prevent Cannot kill container error

src/api/rest/docs/v0.4.10.yaml, src/api/rest/docs/v0.4.11.yaml, src/api/rest/server/common/namespace.go, src/api/rest/server/mcir/common.go, src/api/rest/server/mcir/spec.go, src/api/rest/server/mcis/control.go, src/api/rest/server/mcis/monitor.go, src/api/rest/server/mcis/orchestration.go, src/api/rest/server/mcis/recommendation.go, src/core/common/namespace.go, src/core/mcis/provisioning.go, src/testclient/scripts/2.configureTumblebug/create-ns.sh, src/testclient/scripts/conf.env, src/testclient/scripts/testSet.env
Will use default ns and mcis for examples (ns01, mcis01)
=> Improve API doc and script examples

src/testclient/scripts/conf.env
=> Add default ns for conf.env

src/core/mcir/common.go, src/core/mcis/control.go
=> Update output of DelAllResources func

src/api/rest/docs/v0.4.12.yaml
=> Staging v0.4.12 preRelease

src/api/rest/docs/v0.3.10.yaml, src/api/rest/docs/v0.3.12.yaml, src/api/rest/docs/v0.3.5.yaml, src/api/rest/docs/v0.4.0.yaml, src/api/rest/docs/v0.4.10.yaml, src/api/rest/docs/v0.4.11.yaml, src/api/rest/docs/v0.4.12.yaml, src/api/rest/docs/v0.4.4.yaml, src/api/rest/docs/v0.4.5.yaml, src/api/rest/docs/v0.4.6.yaml, src/api/rest/docs/v0.4.7.yaml, src/api/rest/docs/v0.4.8.yaml, src/api/rest/docs/v0.4.9.yaml, src/api/rest/server/common/utility.go, src/api/rest/server/mcir/common.go, src/api/rest/server/mcir/image.go, src/api/rest/server/mcir/securitygroup.go, src/api/rest/server/mcir/spec.go, src/api/rest/server/mcir/sshkey.go, src/api/rest/server/mcir/subnet.go, src/api/rest/server/mcir/vnet.go, src/api/rest/server/mcis/control.go, src/api/rest/server/mcis/monitor.go, src/api/rest/server/mcis/orchestration.go, src/api/rest/server/mcis/recommendation.go, src/api/rest/server/server.go
=> Fix API typo and tags

src/testclient/scripts/8.mcis/status-mcis.sh, src/testclient/scripts/sequentialFullTest/check-network-performance.sh, src/testclient/scripts/sequentialFullTest/conf-ansible-env.sh, src/testclient/scripts/sequentialFullTest/deploy-dragonfly-docker.sh, src/testclient/scripts/sequentialFullTest/deploy-jitsi-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-mcis-update.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis-update-noinstall.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis-update.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis.sh, src/testclient/scripts/sequentialFullTest/gen-sshKey.sh, src/testclient/scripts/sequentialFullTest/update-dns-for-mcis-ip.sh
Get MCIS
action=status -> option=status
for scripts
=> Fix outdated api option path in script

src/testclient/scripts/8.mcis/delete-mcis.sh, src/testclient/scripts/sequentialFullTest/clean-mcis-only.sh
Use option=terminate for mcis delete script
=> Use option=terminate for mcis delete script

src/testclient/scripts/conf.env
Reference
"tencent-ap-bangkok-c2-2xlarge16",
"tencent-ap-bangkok-c2-2xlarge32",
"tencent-ap-bangkok-c2-4xlarge32",
"tencent-ap-bangkok-c2-4xlarge64",
"tencent-ap-bangkok-c2-8xlarge96",
"tencent-ap-bangkok-c2-large16",
"tencent-ap-bangkok-c2-large8",
"tencent-ap-bangkok-c3-12xlarge160",
"tencent-ap-bangkok-c3-2xlarge16",
"tencent-ap-bangkok-c3-2xlarge32",
"tencent-ap-bangkok-c3-4xlarge32",
"tencent-ap-bangkok-c3-4xlarge64",
"tencent-ap-bangkok-c3-8xlarge128",
"tencent-ap-bangkok-c3-8xlarge64",
"tencent-ap-bangkok-c3-large16",
"tencent-ap-bangkok-c3-large8",
"tencent-ap-bangkok-m2-12xlarge384",
"tencent-ap-bangkok-m2-14xlarge448",
"tencent-ap-bangkok-m2-2xlarge64",
"tencent-ap-bangkok-m2-3xlarge96",
"tencent-ap-bangkok-m2-4xlarge128",
"tencent-ap-bangkok-m2-6xlarge192", …
=> Use available specs for tencent cloud

src/api/rest/docs/v0.4.14.yaml
Integration test result: CB-Tumblebug v0.4.13 with v0.4.18 #969 => v0.4.14
- https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.13
- https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.18
=> Staging v0.4.14

go.mod, go.sum
=> Update go.mod by mod tidy

src/core/mcis/manageInfo.go
- MCIS terminate 후, 조건 오류에 의해 delete 처리가 되지 않는 버그 수정
=> Fix bug in delete MCIS terminate opt

src/core/mcis/monitoring.go, src/testclient/scripts/9.monitoring/install-agent.sh
- Fix problematic error handling.
=> Fix install agent status bug

src/core/mcis/monitoring.go
switch case 문의 사용 패턴을 더 일반적인 형태로 리팩토링 하였습니다.
=> Cleanup switch-case pattern

src/api/rest/server/mcir/common.go, src/api/rest/server/mcis/control.go, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/image_test.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/spec_test.go, src/core/mcir/sshkey.go, src/core/mcir/vnet.go
- Add comments for exported functions/structs/variables
- Related issue: #882
- MCIR common functions
- vNet
- image
- spec
- SG
- SSH Key
- Update to use common function
- Resolves #876
=> Add comments for exported functions/structs/variables

src/testclient/scripts/sequentialFullTest/deploy-fps-game.sh
=> Fix deploy-fps-game for background mode

scripts/usecases/xonotic/startServer.sh, scripts/usecases/xonotic/stopServer.sh
-  Param: serverName, serverPort, numBot
Use like ..
```
wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/usecases/xonotic/startServer.sh; 
chmod +x ~/startServer.sh; 
sudo ~/startServer.sh cloud-barista-VM01 30000
```
=> Support Xonotic server configuration

src/core/mcis/control.go
Fix response message for MCIS terminate
raised from #1012
=> Fix response message for MCIS terminate

assets/cloudlocation.csv, conf/template.credentials.conf, src/testclient/scripts/conf.env, src/testclient/scripts/testSet.env
=> Add support for NHN Cloud

src/api/grpc/server/server.go, src/api/rest/server/server.go
This PR prevents terminating the main thread before the graceful shutdown is processed
Ref: #716
=> Wait until the graceful shutdown is processed

src/core/mcis/recommendation.go
=> Fix misspelled word (#1057)

src/testclient/scripts/2.configureTumblebug/create-ns.sh, src/testclient/scripts/init.sh
change relative path to absolute using $CBTUMBLEBUG_ROOT
=> Fix path issue in test scripts

src/api/grpc/server/mcir/image.go, src/api/grpc/server/mcir/securitygroup.go, src/api/grpc/server/mcir/spec.go, src/api/grpc/server/mcir/sshkey.go, src/api/grpc/server/mcir/vnet.go, src/api/rest/server/mcir/common.go, src/api/rest/server/mcir/image.go, src/api/rest/server/mcir/securitygroup.go, src/api/rest/server/mcir/spec.go, src/api/rest/server/mcir/sshkey.go, src/api/rest/server/mcir/vnet.go, src/core/mcir/common.go, src/core/mcir/securitygroup.go, src/core/mcis/utility.go
- 모든 resource type에 대해서, list all func 의 필터링 기능 추가
- filterKey, filterVal 를 통해서 필터링 
- 동작 메커니즘 참고
- 오브젝트를 표현하는 key value를 모두 포함한 JSON string을 기준으로, 
- 쿼리 파라미터로 제시된 두 스트링이 모두 포함된 오브젝트를 리스트에 포함하여 리턴 (필드 조건을 명확하게 구현하지 않음)
- 향후 가급적, 실제 filed key 에 대해서만 처리하도록 코드 개선 필요 (JSON을 Map으로 변환한 뒤, Map에 해당하는 
<html>
<body>
<div class="curl-command" style="box-sizing: border-box; position: relative; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: …
=> Add resource list filtering feature

src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go, src/api/rest/server/server.go, src/core/mcis/benchmark.go, src/core/mcis/control.go, src/core/mcis/manageInfo.go, src/core/mcis/monitoring.go, src/core/mcis/provisioning.go
=> Enhance stability and speed of TB

scripts/runSpider.sh, src/api/rest/docs/v0.6.0.yaml, src/testclient/scripts/sequentialFullTest/create-mcir-ns-cloud.sh
- [Remove register cloud option from script](https://github.com/cloud-barista/cb-tumblebug/commit/28438ff2c6430230d001bbcd07e9ed2c2cc50d02)
- [Use patched spider version 0.5.12-p1](https://github.com/cloud-barista/cb-tumblebug/commit/258679bbe55f74a1db8ff8355f5bf393d4e46a76)
- [Staging CB-TB v0.6.0](https://github.com/cloud-barista/cb-tumblebug/commit/b060557d1ae8b82acb2d67b54eee3e845c69590a)
=> Staging CB-TB v0.6.0

scripts/usecases/xonotic/startServer.sh
https://xonotic.org/posts/2022/xonotic-0-8-5-release/
=> Update xonotic usecase release v0.8.5

scripts/usecases/xonotic/startServer.sh
Tested Xonotic 0.8.5 (latest)
In Ubuntu 22.04 (LTS) OS VMs in a MCIS.
=> Update Xonotic 0.8.5 script for ubuntu 22.04 dist

assets/cloudimage.csv
=> Fix image id for EC2 debian 10

src/core/mcis/nlb.go
Provide default and example values for NLB API
to make usage easy.
=> Provide default values for NLB API

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/nlb.go, src/api/rest/server/server.go, src/core/mcir/common.go, src/core/mcis/nlb.go, src/testclient/scripts/10.nlb/addVM.sh, src/testclient/scripts/10.nlb/create-NLB.sh, src/testclient/scripts/10.nlb/removeVM.sh
Related issue: #1161
AWS, GCP, Azure에 대해
NLB target group의 VM 추가/삭제 테스트를 수행했습니다.
=> Add 'NLB VM addition/removal' feature

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/manageInfo.go, src/api/rest/server/server.go
Add API to get VMGroup list in a MCIS 
<html>
<body>
<div class="curl-command" style="box-sizing: border-box; position: relative; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px;">Curl</h4><div class="copy-to-clipboard" style="box-sizing: …
=> Add API to get VMGroup list in a MCIS

scripts/runSpider.sh
=> Update CB-Spider version for runContainer

scripts/runSpider.sh
- CB 프릴릴리스를 위한 작업.
- 기본 연동 테스트 진행 완료.
=> Update runSpider version to 0.6.11

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcir/customimage.go, src/api/rest/server/mcir/dataDisk.go, src/api/rest/server/mcis/control.go, src/api/rest/server/mcis/manageInfo.go, src/api/rest/server/mcis/nlb.go, src/api/rest/server/mcis/remoteCommand.go, src/api/rest/server/server.go, src/core/mcis/provisioning.go
- Get available dataDisk 로 API 구분
- 기존 자원 등록을 위한 POST custom image 설명 수정 (기존에는 생성으로 되어 있었음)
- Snapshot and Custom Image Management 관련 API를 동일 카테고리에 포함
=> Enhance API for nlb disk customimg

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/manageInfo.go, src/core/mcis/manageInfo.go, src/core/mcis/provisioning.go
MCIS에 포함된 VM 및 NLB의 접속 정보 (IP, DNS 등)을 종합적으로 리턴하는 기능
(CB-MapUI에 적용하여, SSH 키 다운로드 및 쉬운 접속에 활용)
<html>
<body>
<div style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px;">Request URL</h4><div class="request-url" …
=> Add get mcis access info feature

src/core/mcis/manageInfo.go, src/core/mcis/provisioning.go
=> Apply omitempty for nlb obj in mcisAccessInfo

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/provisioning.go, src/api/rest/server/server.go, src/core/mcis/provisioning.go, src/core/mcis/utility.go
=> feat: add VM to MCIS dynamically

docs/images/cb-tb-call-core-mcis.svg, docs/images/cb-tb-call-rest-mcis.svg, src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/manageInfo.go, src/core/mcis/manageInfo.go
Issue-https://github.com/cloud-barista/cb-tumblebug/issues/1232
Fixed name change
=> fix:CoreDelAllMcis to  DelAllMcis

src/core/mcis/orchestration.go
=> Fix orchestration scaleout err

conf/cloud_conf.yaml, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/nlb.go, src/api/rest/server/server.go, src/core/common/config.go, src/core/mcis/nlb.go, src/core/mcis/provisioning.go
클라우드 기반의 VM을 활용하여, SW NLB를 배포 및 제공하는 기능 PoC 
- 동작 플로우
- NLB 전용 MCIS 생성 (id는 할당하고자 하는 대상 MCIS의 id에 `-nlb` 포스트픽스를 추가한 형태로 자동 구성)
- NLB용 MCIS의 VM(s)에 NLB SW 배포
- 대상 MCIS의 VM 정보를 활용하여, NLB 설정
- 현재는 생성 기능만 제공, MC-NLB 삭제를 위해서는 해당 MCIS-nlb 를 종료 및 삭제
POST [​/ns​/{nsId}​/mcis​/{mcisId}​/mcSwNlb](http://localhost:1323/tumblebug/swagger/index.html#/[Infra%20resource]%20NLB%20management/post_ns__nsId__mcis__mcisId__mcSwNlb) Create a special purpose MCIS for NLB and depoly and setting SW NLB
요청 바디 예시
```
{
"listener": {
"port": "80",
"protocol": "TCP"
},
"targetGroup": {
"port": "80",
"protocol": "TCP"
}
}
```
리턴 바디: nlb mcis 오브젝트
- 결과 확인 방법
- 대상 MCIS에 nginx 배포
- 대상 MCIS에 NLB 생성 및 적용 (MCIS-nlb)
- MCIS-nlb 의 access info 를 조회 IP를 획득하고, 여러번 접속하여 로드벨런싱 확인 (현재 라운드로빈 구성임)
- x.x.x.x:9000 포트를 통해 NLB 현황 확인 가능 …
=> Add MC NLB service feature poc

src/core/mcis/provisioning.go, src/testclient/scripts/sequentialFullTest/test-mcis-dynamic-all-for-one.sh
For
https://cloud-barista.slack.com/archives/CJQ7575PU/p1667545289069159
=> Enhance error handling for DataDiskIds in mcis provision

src/core/mcis/provisioning.go, src/core/mcis/recommendation.go
=> Change default recommendation rule

src/api/grpc/server/mcis/control.go, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/benchmark.go, src/api/rest/server/server.go, src/core/common/config.go, src/core/mcis/benchmark.go, src/core/mcis/nlb.go, src/core/mcis/recommendation.go, src/core/mcis/remoteCommand.go, src/main.go
- 기존 MCIS에 최적(응답시간기준)의 NLB를 배포하는 특징 제공
=> Auto NLB deployment feature by global clouds latency evaluation

scripts/setweb.sh
Thanks for the tip !
@jihoon-seo
=> Make nginx demo page refresh

scripts/usecases/weavescope/startServer.sh, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/core/mcis/manageInfo.go, src/core/mcis/nlb.go, src/core/mcis/provisioning.go
ADD mcisNlbListener Field
```
[Retrieve access information for MCIS:mc-hyfoy]
{
McisId: mc-hyfoy
mcisNlbListener: {
McisId: mc-hyfoy-nlb
McisSubGroupAccessInfo: [
{
SubGroupId: nlb
McisVmAccessInfo: [
{
vmId: nlb-1
publicIP: 107.22.133.87
privateIP: 192.168.7.123
sshPort: 22
vmUserAccount: cb-user
}
]
}
]
}
McisSubGroupAccessInfo: [
{
SubGroupId: g1
nlbListener: {
protocol: TCP
ip: 
port: 80
dnsName: ns01-g1-cdnpuku7p30oepnoga0g-dc4954c34a79db2c.elb.ap-northeast-2.amazonaws.com
keyValueList: [
{
Key: LoadBalancerArn
Value: arn:aws:elasticloadbalancing:ap-northeast-2:635484366616:loadbalancer/net/ns01-g1-cdnpuku7p30oepnoga0g/dc4954c34a79db2c
}
{
Key: Port
Value: 80
}
{
Key: Protocol
Value: TCP
}
{
Key: DefaultActions
Value: [map[AuthenticateCognitoConfig:<nil> AuthenticateOidcConfig:<nil> …
```
=> Show access info of Global-NLB

conf/cloud_conf.yaml, src/core/mcis/manageInfo.go
[Get access info in parallel](https://github.com/cloud-barista/cb-tumblebug/commit/b604e4f69e0afbb5f0db931bee7b13f10736f3fa)
=> Get access info in parallel

assets/cloudimage.csv, scripts/runSpider.sh
Based on https://github.com/cloud-barista/cb-tumblebug/pull/1263#issuecomment-1318610452
=> Fix not available image ids

scripts/runSpider.sh, src/api/grpc/server/mcis/monitor.go, src/api/rest/server/mcis/monitoring.go, src/core/common/common.go, src/core/mcir/common.go, src/core/mcir/image.go, src/core/mcir/spec.go, src/core/mcis/control.go, src/core/mcis/monitoring.go, src/core/mcis/provisioning.go, src/testclient/scripts/2.configureTumblebug/load-common-resource.sh
- [Allow Termination of Suspended MCIS](https://github.com/cloud-barista/cb-tumblebug/commit/2e157c69ac29ca9fd82cd55981ffcf7bbb80f0bb)
- [Enhance image spec reg handling](https://github.com/cloud-barista/cb-tumblebug/commit/d08f6905573e3bfbedb570c096c99104fc701d21)
- [Integrate CB-DF latest](https://github.com/cloud-barista/cb-tumblebug/commit/34f4d65132e1ac866df7605039d555f3f5ce3943)
=> Various updates to prepare release

assets/cloudimage.csv, src/core/common/utility.go, src/core/mcis/monitoring.go, src/core/mcis/provisioning.go
Support Windows MCIS VM 및 에러 핸들링
(윈도우즈는 CB-SP 차원에서 보완이 필요한 상태임. 미리 대응하는 PR)
=> Support Windows MCIS VM

assets/cloudimage.csv, assets/cloudspec.csv, scripts/runSpider.sh, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcir/image.go, src/core/common/utility.go, src/core/mcir/common.go, src/core/mcis/provisioning.go, src/testclient/scripts/conf.env
Related with 
- [Debian 10 and monitoring test](https://github.com/cloud-barista/cb-tumblebug/discussions/1282) 
- [Windows server 2012 R2 provisioning test](https://github.com/cloud-barista/cb-tumblebug/discussions/1283)
=> Support debian and windows instance provisioning

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/monitoring.go, src/api/rest/server/server.go, src/core/mcis/monitoring.go
- Add set monitoring agent status manually for Windows
=> Enabling manual monitoring agent installation for Windows VM

README.md
To apply the suggestion from the issue https://github.com/badges/shields/issues/8671
https://img.shields.io/github/actions/workflow/status/cloud-barista/cb-tumblebug/build-amd64-container-image.yaml
=> Update build tag address

scripts/usecases/jitsi/startServer.sh, scripts/usecases/jitsi/statusServer.sh, src/testclient/scripts/sequentialFullTest/deploy-jitsi-to-mcis.sh
=> Script update for jitsi

scripts/runSpider.sh, scripts/usecases/xonotic/startServer.sh, src/core/mcis/control.go
- [Update spider release version for docker](https://github.com/cloud-barista/cb-tumblebug/commit/5f99684784a7c194a9fac8119c2f20ddc08519cc)
- [Fix Xonotic script code](https://github.com/cloud-barista/cb-tumblebug/commit/0850a9a292b7391e70382e14e8ed0724c3dd6d00)
- +nit
=> Update related component version and scripts

CODE_OF_CONDUCT.md, CONTRIBUTING.md
이후 진행될 Repository 초기 설정을 위한 사전 작업입니다.
=> Update CODE_OF_CONDUCT.md and CONTRIBUTING.md

src/core/mcis/remoteCommand.go
Enhance error handling code in clientConnect
scp.NewClient(sshInfo.ServerPort, &clientConfig)
=> Enhance error handling code in clientConnect

src/api/rest/server/server.go
=> Provide custom error message for request timeout

conf/setup.env
Arrange ENV variables and comments. The variable itself is not changed.
=> Arrange ENV variables and comments

.github/workflows/auto-merge.yml
https://github.com/pascalgn/automerge-action
- uses: "pascalgn/automerge-action@v0.15.6"
=> Update automerge-action version for workflow

src/api/rest/server/mcir/dataDisk.go, src/api/rest/server/mcis/manageInfo.go, src/api/rest/server/mcis/monitoring.go, src/core/common/config.go, src/core/mcis/manageInfo.go, src/core/mcis/nlb.go, src/core/mcis/orchestration.go, src/core/mcis/provisioning.go, src/core/mcis/remoteCommand.go
Refactor func names in manageInfo.
=> Refactor func names in manageInfo

src/api/rest/server/mcis/manageInfo.go, src/core/mcis/manageInfo.go, src/core/mcis/provisioning.go
- CoreGetMcisVmStatus -> GetMcisVmStatus
- GetVmStatus -> FetchVmStatus
=> Refactor func names

src/core/mcis/manageInfo.go, src/core/mcis/provisioning.go, src/core/mcis/recommendation.go
- Apply universal ExecuteHttpRequest for Create MCIS (post) and enhance readability
=> Apply universal ExecuteHttpRequest for Create MCIS (post) and enhance readability 

src/core/mcir/common.go
Enhance internal call for resource delete by using common.ExecuteHttpRequest.
=> Enhance internal call for resource delete

src/core/mcir/common.go, src/core/mcir/customimage.go, src/core/mcir/datadisk.go, src/core/mcir/firewallrule.go, src/core/mcir/image.go, src/core/mcir/securitygroup.go, src/core/mcir/spec.go, src/core/mcir/sshkey.go, src/core/mcir/subnet.go, src/core/mcir/vnet.go, src/core/mcis/benchmark.go, src/core/mcis/control.go, src/core/mcis/manageInfo.go, src/core/mcis/monitoring.go, src/core/mcis/nlb.go, src/core/mcis/snapshot.go, src/core/mcis/utility.go
- Enhance internal call for LookupSpecList
- Change variable name: tempReq to requestBody globally
=> Enhance internal call for LookupSpecList

go.mod, go.sum, src/core/mcir/spec.go, src/core/mcis/remoteCommand.go
- Remove external pkg for ssh.
- Use golang official pkg for ssh. 
- Prepare code for jump host.
=> Remove external pkg for ssh and enhance mechanism

README.md
According to https://docs.github.com/ko/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api#generating-and-submitting-a-software-bill-of-materials-sbom
Add SBOM download link.
=> Add SBOM link to README

src/api/rest/server/mcis/remoteCommand.go, src/api/rest/server/server.go
Add set & get bastion node API
=> Add set get bastion node API

go.mod
Add github.com/fsnotify/fsnotify v1.6.0 by go mod tidy
=> Update gomod to add fsnotify v1.6.0

src/testclient/scripts/sequentialFullTest/change-mcis-hostname.sh, src/testclient/scripts/sequentialFullTest/check-network-performance.sh, src/testclient/scripts/sequentialFullTest/command-mcis.sh, src/testclient/scripts/sequentialFullTest/config-hybridIP-withHosts.sh, src/testclient/scripts/sequentialFullTest/copy-file-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-docker-runtime.sh, src/testclient/scripts/sequentialFullTest/deploy-dragonfly-docker.sh, src/testclient/scripts/sequentialFullTest/deploy-fps-game.sh, src/testclient/scripts/sequentialFullTest/deploy-game-js.sh, src/testclient/scripts/sequentialFullTest/deploy-jitsi-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-loadMaker-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-nginx-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-spider-docker.sh, src/testclient/scripts/sequentialFullTest/deploy-tumblebug.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-mcis-update.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-mcis.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis-update-noinstall.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis-update.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-multi-mcis.sh, src/testclient/scripts/sequentialFullTest/start-weavescope-mcis.sh, src/testclient/scripts/sequentialFullTest/stop-weavescope-mcis.sh
- #1356 를 통해서 수정된 Remote Command API 의 요청 body에 맞게 API 활용 스크립트 수정
=> Apply changed request body of remote cmd to scripts

src/core/mcis/control.go, src/core/mcis/manageInfo.go, src/core/mcis/provisioning.go
Related with #1302 (but not fix thoroughly)
=> Fix suspend resume transition check err

src/core/common/utility.go, src/core/mcis/recommendation.go
Applied to closest and fair geo recommendations
=> Enhance recommendation speed in parallel

.github/workflows/auto-merge.yml
It has been tested on https://github.com/cloud-barista/cm-beetle/pull/21 ^^
=> Update auto-merge workflow

assets/cloudimage.csv, src/testclient/scripts/conf.env
note that the release note of the CSP does not show correct info. unfortunately.
=> Update image ids for alibaba

scripts/usecases/elastic-stack/README.md, scripts/usecases/elastic-stack/removeELK.sh, scripts/usecases/elastic-stack/removeFilebeat.sh, scripts/usecases/elastic-stack/startELK.sh, scripts/usecases/elastic-stack/startFilebeat.sh, scripts/usecases/elastic-stack/statusELK.sh, scripts/usecases/elastic-stack/statusFilebeat.sh, scripts/usecases/elastic-stack/stopELK.sh, scripts/usecases/elastic-stack/stopFilebeat.sh
This PR will provide scripts for the installation, configuration, execution, termination, and removal of Elastic Stack.
The Elastic Stack includes Elasticsearch, Logstash, Kibana (ELK Stack), and Filebeat.
Please take a look at README for a detailed explanation.
=> Add Elastic Stack scripts as a usecase

scripts/runSpider.sh
=> Update CB-Spider docker version to 0.8.0

.github/labeler.yml, .github/workflows/labeler.yml
Test configuration is as follows,
documentation:
- changed-files:
- any-glob-to-any-file: *.md
api:
- changed-files:
- any-glob-to-any-file: src/api/*
=> Add auto labeler workflow

.github/labeler.yml
based on https://github.com/actions/labeler/tree/main#pull-request-labeler
(some guide may not work correctly. requires testing)
=> Fix labeler.yml configuration

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcir/subnet.go
fill in the missing 'vNetId' parameter with the appropriate virtual network ID path string.
=> Fix api description for subnet

assets/cloudimage.csv, assets/cloudspec.csv
AWS,aws-us-east-2,ami-0c616d2c080a12072,Ubuntu 20.04
for testing.
=> Add spec image for gpu

scripts/usecases/llm/startServer.sh
sudo pip install -U vllm
sudo is required
=> Fix error in llm script

scripts/usecases/llm/llmServer.py, scripts/usecases/llm/startServer.sh, scripts/usecases/llm/statusServer.sh
- FastAPI -> Flask
- Backgroud model-loading
- Enhance start script.
=> Enhance llm usecase code

scripts/usecases/llm/llmServer.py, scripts/usecases/llm/startServer.sh
parser.add_argument('--port', type=int, default=5000, help='Port number to run the Flask app on.')
parser.add_argument('--model', type=str, default=model, help='Model name to load.')
=> Parameter passing for llm usecase

scripts/usecases/llm/llmServer.py, scripts/usecases/llm/startServer.sh
- Provide llm deploy elapsed time
- Detail description for api doc
=> Provide llm deploy elapsed time

scripts/misc/update-cloudinfo.py
- AWS 이외의 CSP에 대해서도, 정보 조회 및 업데이트할 수 있도록 일반화
- 정보 수집은 향후, cb-spider 기능 활용 가능
=> Generalize fetch region zone tool

assets/cloudinfo.yaml, scripts/misc/cloudinfo-review.yaml, scripts/misc/update-cloudinfo.py
Test code for GCP update from spider.
=> Enhance update-cloudinfo.py and update info

assets/cloudinfo.yaml, go.mod, go.sum, scripts/misc/update-cloudinfo.py, src/core/common/config.go, src/main.go
- Get and load cloudinfo.yaml into runtime variable (show it as a table when TB start)
```
/home/son/go/src/github.com/cloud-barista/cb-tumblebug/assets/cloudinfo.yaml
+------------+-------------------------+-----------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CSP        | REGION                  | LOCATION                          | (LATI:LONG) …
```
=> Get and load cloudinfo.yaml into runtime variable

assets/cloudspec.csv, scripts/initMultiCloudEnv.sh, src/api/rest/server/server.go, src/core/mcir/common.go, src/core/mcir/spec.go
Enhance error handling for register cloud assets
+ add aws gpu instance specs
=> Enhance error handling for register cloud assets

scripts/initMultiCloudEnv.sh, src/core/common/client.go, src/core/common/common.go, src/core/mcir/common.go, src/core/mcir/customimage.go, src/core/mcir/image.go, src/core/mcir/spec.go, src/testclient/scripts/1.configureSpider/register-cloud-interactive.sh
- 이미지, 스펙 등록 속도 향상
- 기존: 10분 이상, 개선: 약 6분 이내
- 스크립트 UI 개선 등
```
{
"message": "CreateNs(); The namespace ns01 already exists."
}
Loading common Specs and Images takes more than 10 minutes.
Load common Specs and Images. Do you want to proceed ? (y/n) : y
[##################################################################################################-] 98% 
```
=> Enhance registering spec image assets for initMultiCloud

scripts/initMultiCloudEnv.sh, src/core/mcir/common.go
- Reduce log lines that will be produced by initMultiCloud
- Enhance progress bar (countdown style)
```
Load common Specs and Images. Do you want to proceed ? (y/n) : y
[###                                               ] 07:24
```
=> Enhance progress bar and logging in initMuliCloud

src/testclient/scripts/conf.env, src/testclient/scripts/sequentialFullTest/force-clean-cluster-only.sh
NHN Cloud의 컨테이너 이미지 정보 업데이트와 Alibaba의 이미지 정보 등을 업데이트하였습니다.
=> Update container image id for nhncloud and image id for alibaba

assets/cloudinfo.yaml
- 모든 빈칸 채워 넣음
- 명확하지 않은 경우, 추정치임. 대략적인 위치 정보 파악에 도움.
```
7:28PM INF main.go:83 > /home/son/go/src/github.com/cloud-barista/cb-tumblebug/assets/cloudinfo.yaml
+------------+-------------------------+-----------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CSP        | REGION                  | LOCATION                          | (LATI:LONG)     | ZONES …
```
=> Update all csp regions and zones with estimated location

src/testclient/scripts/13.cluster/create-cluster.sh, src/testclient/scripts/conf.env
- 스크립트 기반 Azure k8s cluster 프로비저닝 실행을 위한, 스크립트 파라미터(e.g., K8S_VERSION) 추가
=> Add K8S_VERSION to conf.env for Azure k8s cluster

src/testclient/test-clis/vpn-tunnel/gcp-aws/README.md, src/testclient/test-clis/vpn-tunnel/gcp-aws/app.go, src/testclient/test-clis/vpn-tunnel/gcp-aws/mcisDynamic.json
* Change connection name of Azure
* Replace with Ubuntu 22.04
* Update CLI help messages
* Fix wrong API method
* Fix typo on README
=> Update the test CLI for VPN tunnel

src/core/mcis/cluster.go
Version is not equal after upgrading a cluster
검증 코드 중 오류를 수정하였습니다.
=> Fix to check a cluster version

scripts/init/init.sh
Install python3-venv if there is no.
=> Update init.sh to install python3-venv

scripts/usecases/llm/llmServer.py
Fix model agrs bug in the llm script
=> Fix model agrs bug in the llm script

scripts/usecases/llm/startServer.sh
Fix parameter handling bug in llm deploy script
=> Fix parameter handling bug in llm deploy script

src/api/rest/server/mcis/control.go
=> Fix return object err for mcis control

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcir/spec.go, src/api/rest/server/server.go, src/core/mcir/common.go, src/core/mcir/spec.go, src/core/mcis/recommendation.go
Enhance vm recommendation function by removing static codes.
Takes all the fields from FilterSpecsByRangeRequest dynamically using Reflect.
Please note that using Reflect may reduce system performance, but vm recommendation will not be invoked too frequently. I assumed it is ok.
=> Enhance recommendation input and make it dynamic

src/testclient/scripts/conf.env
conf.env의 알리바바 관련 내용에 CONTAINER_IMAGE_NAME/CONTAINER_IMAGE_TYPE들을 추가하였습니다.
=> Update conf.env for alibaba

scripts/runSpider.sh
- test 0.8.16
- adjust log level
- set ID_TRANSFORM_MODE=ON
=> Update option for spider container

src/api/rest/server/mcis/network.go
* Retrieve the last subnet info
* Set the last subnet ID from CSP
=> Set the last subnet info when including a subnet info in sites info

scripts/usecases/xonotic/startServer.sh
=> Reduce stderr stdout for Xonotic deploy script

scripts/init/init.sh, scripts/init/requirements.txt, scripts/misc/update-cloudinfo.sh
fix init.sh error due to versions.
related with https://github.com/psf/requests/releases/tag/v2.32.2
=> Set req python version to 3.8 for requests==2.32.2

scripts/usecases/xonotic/startServer.sh
- current bot is too powerful T.T
- now users can set its level.
=> Set Xonotic bot skill level

scripts/usecases/llm/installCudaDriver.sh
Script to setup
- Nvidia GPU driver and CUDA
=> Add installCudaDriver.sh

scripts/usecases/llm/installCudaDriver.sh
- ./cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb (3.1GB)
=> Add additional error handling installCudaDriver.sh

scripts/usecases/llm/deployOpenWebUI.sh
Fix OLLAMA_BASE_URLS not applying `;` separator
=> Update deployOpenWebUI.sh to fix OLLAMA_BASE_URLS issue

assets/k8sclusterinfo.yaml, conf/cloud_conf.yaml
assets/k8sclusterinfo.yaml과 cloud_conf.yaml에 k8scluster와 관련한 설정 초기값을 테스트 현황에 맞게 업데이트합니다.
=> Update k8sclusterinfo.yaml and cloud_conf.yaml for k8sclsuter

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcir/image.go, src/api/rest/server/mcir/spec.go
fix #1654
Provides API options in enum list (selectable).
=> Enhance API docs for spec and image registeration

README.md
README.md에 포함된 cluster/nodegroup 명칭 등을 k8scluster/k8snodegroup 등으로 변경합니다.
=> Update K8sCluster's test scripts in README.md

src/core/common/config.go, src/core/common/utility.go, src/core/mcis/k8scluster.go
K8s 클러스터 생성 및 업그레이드 시 k8sclusterinfo.yaml에 기재된 Available 버전 정보를 확인하고,
Error 메시지를 좀 더 상세하게 업데이트합니다.
=> Validate k8scluster version when creating and upgrading k8scluster

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/mcis/k8scluster.go, src/core/common/config.go, src/core/mcis/k8scluster.go
K8sCluster용 REST API의 description과 사용된 구조체의 example을 업데이트합니다.
사용자는 swagger UI를 통해 K8sCluster REST API 사용시 예시를 손쉽게 확인할 수 있습니다.
ref #1538
=> Update K8sCluster's REST API description and example

src/main.go
close #1674 
제 Local 환경에 찌꺼기가 남아있었습니다;;;;
=> Remove unused JWT configuration and environment variable handling

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml
* Update API docs manually because `Apply make swagger` workflow did not run
- The workflow doesn't seem to run when editing annotations.
=> Update API docs

src/api/rest/server/middlewares/custom-middleware/custom-middleware.go
=> Specify data type in ResponseBodyDump logging

src/core/common/utility.go
=> Fix GetRegion info bug

src/core/mcis/manageInfo.go
=> Fix subGroup removal bug in refine func

src/api/rest/server/mcir/spec.go, src/api/rest/server/server.go, src/core/mcir/common.go, src/core/mcir/spec.go, src/core/mcis/recommendation.go
- fetch all csp specs
- update spec info based on assets
- do not use key/value object for spec anymore for simplicity
=> Register all specs and update asset spec

src/core/mcis/provisioning.go
Hot fix.
- we don't use mcir.GetResource for spec anymore
=> Fix provisioning error

assets/k8sclusterinfo.yaml, conf/cloud_conf.yaml, src/testclient/scripts/13.k8scluster/get-available-k8scluster-version.sh, src/testclient/scripts/conf.env, src/testclient/scripts/sequentialFullTest/deploy-nginx-with-pvc-to-k8scluster.sh, src/testclient/scripts/sequentialFullTest/nginx-with-pvc.yaml, src/testclient/scripts/sequentialFullTest/undeploy-nginx-with-pvc-from-k8scluster.sh
k8scluster를 대상으로 service와 persistent volume(dynamic provisioning)의 동작 확인을 위한 테스트 스크립트를 추가하고 일부 k8scluster 관련 정보를 갱신하였습니다.
=> add testscripts for persistent volume and service in k8scluster

src/api/rest/server/mcis/k8scluster.go, src/api/rest/server/server.go, src/core/common/config.go, src/core/common/utility.go, src/testclient/scripts/13.k8scluster/check-nodegroups-on-k8s-creation.sh
- route to RestCheckNodeGroupsOnK8sCreation
- return K8sClusterNodeGroupsOnCreation(json)
- add testscript for CheckNodeGroupsOnK8sCreation
=> [k8scluster] update CheckNodeGroupsOnK8sCreation API

scripts/usecases/ceph/app.py
=> Fix Flask app is run in debug mode

.github/workflows/continuous-integration.yaml, .github/workflows/make-swagger.yaml, Dockerfile, README.md, go.mod, go.work, scripts/setcbdf.sh, scripts/setcbtb.sh
=> Use Golang v1.23.0

src/testclient/scripts/conf.env, src/testclient/scripts/sequentialFullTest/deploy-nginx-with-pvc-to-k8scluster.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-k8scluster.sh, src/testclient/scripts/sequentialFullTest/nginx-with-pvc.yaml, src/testclient/scripts/sequentialFullTest/undeploy-nginx-with-pvc-from-k8scluster.sh
k8scluster용 테스트 스크립트를 업데이트합니다.
=> [k8scluster] update testscripts

docker-compose.yaml
staging for cb-spider:0.9.2 bug fix
=> Staging v0.9.9

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/common/utility.go, src/api/rest/server/server.go, src/core/common/utility.go, src/core/model/common.go, src/core/model/config.go
=> Add get region list by provider

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/server.go, src/api/rest/server/util/netuil.go, src/core/common/netutil/netutil.go, src/core/model/vnet.go, src/core/resource/subnet.go, src/core/resource/vnet.go, src/examples/vnet-design/main.go
* Add features and improve the netutil pkg.
* Add the utility function, DesignVNet
* Add GetFirstNZones
* Include an example
I hope this PR will make vNet and subnet design a bit easier. There's an option to consider supernetting :-)
Let me show the API with just a screenshot and req/res bodies :-) 
Request body
```json
{
"targetPrivateNetwork": "10.0.0.0/8",
"supernettingEnabled": "true",
"cspRegions": [
{
"connectionName": "aws-ap-northeast-2",
"neededVNets": [
{
"subnetCount": 5,
"subnetSize": 260,
"zoneSelectionMethod": "firstTwoZones"
},
{
"subnetCount": 2,
"subnetSize": 100,
"zoneSelectionMethod": "firstTwoZones"
}
]
},
{
"connectionName": "gcp-asia-northeast2",
"neededVNets": [
{
"subnetCount": 3,
"subnetSize": 200,
"zoneSelectionMethod": "firstTwoZones"
}
]
},
{
"connectionName": …
```
=> Add a utility function to design vNets and subnets initially

src/core/common/label/label.go, src/core/resource/vnet.go
* Test with Spider v0.9.4
* Add missing ID and name
* Add missing label
* Add logging on RemoveLabel() in case of error return
테스트 및 디버깅한 API들이 아래와 같습니다. (Yellow marked)
=> Test and bugfix in vNet and subnet APIs

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/common/label/label.go, src/api/rest/server/infra/manageInfo.go, src/core/common/label/label.go, src/core/common/namespace.go, src/core/infra/manageInfo.go, src/core/infra/provisioning.go, src/core/model/common.go, src/core/model/label.go, src/core/resource/common.go, src/core/resource/datadisk.go, src/core/resource/k8scluster.go, src/core/resource/securitygroup.go, src/core/resource/sshkey.go, src/core/resource/subnet.go, src/core/resource/vnet.go
- 주요 리소스에 대해서, 시스템 제공 기본 label 추가 (`sys`. 프리픽스는 시스템이 생성한 것. ex: `sys.`namespace)
- label 오브젝트 삭제 처리 추가
- API 사용성 향상 등.
=> Enhance label feature

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/core/common/label/label.go, src/core/infra/provisioning.go, src/core/model/customimage.go, src/core/model/datadisk.go, src/core/model/k8scluster.go, src/core/model/mci.go, src/core/model/namespace.go, src/core/model/nlb.go, src/core/model/securitygroup.go, src/core/model/sshkey.go, src/core/model/subnet.go, src/core/model/vnet.go, src/core/resource/customimage.go, src/core/resource/datadisk.go, src/core/resource/k8scluster.go, src/core/resource/securitygroup.go, src/core/resource/sshkey.go, src/core/resource/subnet.go, src/core/resource/vnet.go
- Provide resourceType to objects
- Provide sys.connectionName label
=> Provide resourceType to objects

docker-compose.yaml
=> Staging v0.9.11

docker-compose.yaml
=> Use cb-mapui v0.9.5

src/main.go
Resolves https://github.com/cloud-barista/cb-tumblebug/issues/1845
=> Remove deprecated gRPC comments

src/api/rest/server/server.go
=> docs: remove misleading comment

init/init.py, src/core/resource/common.go, src/core/resource/image.go, src/core/resource/spec.go
will enhance #1861 further 
Now, init.sh will be completed within a manageable time. (less than 3 mins)
=> Expedite init by supporting bulk update assets

src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/resource/image.go, src/api/rest/server/server.go, src/core/resource/image.go, src/core/resource/spec.go
To support M-CMP release, temporal enabling.
=> Enable Get image API

src/core/infra/provisioning.go, src/core/model/mci.go
=> Code enhancement in vm provision request

src/core/resource/k8scluster.go
- K8s 생성시, spec 조회를 system default namespace 에서도 진행하도록 처리.
- MapUI 출력을 위해, location 리턴하도록 처리.
=> Provide location and enhance get spec for k8s cluster

init/init.py, init/requirements.txt
=> Enhance initialization script

docker-compose.yaml
cb-spider:
image: cloudbaristaorg/cb-spider:0.9.8
cb-mapui:
image: cloudbaristaorg/cb-mapui:0.9.10
=> Staging CB-TB v0.9.19

assets/cloudspec.csv, src/core/infra/manageInfo.go
ref #1873
for safety and performance.
=> Add Mutex to MCI related infos

src/core/common/utility.go
- this will prevent a possible panic error.
=> Enhance error handling for randomSleep

src/core/infra/provisioning.go, src/core/resource/common.go, src/testclient/scripts/sequentialFullTest/test-mci-dynamic-all-for-one.sh
=> Enhance provisioning speed and stability and Update test scripts

assets/cloudspec.csv
본 PR은 assets/cloudspec.csv 파일 내 Azure의 Spec들을 K8s 지원 가능 항목으로 설정합니다.
=> [chore] update assets/cloudspec for k8s

assets/cloudimage.csv
본 PR은 nhncloud의 cloudimage 정보를 업데이트합니다.
=> CHORE: [k8scluster] update cloudimage.csv for nhncloud

docker-compose.yaml, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/resource/subnet.go
* Update docker-compose.yaml
* Minor update the `option` description of API, `DELETE /ns/{nsId}/resources/vNet/{vNetId}/subnet/{subnetId}`
Close #1923
=> Staging v0.10.1

src/api/rest/server/resource/k8scluster.go, src/api/rest/server/server.go
본 PR은 echo framework에 미반영된 API path를 반영합니다.
=> FIX: [k8scluster] API path

docker-compose.yaml
=> Staging v0.10.4

README.md
* Update screenshots to align with the changed directory tree for initialization scripts
=> Fix incorrect screenshots in the README.md

.github/workflows/continuous-delivery.yaml, docker-compose.yaml
- Support linux/arm64 image
- Staging 0.10.5
=> Staging 0.10.5 to support linux/arm64 image

docker-compose.yaml, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/core/infra/provisioning.go, src/core/model/mci.go
- provide results for mci post command in the mci object.
=> Enhance output of mci post command

docker-compose.yaml, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/core/infra/provisioning.go, src/core/model/image.go, src/core/model/mci.go, src/core/model/spec.go, src/core/resource/image.go, src/core/resource/spec.go, src/testclient/scripts/7.spec/range-filter-specs.sh
- Code update for image, spec structures to apply the changes in cb-sp v0.10.3
Note that image, spec features need to be updated further.
=> Apply cb-sp v0.10.3

src/core/infra/provisioning.go, src/core/model/k8scluster.go, src/core/resource/k8scluster.go, src/testclient/scripts/sequentialFullTest/deploy-nginx-with-pvc-to-k8scluster.sh, src/testclient/scripts/sequentialFullTest/deploy-weavescope-to-k8scluster.sh, src/testclient/scripts/sequentialFullTest/undeploy-nginx-with-pvc-from-k8scluster.sh
본 PR은 k8scluster 정보 구조체의 내용을 CB-TB에서 관리하는 정보값들로 채워지도록 변경합니다. 
fix #1842
=> feat: [k8scluster] enhance k8scluster info struct

docker-compose.yaml
=> Staging cb-tumblebug 0.10.7

docker-compose.yaml
- for Kubernetes provisioning support
- for dependency update (traefik v3.4, cb-mapui 0.10.6)
No breaking change! ;)
=> Staging v0.10.8

docker-compose.yaml
- Use cb-spider:0.10.8 (bug fixed version for empty Alibaba sshkey)
- Use cb-mapui:0.10.7 (enhanced UI)
=> Staging cb-tumblebug v0.10.9

init/init.sh, src/core/model/spec.go, src/core/resource/common.go, src/core/resource/image.go, src/core/resource/spec.go
=> Reduce memory usage for fetching image spec price

docker-compose.yaml, init/init.py, src/api/rest/docs/docs.go, src/api/rest/docs/swagger.json, src/api/rest/docs/swagger.yaml, src/api/rest/server/common/config.go, src/api/rest/server/resource/spec.go, src/api/rest/server/server.go, src/core/common/client/client.go, src/core/model/spec.go, src/core/resource/common.go, src/core/resource/image.go, src/core/resource/spec.go
- [Enhance api request log](https://github.com/cloud-barista/cb-tumblebug/commit/22753833bf714996d1c84a121b25c1abc44a4254) 
- [Enhance spec fetching in init](https://github.com/cloud-barista/cb-tumblebug/commit/82fef9d9eb25f813f229d8c8a231e3b557c8e5d5)
=> Enhance api request log and spec handling

src/core/infra/manageInfo.go, src/core/model/mci.go, src/core/model/securitygroup.go, src/core/resource/common.go, src/core/resource/securitygroup.go, src/interface/rest/docs/docs.go, src/interface/rest/docs/swagger.json, src/interface/rest/docs/swagger.yaml, src/interface/rest/server/infra/manageInfo.go, src/interface/rest/server/resource/firewallrule.go, src/interface/rest/server/resource/securitygroup.go, src/interface/rest/server/server.go
Core Model Redesign:
- Add TbFirewallRuleReq struct with Ports field supporting comma-separated multiple ports/ranges
- Refactor TbFirewallRuleInfo to use single Port field for individual rule representation
- Add comprehensive response models: TbSecurityGroupUpdateResponse, TbRestWrapperSecurityGroupUpdateResponse, TbUpdateSummary
- Add MciAssociatedResourceList struct for complete MCI-resource relationship tracking
Backend Logic Enhancement:
- Implement ConvertFirewallRuleRequestObjToInfoObjs for flexible multi-port request conversion
- Major UpdateFirewallRules refactor with CSP-aware conditional processing (sequential for NCP, parallel for others)
- Add UpdateMultipleFirewallRules with goroutine-based parallel processing and comprehensive error handling
- Enhance diffFirewallRules …
=> feat: comprehensive security group firewall rules management system

src/interface/mcp/tb-mcp.py
Major Features Added:
• Smart namespace management with automatic validation and creation • Intelligent image selection with metadata analysis (no hardcoded patterns) • Spec-first workflow for optimal CSP/region selection • Advanced MCI creation functions with comprehensive error handling
New MCP Tools:
• check_and_prepare_namespace(): Intelligent namespace guidance • validate_namespace(): Namespace existence validation • create_namespace_with_validation(): Safe namespace creation • select_best_image(): Smart image selection with detailed reasoning • select_best_image_with_context(): Context-aware image selection for specific use cases • create_mci_with_namespace_management(): MCI creation with auto namespace handling • create_mci_with_spec_first(): Advanced spec-first workflow …
=> optimized TB-MCP server with intelligent NS management and optimized API policies

src/core/infra/remoteCommand.go, src/core/resource/sshkey.go
Note that Tencent Cloud returns different format for SSHKey.
This PR improve it's handling.
=> Enhance sshkey and remote command logic

src/interface/mcp/tb-mcp.py
- install_mon_agent is not enabled option, and cannot use it especially in automation.
=> Remove MCI with monitoring option from MCP

src/core/infra/remoteCommand.go, src/core/model/mci.go, src/interface/rest/docs/docs.go, src/interface/rest/docs/swagger.json, src/interface/rest/docs/swagger.yaml, src/interface/rest/server/infra/remoteCommand.go
- change error return to string return for API clients
=> Fix remote commend error return issue

docker-compose.yaml, src/core/common/client/client.go, src/core/model/spec.go, src/core/resource/common.go, src/core/resource/spec.go, src/interface/rest/docs/docs.go, src/interface/rest/docs/swagger.json, src/interface/rest/docs/swagger.yaml, src/interface/rest/server/resource/spec.go, src/interface/rest/server/server.go
Feat Update SpecList By Availability for Alibaba
Currently, to use this feature, you need to be call by API directly.
Sub systems will be updated.
- cb-spider:0.11.5
- cb-mapui:0.11.12
=> Feat Update SpecList By Availability for Alibaba

src/core/common/client/client.go, src/core/resource/image.go, src/core/resource/spec.go, src/interface/rest/docs/docs.go, src/interface/rest/docs/swagger.json, src/interface/rest/docs/swagger.yaml, src/interface/rest/server/resource/image.go
- related with issue https://github.com/cloud-barista/cm-beetle/issues/194
But, I will double check :)
=> Apply url.QueryUnescape for get image

src/core/infra/benchmark.go, src/core/infra/loadbalance.go, src/core/infra/orchestration.go, src/core/infra/provisioning.go, src/core/infra/remoteCommand.go, src/core/model/mci.go, src/interface/rest/docs/docs.go, src/interface/rest/docs/swagger.json, src/interface/rest/docs/swagger.yaml, src/interface/rest/server/infra/remoteCommand.go, src/interface/rest/server/server.go
=> Support remote command status and history

src/core/resource/k8scluster.go, src/interface/rest/server/server.go
Control timeout and timing for k8s related operations.
=> Enhance k8s management stability

assets/k8sclusterinfo.yaml, src/core/common/utility.go, src/core/infra/manageInfo.go, src/core/infra/utility.go
- Update available alibaba kubernetes cluster versions.
- minor enhance for duplicated error checking.
=> Update alibaba kubernetes cluster versions

src/core/infra/manageInfo.go, src/core/infra/provisioning.go
Note that, It is a special treatment for Alibaba VMs provisioning.
=> Fix mci provisioning all failed return pending situation

docker-compose.yaml
- CB-Spider [v0.11.10](https://github.com/cloud-barista/cb-spider/releases/tag/v0.11.10) 
- CB-MapUI [v0.11.15](https://github.com/cloud-barista/cb-mapui/releases/tag/v0.11.15)
=> Staging v0.11.10

docs/migration_guide_0.11.8_to_0.11.13.md
Add docs/migration_guide_0.11.8_to_0.11.13+
=> Add docs/migration_guide_0.11.8_to_0.11.13+

src/core/resource/spec.go
- To fix https://github.com/cloud-barista/cm-beetle/issues/208
=> Apply simple rule for checking Azure Gen2 Spec
