cloud-barista/cb-tumblebug

- mcism_master/mcism_master.go
For this moment, it is disabled for development convenience.
fix issue #3
> Add HTTP BasicAuth

- mcism_server/mcism_mcis.go
- mcism_server/mcism_server.go
Fix #9 
Add individual VM control functionalities.
- POST("/:nsId/mcis/:mcisId/vm", restPostMcisVm)
- GET("/:nsId/mcis/:mcisId/vm/:vmId", restGetMcisVm)
- DELETE("/:nsId/mcis/:mcisId/vm/:vmId", restDelMcisVm)
with some minor error fixs.
> Add individual VM control functionalities

- mcism_server/mcir_image.go
- mcism_server/mcir_network.go
- mcism_server/mcir_publicip.go
- mcism_server/mcir_securitygroup.go
- mcism_server/mcir_sshkey.go
- mcism_server/mcir_vnic.go
- mcism_server/mcism_mcis.go
- mcism_server/mcism_server.go
How to run CB-Tumblebug:
1. Set some envvars.
```Shell
export CBSTORE_ROOT=~/go/src/github.com/cloud-barista/cb-store
export CBLOG_ROOT=~/go/src/github.com/cloud-barista/cb-store
export MCISM_SERVER=~/go/src/github.com/cloud-barista/cb-tumblebug/mcism_server
export SPIDER_URL=https://testapi.io/api/jihoon-seo
```
2. Run `mcism_server`
```
./mcism_server
```
---
FYI: https://testapi.io/api/jihoon-seo/* returns some mock API results for MCIRs and VM.
- VM and VM status
1. https://testapi.io/api/jihoon-seo/vm
2. https://testapi.io/api/jihoon-seo/vmstatus
- MCIRs
3. https://testapi.io/api/jihoon-seo/keypair
4. https://testapi.io/api/jihoon-seo/securitygroup
5. https://testapi.io/api/jihoon-seo/vnic
6. https://testapi.io/api/jihoon-seo/publicip
7. https://testapi.io/api/jihoon-seo/vmimage
8. …
> Modify to read envvar SPIDER_URL

- setup.env
Add file for setup environment config
setup.env includes following environment variables. 
```
export CBSTORE_ROOT=~/go/src/github.com/cloud-barista/cb-store
export CBLOG_ROOT=~/go/src/github.com/cloud-barista/cb-store
export MCISM_SERVER=~/go/src/github.com/cloud-barista/cb-tumblebug/mcism_server
export SPIDER_URL=https://testapi.io/api/jihoon-seo
```
> Add file for setup environment config

- mcism_server/mcism_mcis.go
- mcism_server/mcism_server.go
Enhance MCIS and VM lifecycle  control 
Here I introduce MCIS status which provides an overview of all VMs in a MCIS.
These definitions show status types for a VM.
const statusRunning string = "Running"
const statusSuspended string = "Suspended"
const statusFailed string = "Failed"
const statusTerminated string = "Terminated"
const statusCreating string = "Creating"
const statusSuspending string = "Suspending"
const statusResuming string = "Resuming"
const statusRebooting string = "Rebooting"
const statusTerminating string = "Terminating"
If there is any "Failed" VM, the status of the including MCIS is "Failed"
else if all of VMs have the same status, the status of MCIS is the same also.
In case statuses of VMs are different from each other, the status of MCIS will have the status which …
> Enhance MCIS and VM lifecycle  control and etc

- conf/setup.env
- src/apiserver/apiserver.go
- src/mcir/common.go
- src/mcir/image.go
- src/mcir/network.go
- src/mcir/publicip.go
- src/mcir/securitygroup.go
- src/mcir/spec.go
- src/mcir/sshkey.go
- src/mcir/subnet.go
- src/mcir/vnic.go
- test/shooter-sh/insert-all-azure-regions.sh
- test/shooter-sh/insert-all-gcp-zones-region.sh
`/spider` 대응:
`conf/setup.env` 에
`export SPIDER_URL=http://localhost:1024/spider`
(Spider URL 지정이 환경 변수로 되어 있으니
docker, docker-compose 에서 컨테이너 띄울 때에도
환경변수를 바꾸면 돼서 편하고 좋네요)
---
`/tumblebug` 대응:
`src/apiserver/apiserver.go` 에
`g := e.Group("/tumblebug/ns", common.NsValidation())`
---
[TODO]
- test (Shooter) 스크립트에 `/spider`, `/tumblebug` 변경 반영 안 한 파일들이 많음
- 컨테이너 이미지 새로 만들고, Docker Hub 에 올리기
- CB-Deployer 의 docker-compose.yaml 업데이트
- API-GW conf 업데이트
- 등등
---
Related:
- Suggestion: Add `/tumblebug/` prefix for REST APIs #96 
- Spider 의 API 변경에 대한 대응 #97
> Apply changes for API prefix addition of Spider and TB

- src/apiserver/apiserver.go
- src/mcir/common.go
- src/mcir/spec.go
Usage of REST API:
[Request]
- GET `{{tb_ip}}:{{tb_port}}/tumblebug/lookupSpec/r5.4xlarge`
```JSON
{
"connectionName": "{{connection_name}}"	
}
```
---
[Response]
```JSON
{
"Region": "us-east-1",
"Name": "r5.4xlarge",
"VCpu": {
"Count": "16",
"Clock": "3.1"
},
"Mem": "131072",
"Gpu": [],
"KeyValueList": [
{
"Key": "SupportedRootDeviceTypes",
"Value": "[ebs]"
},
{
"Key": "SupportedUsageClasses",
"Value": "[on-demand spot]"
},
{
"Key": "VCpuInfo",
"Value": "map[DefaultCores:8 DefaultThreadsPerCore:2 DefaultVCpus:16 ValidCores:[2 4 6 8] ValidThreadsPerCore:[1 2]]"
},
{
"Key": "InstanceStorageSupported",
"Value": "false"
},
{
"Key": "CurrentGeneration",
"Value": "true"
},
{
"Key": "DedicatedHostsSupported",
"Value": "true"
},
{
"Key": "FreeTierEligible",
"Value": "false"
},
{
"Key": …
```
> Add functions `lookupSpec` and `RestLookupSpec`

- src/mcir/spec.go
[API changelog]
1. ~~JSON key 중
기존에는 `name` 이었던 것이
`cspSpecName` 으로 변경되었습니다.~~
2. CB-Tumblebug metadata store 에 Spec 을 등록할 때
1) 기존에는 `name`, `connectionName`, 그리고 spec 의 상세내용을 적어서 POST 하면
Spider 나 CSP 에 lookup 하지 않고 즉시 CB-Tumblebug metadata store 에 저장하는 방식이었습니다.
```JSON
{
"name": "t2.micro",
"connectionName": "{{connection_name}}",
"os_type": "",
"num_vCPU": "",
"num_core": "",
"mem_GiB": "",
"storage_GiB": "",
"description": "",
"cost_per_hour": "",
"num_storage": "",
"max_num_storage": "",
"max_total_storage_TiB": "",
"net_bw_Gbps": "",
"ebs_bw_Mbps": "",
"gpu_model": "",
"num_gpu": "",
"gpumem_GiB": "",
"gpu_p2p": ""
}
```
이것이 변경되어서
2) `cspSpecName` 과 `connectionName` 만 적어서 POST 하면
Spider 에 lookup 하고 그 결과를 이용하여 CB-Tumblebug metadata store 에 저장하는 방식으로 변경되었습니다.
```JSON
{
"cspSpecName": …
```
> Implement function `registerSpecWithCspSpecName`

- src/apiserver/apiserver.go
- src/mcir/common.go
- src/mcir/sshkey.go
- We cannot use these wildcard methods.
- `g.DELETE("/:nsId/resources/:resourceType/:resourceId", mcir.RestDelResource)`
- `g.DELETE("/:nsId/resources/:resourceType", mcir.RestDelAllResources)`
- Reason: https://github.com/labstack/echo/issues/382
> Update some commented codes

- src/apiserver/apiserver.go
- src/mcir/common.go
- src/mcir/spec.go
- test/2020-04-29/5.spec/fetch-specs.sh
- test/2020-04-29/5.spec/lookupSpec.sh
- test/2020-04-29/5.spec/lookupSpecList.sh
- test/2020-04-29/5.spec/spider-get-spec.sh
- test/2020-04-29/5.spec/spider-get-speclist.sh
- test/shooter-sh-2019/azure-locations-list.txt
[사용법]
[Request]
`test/2020-04-29/5.spec/fetch-specs.sh`
```Shell
curl -sX POST http://localhost:1323/tumblebug/ns/$NS_ID/resources/fetchSpecs
```
---
[결과]
GET `{{tb_ip}}:{{tb_port}}/tumblebug/ns/{{ns_id}}/resources/spec`
```JSON
{
"spec": [
{
"id": "aws-us-east-1-config-a1.large",
"connectionName": "aws-us-east-1-config",
"cspSpecName": "a1.large",
"name": "aws-us-east-1-config-a1.large",
"os_type": "",
"num_vCPU": "2",
"num_core": "",
"mem_GiB": "4",
"mem_MiB": "4096",
"storage_GiB": "",
"description": "",
"cost_per_hour": "",
"num_storage": "",
"max_num_storage": "",
"max_total_storage_TiB": "",
"net_bw_Gbps": "",
"ebs_bw_Mbps": "",
"gpu_model": "",
"num_gpu": "",
"gpumem_GiB": "",
"gpu_p2p": ""
},
{
"id": "aws-us-east-1-config-a1.medium",
"connectionName": "aws-us-east-1-config", …
```
> Add fetchSpecs function and API

- test/2020-04-29/0.settingSpider/delete-test.sh
- test/2020-04-29/0.settingSpider/get-test.sh
- test/2020-04-29/0.settingSpider/insert-test.sh
- test/2020-04-29/0.settingSpider/list-test.sh
- test/2020-04-29/conf.env
- test/2020-04-29/prettify-json.sh
Automate test script to set up connection-conf
0.settingSpider 디렉터리에 delete-test.sh  get-test.sh  insert-test.sh  list-test.sh 가 추가됨
insert-test.sh 1 은 ../conf.env 에 "1"에 해당하는 CSP에 대한 드라이버, 크리덴셜, 리젼, 커넥션컨피그를 등록함.
conf.env 에는 각 CSP에 해당하는 사용자의 크리덴셜 정보를 입력해야 사용 가능함.
> Automate test script to set up connection-conf

- src/mcis/control.go
- test/2020-04-29/2.securityGroup/create-securityGroup.sh
Enable measure RTT to all VMs in MCIS.
This commit works with the latest CB-Spider commit. (commit da3e11a258828f33cfe75a75197aac6b8feda7b8)
> Enable measure RTT to all VMs in MCIS

- src/mcis/control.go
- test/2020-04-29/0.settingSpider/register-cloud.sh
- test/2020-04-29/fullTest/cleanAll-mcis-mcir-cloud.sh
- test/2020-04-29/fullTest/test-cloud.sh
- test/2020-04-29/fullTest/test-mcir-ns-cloud.sh
- test/2020-04-29/fullTest/test-ns-cloud.sh
- test/2020-04-29/fullTest/testAll-mcis-mcir-ns-cloud.sh
Parallel mcis control and enhance test script
1. MCIS 내의 VM 제어 처리 병렬화
- CB-Spider 의 특정 CSP는 VM 제어시 동기 콜을 사용하고 있어서, CB-TB가 MCIS를 생성하는데 시간이 많이 소요됨. CB-TB에서 CB-Spider로의 VM 제어 콜을 병렬로 보내도록 수정.
2. 테스트 스크립트가 보완됨
- 사용자 명칭만 다르게하면 CSP 쪽 자원이 겹치지 않도록 처리 (특히, azure의 경우 Resource Group 명칭을 동일하게 사용하고 있었음). 
- 여러 CSP에 대한 동시 테스트 가능
- 시퀀셜 테스트 스크립트를 단계 형태로 추가
- testAll-mcis-mcir-ns-cloud.sh  
- test-mcir-ns-cloud.sh
- test-ns-cloud.sh
- test-cloud.sh                  
- 모든 테슽트 코드 삭제
- cleanAll-mcis-mcir-cloud.sh  (다만 ns는 CSP간 시험에서 공유할 수 있으므로, 삭제하지 않음)
- 동일 테스트 중복 실행을 막기 위해서, 커맨드 히스토리를 파일로 남김
- executionStatus  (커맨드 히스토리 자동 기록)           
3. AWS, Azure 까지 테스트
- testAll-mcis-mcir-ns-cloud.sh
> Parallel mcis control and enhance test script

- src/common/namespace.go
- src/mcis/control.go
- src/mcism.go
기존의 MCIS 및 VM 상태 오류를 보정하는 업데이트.
관련 이슈: spider에서 제공하는 native한 vm의 status는 csp 마다 값과 처리 방식이 다름. MCIS 상태에 오류 발생.
이를 보정하기 위해서, 
- CB-TB는  "targetStatus", "targetAction" 필드를 도입함.
- 사용자에게  MCIS 제어 요청을 받으면, "targetStatus", "targetAction" 을 DB에 저장하고
- 향후, MCIS 상태 조회시, 이를 고려하여 값을 보정함.
상태별로 불가한 제어 명령을 지정 및 기능을 추가하였음 (func checkAllowedTransition)
- Transitional statuses (suspending, resuming, terminating, ...): 상태 전이 완료 전까지 모든 제어 명령 허용하지 않음
- Terminated : 모든 제어 명령 허용하지 않음
- Suspended: Resume, Terminate 만 허용
> Stateless management of MCIS lifecycle

- src/mcis/control.go
- src/resource/cloudlocation.csv
Enhance MCIS lifecycle status
1. 클라우드타입별 지리적 위치 파일이 추가됨. 
- 데이터는 다양한 래퍼런스를 통해 @seokho-son 이 직접 생성
- aws, azure, gcp, alibaba, cloudit 등에 대한 현재 리전 정보를 포함
2. 클라우드의 위치 정보를 기반으로, MCIS 생성시 VM에 location (위도,경도) 정보를 추가 제공
3. MCIS 라이프사이클에 총VM수와 제어중인 VM수에 대한 정보 추가
> Enhance MCIS lifecycle status

- src/common/utility.go
- src/mcir/common.go
- src/mcir/image.go
- src/mcir/obsolete/publicip.go
- src/mcir/obsolete/subnet.go
- src/mcir/obsolete/vnic.go
- src/mcir/securitygroup.go
- src/mcir/spec.go
- src/mcir/sshkey.go
- src/mcir/vnet.go
- src/mcis/control.go
- src/mcis/utility.go
This PR
- Adds MySQL handling logic for `func registerSpecWithCspSpecName`
(cf. #162: for `func registerSpecWithInfo`)
- Updates env var `SPIDER_URL` handling logic
- Before: Package-wide variable `SPIDER_URL` is declared in each package,
and initialized in the `func init` of each package (`common`, `mcir`, `mcis`).
- After: Exported variable `SPIDER_URL` is declared in `common/utility.go`,
and initialized in the `func main` of `mcism.go`.
@seokho-son 
`cblog` 변수와 `store` 변수에 대해서도 위의 `SPIDER_URL` 변수와 동일한 이슈가 있습니다.
`cblog` 변수와 `store` 변수가
각 패키지 안에서 declare 되고
각 패키지 안에서 init 되는데요
이를 일원화 할 수도 있습니다.
다만 현재는 `cblog.Error(err)` 이렇게 쓰면 되는데
일원화 하면 `common.CBLog.Error(err)` 와 같이
사용할 때마다 앞에 `common.` 을 붙여야 할 것입니다.
> Update env var SPIDER_URL handling logic

- src/api/grpc/protobuf/Makefile
- src/api/grpc/protobuf/cbtumblebug.pb.go
- src/api/grpc/protobuf/cbtumblebug.proto
- src/api/grpc/server/server.go
- src/api/grpc/test-client/test.go
- src/common/namespace.go
- src/mcir/common.go
- src/mcis/control.go
- Renamed & Exported functions
- `getNsList` -> `ListNsId(nsId string, resourceType string) []string`
- `checkNs` -> `CheckNs(Id string) (bool, error)`
- `delNs` -> `DelNs(Id string) error`
- New functions
- `GetNs(id string) (NsInfo, error)`
- `ListNs() ([]NsInfo, error)`
- `DelAllNs() error`
- Updated REST-handling functions (to separate REST and core logic) (for gRPC integration)
- `RestGetNs(c echo.Context) error`
- `RestGetAllNs(c echo.Context) error`
- `RestDelAllNs(c echo.Context) error`
- Renamed & Exported structs
- `nsInfo` -> `NsInfo`
---
- New gRPC functions
- `rpc CheckNs (NsId) returns (BooleanResponse) {}`
- `rpc CreateNs (NsReq) returns (NsInfo) {}`
- `rpc DelAllNs (google.protobuf.Empty) returns (google.protobuf.Empty) {}`
- `rpc DelNs (NsId) returns …
> Add gRPC functions for NS mgmt

- src/api/rest/server/mcis/control.go
- src/cli/cmd/root.go
- src/cli/config.json
- src/mcis/control.go
- test/obsolete/aws-tester-sh/vm/start_all-test.sh
- test/obsolete/azure-tester-sh/vm/start_all-test.sh
- test/obsolete/full_test.sh
- test/obsolete/gcp-tester-sh/vm/start_all-test.sh
- test/obsolete/shooter-sh-2019/vm/start_all-test.sh
- test/official/6.mcis/create-mcis.sh
- test/official/README.md
- VM REST API JSON field names are changed. (Ref: @jazmandorf @dev4unet)
- Issue #180: Suggestion: Organize JSON field name
- Issue #187: Info: JSON input/output of `CreateMcis()` will be changed
- Integrate struct `TbVmReq` into `TbVmInfo`
- Issue #177: Suggestion: Integrate struct pair `xxxReq` and `xxxInfo`
- Update `RestPostMcisVm()`
- Related info: #186 Info: Go struct / JSON field name match table
[Logic of `RestPostMcisVm()`]
[Before this PR](https://github.com/cloud-barista/cb-tumblebug/blob/58e51127acfe3fe324dfb0204311c8d537366583/src/api/rest/server/mcis/control.go#L581):
1. POST `{tb_host}:{tb_port}/tumblebug/ns/:nsId/mcis/:mcisId/vm` (in [src/api/rest/server/server.go](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/api/rest/server/server.go))
2. `func …
> Integrate struct TbVmReq into TbVmInfo, and update RestPostMcisVm

- src/api/rest/server/mcis/control.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
BTW,
in PR #199 by @seokho-son,
`"type": "object"` field is added for some structs.
But in this PR,
`"type": "object"` field will be removed from those structs.
I guess that this phenomenon may occur from using different version of `swag`.
- `swag` version in my dev env:
```
❯ swag -v
swag version v1.6.7
```
---
> Update Swagger annotations for MCIS/VM REST functions

- src/api/rest/server/mcis/control.go
- src/mcis/control.go
- RestPostMcis() 함수에서 core logic 분리
- CorePostMcis() 추가
- RestGetMcis() 함수에서 core logic 분리
- CoreGetMcisAction() 추가
- CoreGetMcisStatus() 추가 : VM 정보가 없을경우 nil 을 리턴하는 것으로 변경
- CoreGetMcisInfo() 추가
> Seperate core logic from RestPostMcis and RestGetMcis

- src/mcir/common.go
- src/mcir/obsolete/publicip.go
- src/mcir/obsolete/vnic.go
- test/official/5.sshKey/force-delete-sshKey.sh
[Implementation details]
[Pseudo-code of `func DelResource(nsId string, resourceType string, resourceId string, forceFlag string) error {`]
```
func DelResource(nsId string, resourceType string, resourceId string, forceFlag string) error {
call Spider's DELETE REST API;
switch {
case forceFlag == "true":
call Spider's DELETE REST API again with `?force=true` query param;
CBStore.Delete(key)
case res.StatusCode >= 400 || res.StatusCode < 200:
return err
default: // forceFlag != "true" && (200 <= res.StatusCode <= 399)
CBStore.Delete(key)
}
}
```
You can see that
when `?force=true` query param is set in REST API call to Tumblebug,
Tumblebug calls Spider's DELETE REST API 2 times.
1. Tumblebug calls Spider's DELETE REST API without `?force=true` query param.
2. Tumblebug calls Spider's …
> Update to support Spider's force delete feature

- test/official/README.md
- test/official/credentials.conf.tmp
Change way to handle credentials.conf
실제 역할을 하는 credentials.conf 를 소스트리에서 삭제하고,
해당 파일은 credentials.conf.tmp 로 변경함. (이를 통해 credentials.conf 는 gitignore 적용.)
사용자가 credentials.conf.tmp 를 활용하여 credentials.conf를 생성하도록 가이드함.
> Change way to handle credentials.conf

- test/official/1.configureSpider/get-cloud.sh
- test/official/1.configureSpider/unregister-cloud.sh
- test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh
Tested with:
- `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `test/official/sequentialFullTest/1.configureSpider/get-cloud.sh aws 1 jhseo`
- `test/official/sequentialFullTest/1.configureSpider/unregister-cloud.sh aws 1 jhseo`
> BugFix for Add 'credentials.conf' existence check logic in 'test/official/*/*.sh'

- .gitignore
- conf/grpc_conf.yaml
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- core logic 에 spider api 를 이용한 연결 추가
- setup.env 에서 SPIDER_CALL_METHOD=REST 로 설정하면 REST방식으로 spider 와 통신
- setup.env 에서 SPIDER_CALL_METHOD=GRPC 로 설정하면 GRPC방식으로 spider 와 통신
> Add spider grpc call to core logic

- Dockerfile
- conf/grpc_conf.yaml
- conf/setup.env
- src/core/common/common.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/obsolete/publicip.go
- src/core/mcir/obsolete/subnet.go
- src/core/mcir/obsolete/vnic.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/core/mcis/utility.go
- src/main.go
- test/obsolete/tester-go/cloud-info-mgmt.go
- test/obsolete/tester-go/tester.go
Since there exist 2 methods (REST / gRPC) for calling CB-Spider,
`SPIDER_REST_URL` seems clear than `SPIDER_URL`.
---
Note: You can set CB-Spider's gRPC endpoint URL at `cb-tumblebug/conf/grpc_conf.yaml`.
```YAML
spidersrv:
addr: 127.0.0.1:50251
```
---
And..
- `DRAGONFLY_URL` → `DRAGONFLY_REST_URL`
- Change TB gRPC listen address from `127.0.0.1:50252` to `:50252` (Same issue with https://github.com/cloud-barista/cb-spider/pull/278)
- Add some lines in `Dockerfile`
- `ENV CBTUMBLEBUG_ROOT /app`
- `ENV SPIDER_CALL_METHOD REST`
- `ENV DRAGONFLY_REST_URL http://cb-dragonfly:9090/dragonfly`
- `EXPOSE 50252`
> Change the env var name SPIDER_URL to SPIDER_REST_URL

- src/api/grpc/request/mcisapi.go
- KeyValue을 잘못 사용하여 CBSTORE_ROOT 의 환경변수를 필요하게 된 현상 수정
> Fix bug : wrong import for KeyValue struct

- test/official/README.md
- test/official/conf.env
AWS의 3개의 리전을 사용하는 MCIS 를 생성할 수 있도록 기본 conf.env 를 수정.
여러 클라우드 및 리전에 걸친 MCIS 테스트를 위한 가이드 일부 수정.
> Modify basic conf for testing

- src/core/common/namespace.go
- src/core/common/utility.go
Resolves #264 
---
- Add `func GetChildIdList(key string) []string` in `src/core/common/utility.go`
- Add NS emptiness check logic in `DelNs()`
---
`❯ ./delete-ns.sh`
```JSON
{
"message" : "Cannot delete NS NS-01, which is not empty. There exists at least one MCIS or one of resources. \n len(mcisList): 0 \n len(imageList): 7427 \n len(vNetList): 0 \n len(securityGroupList): 0 \n len(specList): 331 \n len(sshKeyList): 0"
}
```
> Add NS emptiness check logic in DelNs()

- src/api/grpc/server/common/namespace.go
- src/api/grpc/server/mcir/common.go
- src/api/grpc/server/mcis/utility.go
- src/api/rest/server/common/namespace.go
- src/api/rest/server/mcir/common.go
- src/api/rest/server/mcis/utility.go
- src/core/common/namespace.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/core/mcis/utility.go
- test/official/conf.env
Related: https://github.com/cloud-barista/cb-tumblebug/pull/270#issuecomment-703776867
[Namespace part]
- CreateNs()
- GetNs()
- DelNs()
[MCIR part]
- DelResource()
- GetResource()
- All resource-creating functions
[MCIS part]
- Ref: [Call chains of functions in src core mcis *.go](https://github.com/cloud-barista/cb-tumblebug/wiki/Call-chains-of-functions-in-src-core-mcis-*.go)
- ([모든 Wrapper functions] + [Wrapper function 이 없지만 REST / gRPC function 과 직접 연결되는 함수들] 에 적용했음)
- ===
- [core/mcis/control.go](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/core/mcis/control.go)
- Core*()
- DelMcis()
- DelMcisVm()
- InstallAgentToMcis()
- [core/mcis/monitor.go](https://github.com/cloud-barista/cb-tumblebug/blob/master/src/core/mcis/monitor.go)
- GetMonitoringData()
- …
> Update core functions to replace uppercases and underscores

- assets/scripts/setcbdf.sh
- test/official/8.mcis/create-mcis.sh
- test/official/sequentialFullTest/deploy-dragonfly-docker.sh
- test/official/sequentialFullTest/deploy-spider-docker.sh
- test/official/sequentialFullTest/deploy-tumblebug.sh
Add a CB-TB script for automatic dragonfly deployment.
- Test output
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ 
./deploy-dragonfly-docker.sh aws 1 df1
[Test for AWS]
{
"result_array" : [
{
"result" : "go build -o operator\ncb-operator is ready. Access to it with ssh 3.84.229.190 CB_OPERATOR_MODE: DockerCompose\n\n[Get info for Cloud-Barista runtimes]\n\n[Config path] /home/ubuntu/go/src/github.com/cloud-barista/cb-operator/docker-compose-mode-files/docker-compose-df-only.yaml\n\n\n[v]Status of Cloud-Barista runtimes\nName   Command   State   Ports\n------------------------------\n\n[v]Status of …
```
> Add script for automatic dragonfly deployment

- go.mod
- src/core/mcis/monitor.go
Renew client code for latest CB-DF API
최신 CB-Dragonfly와의 연동을 위해, 내부 소스코드 수정
[TB를 통항 DF 호스팅용 MCIS-VM 생성]
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./testAll-mcis-mcir-ns-cloud.sh aws 1 shson
[Test for AWS]
[Single excution for a CSP region]
[Test for AWS]
{
"DriverName" : "aws-driver01",
"ProviderName" : "AWS",
"DriverLibFileName" : "aws-driver-v1.0.so"
}
...
...
...
[Test for AWS]
{
"status" : {
"id" …
```
> Renew client code for latest CB-DF API

- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/1.configureSpider/unregister-cloud.sh
- test/official/8.mcis/create-mcis-no-agent.sh
- test/official/sequentialFullTest/gen-mcis-for-df.sh
resolves : #274
```
type TbMcisReq struct {
Name           string    `json:"name"`
Vm             []TbVmReq `json:"vm"`
Placement_algo string    `json:"placement_algo"`
// AgentEnabled Option for CB-Dragonfly agent installation ([yes/no] default:yes)
//
// in: body
// required: false
AgentEnabled   string    `json:"agentEnabled"` // yes or no
Description    string    `json:"description"`
}
```
> Add default agent install for MCIS

- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/8.mcis/create-mcis-no-agent.sh
- test/official/8.mcis/create-mcis.sh
- test/official/sequentialFullTest/deploy-dragonfly-docker.sh
(related issue: #274)
(related PR: #283)
The PR #283 provide a feature for installing monitoring agent of CB-Dragonfly to all VMs in a MCIS.
However, it was applicable for an initial creation of MCIS.
CB-Tumblebug has a module for "expand MCIS" to add more VMs in a MCIS.
This PR enable the default agent installation option for the "expand MCIS" module.
Note that,
API and object parameters of MCIS will be changed.
(for MCIS creation request, MCIS info)
`InstallMonAgent   string    json:"installMonAgent" // yes or no`
(in VM info)
`MonAgentStatus   string  json:"monAgentStatus" // installed, notInstalled, failed`
- Create a MCIS(single VM) for CB-Draonfly hosting
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./gen-mcis-for-df.sh aws 1 df …
```
> Apply default agentInstall for mcis expand module

- src/api/rest/server/mcir/spec.go
- src/api/rest/server/server.go
- src/core/mcir/spec.go
- test/official/7.spec/test-sort-specs.sh
CB-Tumblebug Go 코드 내부에서 사용하는 방법:
`func SortSpecs(specList []TbSpecInfo, orderBy string, direction string) ([]TbSpecInfo, error)` 함수 호출
---
호출 예시:
`func RestTestSortSpecs(c echo.Context) error` 에 기재되어 있음
```Go
content, err = mcir.SortSpecs(content, "mem_GiB", "descending")
```
---
테스트를 위한 REST API 호출:
`test/official/7.spec/test-sort-specs.sh` 에 기재되어 있음
```
curl -H "${AUTH}" -sX GET http://$TumblebugServer/tumblebug/ns/$NS_ID/resources/testSortSpecs -H 'Content-Type: application/json' -d \
'{ 
"num_vCPU": '4'
}' | json_pp
```
- JSON body 의 `"num_vCPU": 4` 는 정렬용이 아니라, 정렬에 사용할 데이터를 필터하기 위한 조건임
(`"num_vCPU": 4` 인 spec들 중에서)
- 정렬 조건은 `func RestTestSortSpecs(c echo.Context) error` 에 하드코딩 되어 있음
`content, err = mcir.SortSpecs(content, "mem_GiB", "descending")`
("mem_GiB" 내림차순으로 정렬)
- 결과 …
> Add 'SortSpecs' function

- src/core/mcir/image.go
- src/core/mcir/spec.go
- Resolves #307 
---
`cb-tumblebug/test/official/7.spec# ./filter-specs.sh | less`
```
{
"spec" : [
{
"max_num_storage" : 0,
"name" : "aws-us-east-1-a1.medium",
"num_core" : 0,
"num_vCPU" : 1,
"storage_GiB" : 0,
"id" : "aws-us-east-1-a1.medium",
"evaluationScore_09" : 0,
"num_storage" : 0,
"evaluationScore_04" : 0,
"connectionName" : "aws-us-east-1",
"evaluationScore_02" : 0,
"evaluationScore_01" : 0,
"evaluationScore_08" : 0,
"gpu_p2p" : "",
"ebs_bw_Mbps" : 0,
"gpu_model" : "",
"gpumem_GiB" : 0,
"description" : "",
"num_gpu" : 0,
"max_total_storage_TiB" : 0,
"evaluationScore_05" : 0,
"cspSpecName" : "a1.medium",
"orderInFilteredResult" : 0, …
```
> Fix bug in 'FilterSpecs' function

- src/api/rest/server/mcis/control.go
- src/core/mcir/obsolete/publicip.go
- src/core/mcir/obsolete/subnet.go
- src/core/mcir/obsolete/vnic.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/orchestration.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/8.mcis/create-mcis-policy.sh
MCIS 자동 제어에,
- ScaleOut (MCIS에 지정된 요구사항 형태의 VM 추가)
- ScaleIn (MCIS의 VM 중, label=="Autogen" 인 VM 1개 종료 및 삭제)
- ScaleOut 자동 제어 정책 등록 예시
8.mcis/create-mcis-policy.sh aws 3 shson
```
curl -H "${AUTH}" -sX POST http://$TumblebugServer/tumblebug/ns/$NS_ID/policy/mcis/${CONN_CONFIG[$INDEX,$REGION]}-${POSTFIX} -H 'Content-Type: application/json' -d \
'{
"description": "Tumblebug Auto Control Demo",
"policy": [{
"autoCondition": {
"metric": "cpu",
"operator": ">=",
"operand": "7",
"evaluationPeriod": "5"
},
"autoAction": {
"actionType": "ScaleOut",
"placement_algo": "tbd",
"vm": {
"name": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'-Autogen",
"imageId": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'",
"vmUserAccount": "cb-user",
"connectionName": "'${CONN_CONFIG[$INDEX,$REGION]}'",
"sshKeyId": …
```
>  Add auto control ScaleOut and ScaleIn actions

- src/core/mcis/control.go
- src/core/mcis/orchestration.go
- test/official/8.mcis/create-mcis-policy.sh
- test/official/sequentialFullTest/create-mcis-for-df.sh
- test/official/sequentialFullTest/expand-mcis.sh
- test/official/sequentialFullTest/gen-sshKey-withGivenMcisName.sh
- 자동 제어의 scaleout 시, "placement_algo": "random" 으로 선택하면, MCIS 내의 기존 VM의 템플릿을 복제해서 ScaleOut용 VM의 템플릿으로 사용하도록 기능 수정
```
curl -H "${AUTH}" -sX POST http://$TumblebugServer/tumblebug/ns/$NS_ID/policy/mcis/${CONN_CONFIG[$INDEX,$REGION]}-${POSTFIX} -H 'Content-Type: application/json' -d \
'{
"description": "Tumblebug Auto Control Demo",
"policy": [
{
"autoCondition": {
"metric": "cpu",
"operator": ">=",
"operand": "20",
"evaluationPeriod": "5"
},
"autoAction": {
"actionType": "ScaleOut",
"placement_algo": "random",
"vm": {
"name": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'-AutoGen",
"imageId": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'",
"vmUserAccount": "cb-user",
"connectionName": "'${CONN_CONFIG[$INDEX,$REGION]}'",
"sshKeyId": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'", …
```
> Enable scaleout with auto vm template selection

- src/api/grpc/server/common/namespace.go
- src/api/rest/server/common/namespace.go
- src/core/common/namespace.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- Related issue: #313 
- 기존에는 underscore-to-hyphen + ToLower 로직을 `GenId` 함수에 넣어서 사용했었는데,
똑같은 내용의 `ToLower` 라는 함수를 추가했습니다.
- `LowerizeAndCheckNs` 함수는 주석처리했고,
`CheckNs` 함수를 되살렸습니다.
- `LowerizeAndCheckNs` 함수 호출 부분들을
`ToLower` 호출 + `CheckNs` 호출 로 분리했습니다.
- 이 PR에서는 `LowerizeAndCheckNs` 함수에 대해서만 다루고,
다른 `LowerizeAndCheck*` 함수들은 별도의 PR로 다룰 예정입니다.
- 테스트 스크립트로 테스트 했습니다.
- `./testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
- `./cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
> Separate LowerizeAndCheckNs function

- .github/dependabot.yml
CC: @hermitkim1
---
From https://github.com/docker/setup-qemu-action#keep-up-to-date-with-github-dependabot
---
Since [Dependabot](https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot) has [native GitHub Actions support](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem), to enable it on your GitHub repo all you need to do is add the `.github/dependabot.yml` file:
```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
directory: "/"
schedule:
interval: "daily"
```
> Enable GitHub Actions autoupdate

- .github/workflows/build-and-publish-container-image.yaml
[#356 관련 PR]
The `build-and-publish-container-image.yaml` workflow will ignore files and directories as follows:
- Ignore files: '\*\*md', '.all-contributorsrc', '.gitignore', 'LICENSE'
- Igrnoe directories: 'assets/\*\*', 'test/\*\*"
It has passed a test on the forked repository. :heavy_check_mark:
For double-check, I will make another PR to add `.idea/` to the `.gitignore`.  :smiley:
> Add paths-ignore to workflow

- .github/workflows/prow-commands.yml
This PR proposes a GitHub workflow for action by command-style comments (inspired by Kubernetes Prow))
Supported comments are as follows,
/assign 
/unassign
/approve 
/retitle 
/area 
/kind 
/priority 
/remove 
/lgtm 
/close 
/reopen 
/lock 
/milestone 
/hold 
/cc 
/uncc
This GitHub workflow is based on jpmcb/prow-github-actions .
https://github.com/jpmcb/prow-github-actions/blob/main/docs/commands.md
You can see a demo PR from [here](https://github.com/seokho-son/docs/pull/18) to check actions.
> Add workflow for action by command-style comments

- .github/workflows/auto-merge.yml
This workflow consists of 3 main steps.
For each event on a comment (in PR)
1. Check author_association is OWNER
1. Apply 'approved' label when OWNER left '/approve' comment
1. AutoMerging if this PR has MERGE_LABELS: approved, lgtm (not wip, hold)
You can check demo from [here](https://github.com/seokho-son/docs/pull/18)
> Add workflow for automatic PR merge

- .github/workflows/build-and-publish-container-image.yaml
Add 'CODEOWNERS' file path to
paths-ignore in build-and-publish-container-image.yaml
(we don't need to build and publish image according to codeowners files changes)
> Add path-ignore in build-publish-container-image

- .github/workflows/prow-commands.yml
Enhance performance of prow wf by skipping rule.
This workflow step will be skipped, unless 
`startsWith(github.event.comment.body, '/')` is satisfied .
> Enhance performance of prow wf by skipping rule

- go.sum
- src/api/rest/server/mcir/common.go
- src/api/rest/server/mcir/sshkey.go
- src/api/rest/server/server.go
- src/core/common/common.go
- src/core/common/config.go
- src/core/common/namespace.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/image_test.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/spec_test.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/core/mcis/orchestration.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/5.sshKey/testAddAsso.sh
- test/official/5.sshKey/testDeleteAsso.sh
- Related issue: #348 
- @seokho-son 께서 https://github.com/cloud-barista/cb-tumblebug/pull/347#pullrequestreview-568827067 에서
`associatedObj` 들의 예시를 `mcis/mcis-01/vm/vm-04` 이렇게 제안해 주셨습니다.
저도 타당하다고 생각합니다.
(mcis-01, vm-04, 그리고 여기에 연결되는 obj 들은 모두 같은 ns 에 속하므로 ns 를 기재하지 않아도 됨)
그런데 이미 사용되고 있는 `GenMcisKey(nsId, mcisId, vmId)` 함수를 여기에서도 활용하니
`/ns/ns-01/mcis/avengers-jhseo/vm/aws-us-east-1-jhseo-master` 의 형식이 되었습니다.
이 형식은 변경도 가능하므로, 의견이 있으시면 알려 주시면 감사하겠습니다.
- 작성한 코드에서 제 예상과 다르게 동작하는 부분이 있었고,
이(예상과 다르게 동작하는 것)를 찾는 데에 오래 걸렸습니다.
https://play.golang.org/p/uX2UZcx4LLj
의 결과를 보시면
`result: []` 인데
`len(result): 1` 입니다.
0 이어야 할 것 같은데 말이죠..
- `sjson` 관련 참고사항
sjson 을 이용하여 json 을 조작할 때,
array 에 새로운 element 를 추가할 때에는 `-1` 이라는 index 를 사용하면 된다고 합니다.
그런데 그 json array 가 `[]` 일 때에만 정상 작동하고
`""` (`null`) 일 때에는 …
> Add associatedObjList mgmt feature in TB sshKey object

- .github/workflows/build-amd64-container-image.yaml
- .github/workflows/build-and-publish-container-image.yaml
- .github/workflows/publish-multi-arch-container-images.yaml
For efficient continuous integration (CI), the existing workflow has been divided into the two below.
- Publish (build and publish) multi-arch container images on `merged` event.
- Build an amd64 container image on `pull request` event.
And also, the workflow name, job ID and name are renamed for readability on GitHub Actions.
> Divide and edit container-related workflows for efficiency

- README.md
[![GoDoc](https://godoc.org/github.com/cloud-barista/cb-tumblebug?status.svg)](https://pkg.go.dev/github.com/cloud-barista/cb-tumblebug)
This badge will provide the link for cb-tumblebug source code documentation by `godoc`
https://pkg.go.dev/github.com/cloud-barista/cb-tumblebug
> Add godoc link and badge

- .gitignore
- Dockerfile
- assets/cloudlocation.csv
- src/Makefile
- src/core/common/config.go
- src/core/common/namespace.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/obsolete/publicip.go
- src/core/mcir/obsolete/subnet.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcis/control.go
- src/core/mcis/orchestration.go
- src/core/mcis/utility.go
- src/main.go
- test/official/3.vNet/spider-create-vNet.sh
- test/official/3.vNet/spider-delete-vNet.sh
- Move `src/resource/cloudlocation.csv` to `assets/` (Resolves #259)
- `cloudlocation.csv` 에 Mock driver 테스트용 라인 추가
- 컨테이너 이미지 빌드 시 `cloudlocation.csv` 및 `assets/` 파일을 컨테이너로 복사하는 부분이 누락되어 있었고, 이것을 보완
- `.gitignore` 에 `vendor/` 추가
- `go build` 시 `vendor/` 디렉토리가 있어도 이를 무시하도록 `Makefile` 및 `Dockerfile` 수정 (Resolves #406)
- `GenId` 함수가 실제로는 대문자->소문자, `_`->`-` 변환만을 하고 있어서, 
`GenId` 레퍼런스들을 `ToLower` 로 일괄 변경하여 명확성/readability 강화
- Spider 테스트 스크립트 추가
- `test/official/3.vNet/spider-create-vNet.sh`
- `test/official/3.vNet/spider-delete-vNet.sh`
> Move cloudlocation.csv, and so on

- .github/workflows/publish-multi-arch-container-images.yaml
- Resolves #409 
> **What would you like to be added**
> :
> 얼마 전에 CB-TB repo 에 v0.3.1 tag 가 추가되었는데, Docker Hub 과 GHCR 에는 container image 가 push 되지 않았습니다.
> 
> * https://github.com/cloud-barista/cb-tumblebug/releases
> * https://hub.docker.com/r/cloudbaristaorg/cb-tumblebug/tags?page=1&ordering=last_updated
> * https://github.com/orgs/cloud-barista/packages/container/cb-tumblebug/versions
> 
> **Why is this needed**
> :
> CB-TB repo 에 tag 가 추가될 때 Docker Hub 과 GHCR 에 자동으로 container image 가 push 되면 편리할 것으로 보입니다.
> 
> **Suggested solution**
> :
> [publish-multi-arch-container-images.yaml](https://github.com/cloud-barista/cb-tumblebug/blob/master/.github/workflows/publish-multi-arch-container-images.yaml) 에 다음을 추가
> 
> ```yaml
> on:
>   push:
>     tags:
>       - "v*.*.*"
> ```
> Enable auto-push on new tag, to Docker Hub and GHCR

- src/core/common/utility.go
- src/core/mcis/control.go
- test/official/8.mcis/create-mcis.sh
- test/official/conf.env
resolves #412
기존 MCIS 생성 API에서,
vm 요청 명세에 vmGroupSize 를 1 이상 입력하면,
(참고: vmGroupSize 를 명시하지 않거나 0으로 지정하면, 기존의 개별 vm 생성 방식과 동일하게 동작함)
TbVmGroupInfo 오브젝트가 생성되고, CB-TB가 지정된 숫자만큼 자동으로 vm을 생성함.
이때 vm의 이름은 
vm 명세에 지정된 name에 
postfix (`-N`) 를 추가하여 자동 생성.
**"vmGroupSize": "3",**
[요청 예시]
```
curl -H "${AUTH}" -sX POST http://$TumblebugServer/tumblebug/ns/$NS_ID/mcis -H 'Content-Type: application/json' -d \
'{
"name": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'",
"description": "Tumblebug Demo",
"installMonAgent": "yes",
"vm": [ {
"vmGroupSize": "3",
"name": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'",
"imageId": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'",
"vmUserAccount": "cb-user",
"connectionName": "'${CONN_CONFIG[$INDEX,$REGION]}'",
"sshKeyId": …
```
> Add VM group feature to request multiple VMs simply

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/sequentialFullTest/get-object.sh
- test/official/sequentialFullTest/list-object.sh
기존 텀블벅은 
텀블벅에 등록된 오브젝트(특히 문제가 있는 오브젝트)를 개발자가 확인하는 데 어려움이 있었음.
본 PR은 텀블벅의 오브젝트 리스트를 조회하고,
값을 조회할 수 있는 기능 제공. (관리자 및 개발자를 위한 기능)
1) objectList
2) objectValue
예를 들어,
1) `http://localhost:1323/tumblebug/`**objectList**?key=`/ns/ns-01/` 는 
`/ns/ns-01/` 가 포함된 모든 TB 오브젝트의 ID 리스트를 반환함.
2) `http://localhost:1323/tumblebug/`**objectValue**?key=`/ns/ns-01/mcis/aws-ap-southeast-1-shson/vmgroup/aws-ap-southeast-1-shson`  는 
`/ns/ns-01/mcis/aws-ap-southeast-1-shson/vmgroup/aws-ap-southeast-1-shson` 오브젝트의 값을 반환함.
테스트 스크립트:
1) list-object.sh
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./list-object.sh /ns/ns-01/mcis/
{ …
```
> Add feature for general TB object retrieve

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/sequentialFullTest/delete-object.sh
- test/official/sequentialFullTest/delete-objects-becareful.sh
- test/official/sequentialFullTest/list-object.sh
- Tumblebug Object의 강제 삭제 기능 제공. 
- Tumblebug Object 직접 조회 기능 API 업데이트.
기존 텀블벅은 텀블벅에 등록된 오브젝트(특히 문제가 있는 오브젝트)를 개발자가 확인하는 데 어려움이 있었음.
텀블벅의 오브젝트를 조회하고 데이터를 강제 삭제할 수 있는 기능 제공. (관리자 및 개발자를 위한 기능)
1) get objects
2) get object
3) delete object
4) delete objects
----
1) GET `http://localhost:1323/tumblebug/`**objects**?key=`/ns/ns-01/` 는 
`/ns/ns-01/` 가 포함된 모든 TB 오브젝트의 ID 리스트를 반환함.
2) GET `http://localhost:1323/tumblebug/`**object**?key=`/ns/ns-01/mcis/aws-ap-southeast-1-shson/vmgroup/aws-ap-southeast-1-shson`  는 
`/ns/ns-01/mcis/aws-ap-southeast-1-shson/vmgroup/aws-ap-southeast-1-shson` 오브젝트의 값을 반환함.
3) DELETE `http://localhost:1323/tumblebug/`**object**?key=`/ns/ns-01/mcis/aws-ap-southeast-1-shson/vmgroup/aws-ap-southeast-1-shson`  는 …
> Add tumblebug obj delete feature and update obj api

- test/official/sequentialFullTest/deploy-weavescope-to-mcis.sh
이 PR은 
MCIS에 [WeaveScope](https://www.weave.works/docs/scope/latest/introducing/) 클러스터를 배치하여,
MCIS의 구성 형상(트래픽, 리소스, 프로세스 현황 등)을 비주얼라이즈하는 GUI를 제공할 수 있도록
WeaveScope 자동 설치 및 배치 스크립트를 제공합니다.
~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ 
스크립트 실행
> ./deploy-weavescope-to-mcis.sh aws 2 shson
마지막 출력에 따라 Web 접속
> URL: 15.222.62.163:4040/#!/state/{"topologyId":"hosts"}
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./deploy-weavescope-to-mcis.sh aws 2 shson
[Check jq package (if not, install)]
install ok installed
[Test for AWS]
MASTERIP: 15.222.62.163
MASTERVM: …
```
> Add WeaveScope deployment script

- src/api/rest/server/mcis/control.go
- src/core/mcis/control.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/conf.env
- test/official/sequentialFullTest/deploy-weavescope-to-mcis.sh
Add private IP in mcis status to enhance weavescope deployment
- MCIS status 오브젝트에 private_ip 항목을 추가함.
- Weavescope deployment 도구를 개선함. (노드간 private IP를 인식하도록)
- API 문서화를 위한 annotation 일부 개선
[Weavescope 개선 관련]
- Private IP를 인식하는 VM간의 연결성을 보여줄 수 있음
[Swag 를 활용한 API 문서화 관련]
- Get MCIS에서, 다중 쿼리 파라미터에 대한 명시 (Get MCIS는 기본 정보 조회, 상태 조회, 상태 제어 등을 쿼리 파라미터로 처리)
- Swag에서는 다중 응답에 대한 표현이 어려움으로, 임시 방편 마련
> Add private IP in mcis status to enhance weavescope deployment

- src/core/mcir/sshkey.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
기존에 SSH username 를 찾는 메커니즘이 비효율적이었음. (username 리스트에서 라운드로빈으로 계속 확인)
한번이라도 성공한 username을 저장해두었다가, 성공한 username이 있는 경우에는 다시 검색하지 않고 바로 사용.
spec 오브젝트에, verifiedUserName 항목이 추가되어, API 갱신.
> Enhance ssh username verification performance

- src/core/mcir/common.go
- Resolves #426
- `UpdateAssociatedObjectList` 함수의 "delete" 파트에는 여전히 SJSON 을 사용하도록 두었습니다. 
`UpdateAssociatedObjectList` 함수의 "delete" 파트는 문제 없이 동작하고 있습니다.
- **하지만, 다른 문제가 있습니다.**
이 PR로 업데이트되는 `UpdateAssociatedObjectList` 함수의 "add" 파트와 관련이 있습니다.
[문제에 대한 설명]
현재 `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh` 스크립트는 
3개의 VM으로 구성되는 1개의 MCIS를 생성합니다.
`❯ ./testAll-mcis-mcir-ns-cloud.sh mock 1 jhseo`
```JSON
...
"targetStatus" : "None",
"installMonAgent" : "no",
"masterVmId" : "mock-seoul-jhseo-0",
"masterIp" : "4.3.2.1",
"status" : "Running-(3/3)",
"name" : "mock-seoul-jhseo",
"targetAction" : "None",
"id" : "mock-seoul-jhseo"
}
}
```
---
이 스크립트를 실행하면, 먼저
- vNet
- securityGroup
- sshKey
- image
- spec
5종류의 CB-Tumblebug MCIR object 를 1개씩 생성하고,
이후 3개의 VM으로 구성되는 1개의 MCIS를 생성하면서
위에서 …
> Fix JSON unmarshaling error

- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
Enhance error handing for provisioning and cmd phases
1) Add SystemMessage string in TbVmInfo
to share systeam-given string message (especially for provisioning errors)
2) Avoid RunSSH to not ready VM
>  Enhance error handing for provisioning and cmd phases

- test/official/8.mcis/add-vmgroup-to-mcis.sh
- test/official/8.mcis/create-mcis.sh
- test/official/sequentialFullTest/deploy-dragonfly-docker.sh
- test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
This PR enhances 
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./create-mcis-for-df.sh aws 1 shson
[For AWS]
[Single excution for a CSP region]
[For AWS]
...
...
Dozing for 1 : 1 (Back to work)
[For AWS]
{
"status" : {
"targetStatus" : "None",
"vm" : [
{
"location" : {
"longitude" : "103.8000",
"nativeRegion" : "ap-southeast-1", …
```
> Enhance script stability and usability

- test/official/conf.env
- `conf.env` 에 등록되어 있는 region 수
- Azure: 3개 => 40개
- GCP: 3개 => 23개
- 주의사항
- Tumblebug 테스트 스크립트를 CSP=all 로 실행할 때
`conf.env` 에 등록되어 있는 region 들을 실제로 활용하려면
`conf.env` 에서 다음 부분을 수정해야 할 것으로 보입니다.
```
NumCSP=4
CSPType[1]=aws
NumRegion[1]=8
CSPType[2]=alibaba
NumRegion[2]=1
CSPType[3]=gcp
NumRegion[3]=3
CSPType[4]=azure
NumRegion[4]=1
CSPType[5]=mock
NumRegion[5]=1
```
> Add Azure & GCP regions

- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/spec.go
- src/api/rest/server/server.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- test/official/6.image/lookupImage.sh
- test/official/6.image/lookupImageList.sh
- test/official/7.spec/lookupSpec.sh
- test/official/7.spec/lookupSpecList.sh
- Related issue: GCP image lookup fails (#442)
- Related issue: How to lookup GCP VM image info? (https://github.com/cloud-barista/cb-spider/issues/339)
Tumblebug 에 LookupImage 함수가 있습니다. (호출되면 Spider 에 Lookup 요청 보냄)
그런데, LookupImage 에 대한 REST API 를 호출하면, Tumblebug 이 Spider 를 호출하지 않고 바로 404 Not Found 를 리턴하는 현상이 있었습니다.
(GCP 의 `cspImageId` 가 URL 형식이라서 발생하는 현상으로 추정)
[요청]
`GET http://$TumblebugServer/tumblebug/lookupImage/https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024`
```JSON
{
"connectionName": "gcp-asia-east1"
}
```
[응답]
```JSON
{
"message": "Not Found"
}
```
---
그래서, `cspImageId` 를 
GET 요청의 URL 이 아니라
JSON 바디에 넣는 것으로 바꾸니
[요청]
`GET http://$TumblebugServer/tumblebug/lookupImage`
```JSON
{
"connectionName": "gcp-asia-east1", …
```
> Update REST API of LookupImage & LookupSpec

- src/core/mcir/image.go
- test/official/6.image/registerImageWithId.sh
- Related issue comment: https://github.com/cloud-barista/cb-spider/issues/339#issuecomment-813383531
- Resolves https://github.com/cloud-barista/cb-spider/issues/339
- 필요 시, PR #444 를 롤백 할 수도 있습니다.
[테스트 결과]
`❯ ./lookupImage.sh gcp 1 jhseo`
```JSON
{
"Name" : "",
"Status" : "READY",
"KeyValueList" : [
{
"Key" : "Name",
"Value" : "ubuntu-minimal-1804-bionic-v20191024"
},
{
"Value" : "",
"Key" : "SourceImage"
},
{
"Key" : "SourceType",
"Value" : "RAW"
},
{
"Value" : "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024",
"Key" : "SelfLink"
},
{
"Key" : "Family",
"Value" : "ubuntu-minimal-1804-lts"
},
{
"Key" : "DiskSizeGb",
"Value" : "10"
}
],
"IId" : {
"SystemId" : "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/gl …
```
> Add URL encoding for Spider image lookup API call

- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/core/mcis/sshrun.go
- src/main.go
- test/official/9.monitoring/get-monitoring-data.sh
- test/official/9.monitoring/install-agent.sh
- test/official/conf.env
- test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh
- test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh
1) MCIS 생성시 Agent 자동 설치하는 코드를 병렬화하여, 전체 프로비저닝 속도 향상
2) Azure CSP 의 리전 테스트 및 정상 동작하지 않는 리전을 conf.env 구성상 뒤로 바꿈
[동작하지 않는 리전]
- uaecentral
- germanynorth
- southafricawest
- norwaywest
- francesouth
- switzerlandwest
> Expedite auto agent installation

- .gitignore
- assets/cloudlocation.csv
- src/core/mcis/control.go
- test/official/3.vNet/create-vNet.sh
- test/official/8.mcis/get-mcis.sh
- test/official/conf.env
- test/official/sequentialFullTest/change-mcis-hostname.sh
- test/official/sequentialFullTest/clean-mcis-only.sh
- test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh
- test/official/sequentialFullTest/command-mcis-custom.sh
- test/official/sequentialFullTest/command-mcis-vm-custom.sh
- test/official/sequentialFullTest/create-mcis-for-df.sh
- test/official/sequentialFullTest/create-mcis-for-ws.sh
- test/official/sequentialFullTest/create-mcis-only.sh
- test/official/sequentialFullTest/createAll-mcis-mcir-ns-cloud.sh
- test/official/sequentialFullTest/deploy-weavescope-to-mcis.sh
- test/official/sequentialFullTest/deploy-weavescope-to-multi-mcis-update-noinstall.sh
- test/official/sequentialFullTest/deploy-weavescope-to-multi-mcis-update.sh
- test/official/sequentialFullTest/deploy-weavescope-to-multi-mcis.sh
- test/official/sequentialFullTest/prepare-mcir-ns-cloud.sh
// Spider https://github.com/cloud-barista/cb-spider/releases/tag/v0.3.7 연동
- Fix location error
/
- Enable weavescope in ch regions
/
- Feature for change hostname based on TB info
/
- Assign isolated CIDR per cloud regions
/
- Add command-mcis-vm-custom script
/
- Enhance test history style
- Backup machanism for teset history
- Enhance script output message
- 기존: VM의 도메인 네임이 클라우드 타입에 따라서 상이하며, MCIS와 관계 파악이 어려움 
(예: 192-168-3-1, zwf23f2f, ip-xxx-vvv-eee)
- 개선: VM의 도메인 네임을 "인지하기 편한 명칭으로 변경"  [prefix]-[connectionConfig]-[PublicIP]
(예: c-alibaba-ap-northeast-1-47.74.3.124, b-aws-ap-northeast-1-18.182.26.230, ... )
- 사용 방법: /cb-tumblebug/test/official/sequentialFullTest$ ./change-mcis-hostname.sh all 1 shson42
- 기존: 클라우드별로 아이콘이 명확히 구분되지 않았음
- 개선: 클라우드별로 아이콘 색 구분 (도메인 네임에 prefix로 조정. …
> Enhance scripts and fix some bugs

- src/core/mcis/control.go
MCIS 프로비저닝 중, VM 생성에 오류가 발생한 경우에도 
여전히 `Creating` 상태로 표기되던 오류를 수정.
Status MCIS
{
"status": {
"id": "mcis-shson46",
"name": "mcis-shson46",
**"status": "Creating-(1/1)",**
"targetStatus": "Running",
"targetAction": "Create",
"installMonAgent": "yes",
"masterVmId": "aws-ap-northeast-1-shson46-lead-0",
"masterIp": "",
"masterSSHPort": "0",
"vm": [
{
"id": "aws-ap-northeast-1-shson46-lead-0",
"name": "aws-ap-northeast-1-shson46-lead-0",
"csp_vm_id": "",
**"status": "Creating",**
"targetStatus": "Running",
"targetAction": "Create",
"native_status": "",
"monAgentStatus": "",
"public_ip": "",
"private_ip": "",
"sshPort": "0",
"location": {
"latitude": "35.4100",
"longitude": "139.4200",
"briefAddr": "Tokyo",
"cloudType": "aws",
"nativeRegion": "ap-northeast-1"
}
}
]
}
Status MCIS
{
"status": { …
> Fix initial failed status in MCIS provisioning

- assets/cloudlocation.csv
- src/core/mcis/control.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
Provide SystemMessage to vm status object
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/test/official/sequentialFullTest$ ./cleanAll-mcis-mcir-ns-cloud.sh all 1 shson14 ../testSetCustom.env
VM: Status MCIS
{
"status": {
"id": "mcis-shson14",
"name": "mcis-shson14",
**"status": "Failed-(1/4)",**
"targetStatus": "Running",
"targetAction": "Create",
"installMonAgent": "no",
"masterVmId": "alibaba-ap-northeast-1-shson14-0",
"masterIp": "47.74.2.",
"masterSSHPort": "22",
"vm": [
{
"id": "aws-ap-southeast-1-shson14-0",
"name": "aws-ap-southeast-1-shson14-0",
"csp_vm_id": "",
**"status": "Failed",**
"targetStatus": "Running",
"targetAction": "Create",
"native_status": "",
"monAgentStatus": "",
**"systemMessage": …
> Provide SystemMessage to vm status object

- test/official/4.securityGroup/create-securityGroup.sh
- test/official/sequentialFullTest/deploy-jitsi-to-mcis.sh
Multi-cloud Jitsi Meet usecase.
Jitsi Meet - Secure, Simple and Scalable Video Conferences
https://github.com/jitsi/jitsi-meet
How to use
~/cb-tumblebug/test/official/sequentialFullTest$ ./deploy-jitsi-to-mcis.sh all 1 shson35 ../testSetCustom.env ${YOURDNS} ${YOUREMAIL}
Before use this script, you need to set DNS A record.
> Add jitsi video conference automation

- src/core/common/utility.go
- src/core/mcis/control.go
- src/core/mcis/orchestration.go
Resolves misspells
```
misspell97%
Misspell Finds commonly misspelled English words
cb-tumblebug/src/core/mcis/orchestration.go
Line 128: warning: "existance" is a misspelling of "existence" (misspell)
cb-tumblebug/src/core/common/utility.go
Line 145: warning: "fucntion" is a misspelling of "function" (misspell)
Line 150: warning: "fucntion" is a misspelling of "function" (misspell)
Line 218: warning: "fucntion" is a misspelling of "function" (misspell)
Line 223: warning: "fucntion" is a misspelling of "function" (misspell)
Line 262: warning: "fucntion" is a misspelling of "function" (misspell)
cb-tumblebug/src/core/mcis/control.go
Line 1109: warning: "untill" is a misspelling of "until" (misspell)
Line 1196: warning: "untill" is a misspelling of "until" (misspell)
Line 1224: warning: …
```
> Fix misspell in comments

- assets/cloudlocation.csv
- src/testclient/scripts/conf.env
- src/testclient/scripts/testSet.env
- Ref: https://docs.google.com/spreadsheets/d/1zwlgGsBFmeiw41w0ZxTdqIBFQmx5fPICVrdyNi-p1ck/edit?usp=sharing
- Related discussion: #452
- Added cloud regions
- AWS EU South 1 (Milan)  -  Opt-In required
- GCP Asia Southeast 2 (Jakarta, Indonesia, APAC)
- GCP Europe Central 2 (Warsaw, Poland, Europe)
- 기타: Alibaba ME East 1 (UAE Dubai) 는 
CB-Tumblebug 테스트 스크립트에는 있는데
https://www.alibabacloud.com/help/doc-detail/89155.htm 에는 없음
> Add cloud regions

- src/testclient/scripts/conf.env
Fix connectionconfig name to prevent length err
`CONN_CONFIG[$IX,$IY]=gcp-europe-central2`
에 의해 리소스 명칭이 너무 길어지면, gcp의 경우 오류가 발생함.
test script에서는 정상 동작하도록 CONN_CONFIG 명칭 간소화
> Fix connectionconfig name to prevent length err

- conf/setup.env
- src/api/grpc/request/test/test_api.go
- src/api/rest/server/common/config.go
- src/api/rest/server/common/namespace.go
- src/api/rest/server/common/utility.go
- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/securitygroup.go
- src/api/rest/server/mcir/spec.go
- src/api/rest/server/mcir/sshkey.go
- src/api/rest/server/mcir/vnet.go
- src/api/rest/server/mcis/control.go
- src/api/rest/server/mcis/monitor.go
- src/api/rest/server/mcis/orchestration.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
Enhance swagger documentation and UI mechanism.
If you define (source) `SELF_ENDPOINT` in `setup.env`, 
you can access Swagger UI from outside.
```
export SELF_ENDPOINT=localhost:1323
```
```
██████╗██████╗    ████████╗██████╗      
██╔════╝██╔══██╗   ╚══██╔══╝██╔══██╗     
██║     ██████╔╝█████╗██║   ██████╔╝     
██║     ██╔══██╗╚════╝██║   ██╔══██╗     
╚██████╗██████╔╝      ██║   ██████╔╝     
╚═════╝╚═════╝       ╚═╝   ╚═════╝      
██████╗ ███████╗ █████╗ ██████╗ ██╗   ██╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗╚██╗ ██╔╝
██████╔╝█████╗  ███████║██║  ██║ ╚████╔╝ 
██╔══██╗██╔══╝  ██╔══██║██║  ██║  ╚██╔╝  
██║  ██║███████╗██║  ██║██████╔╝   ██║   
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝    ╚═╝   
Multi-cloud infrastructure managemenet framework
________________________________________________ …
```
> Enhance swagger documentation and UI mechanism

- src/testclient/scripts/credentials.conf.example
We don't need `source ../testSet.env` in `credentials.conf` any more since the sourced xx.env will be provided by users as a cli parameter.
So, this PR fixes `credentials.conf.example` by removing `source ../testSet.env`
> Fix credentials.conf.example

- src/api/rest/server/common/utility.go
- src/api/rest/server/mcir/common.go
- src/api/rest/server/server.go
- src/core/mcir/common.go
- src/core/mcis/utility.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/testclient/scripts/3.vNet/create-vNet.sh
- src/testclient/scripts/3.vNet/inspect-vNet.sh
- src/testclient/scripts/4.securityGroup/inspect-securityGroup.sh
- src/testclient/scripts/5.sshKey/inspect-sshKey.sh
- src/testclient/scripts/8.mcis/inspect-vm.sh
- src/testclient/scripts/sequentialFullTest/create-all.sh
- Related PR: #501 (Add `inspectResources` function)
- #501 에서는 TB 의 모든 리소스를 (`connectionName` 으로 필터링하지 않고) 출력하는 버그가 있었고,
이 PR에서 이를 수정했습니다.
- Related discussion: #503 (import cycle regarding `inspectResources` function)
[테스트 결과]
```JSON
❯ ../8.mcis/inspect-vm.sh aws 1 jhseo
{
"resourcesOnCsp": [
{
"id": "aws-ap-southeast-1-jhseo-0",
"cspNativeId": "i-039ab7e96112287cd"
},
{
"id": "kimy-etcd-host",
"cspNativeId": "i-061fba35c45e36c80"
}
],
"resourcesOnSpider": [
{
"id": "aws-ap-southeast-1-jhseo-0",
"cspNativeId": "i-039ab7e96112287cd"
}
],
"resourcesOnTumblebug": [
{
"id": "aws-ap-southeast-1-jhseo-0",
"cspNativeId": "i-039ab7e96112287cd",
"nsId": …
```
> Add `inspectVMs` function

- src/api/rest/server/common/utility.go
- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/spec.go
- src/core/common/common.go
- src/core/mcir/image.go
- src/core/mcir/spec.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/testclient/scripts/6.image/lookupImage.sh
- src/testclient/scripts/7.spec/lookupSpec.sh
- `lookupImages` API 요청의 JSON body 에는 
`connectionName` 만 있으면 되는데
Swagger doc 에는 `cspImageId` 도 필요하다고 되어 있어서 이를 수정했습니다.
- `lookupSpecs` API 요청의 JSON body 에는 
`connectionName` 만 있으면 되는데
Swagger doc 에는 `cspSpecName` 도 필요하다고 되어 있어서 이를 수정했습니다.
- `LookupImageList`, `LookupImage`, `LookupSpecList`, `LookupSpec` 함수에
args emptiness check 로직을 추가했습니다.
- `src/testclient/scripts/7.spec/lookupSpec.sh` 테스트 스크립트가 동작하지 않는 문제가 있었고
이를 수정했습니다.
- 그 외 기타 수정
> Fix lookupImages' & lookupSpecs' Swagger docs

- src/testclient/scripts/sequentialFullTest/ansibleAutoConf/add-key.yml
- src/testclient/scripts/sequentialFullTest/ansibleAutoConf/helloworld.yml
- src/testclient/scripts/sequentialFullTest/ansibleAutoConf/mcis-shson01-host-example
- src/testclient/scripts/sequentialFullTest/conf-ansible-env.sh
- src/testclient/scripts/sequentialFullTest/gen-sshKey.sh
CB-TB를 통해 생성된, MCIS에
Ansible 을 바로 동작시킬 수 있도록 스크립트 도구 제공.
MCIS를 생성 후, `./creat-all.sh all 1 shson04 ../testSetAws.env`
cb-tumblebug/src/testclient/scripts/sequentialFullTest$ 
**./conf-ansible-env.sh** all 1 shson04 ../testSetAws.env
를 사용하면,
Ansible이 필요로하는 정보를 포함하는 파일을 자동으로 생성하여, ansibleAutoConf/MCISID-host 파일에 추가함.
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/sequentialFullTest$ ./conf-ansible-env.sh all 1 shson04 ../testSetAws.env
...
[Check Ansible (if not, Exit)]
[Command to install Ansible]
1. apt install python-pip
2. pip install ansible
3. ansible -h
4. ansible localhost -m pinginstall ok installed
[CHECK …
```
> Add MCIS Ansible environment automation script

- src/core/mcir/image.go
- src/testclient/scripts/conf.env
- Cloudit 의 경우, `spiderImage.IId.SystemId` 에 UUID 가 담겨져 리턴되어 옴.
하지만 VM 생성에는 `spiderImage.IId.NameId` 에 담긴 값 (예: `CentOS-7`) 이 필요함.
- @powerkimhub 님의 말에 따르면, Tumblebug 에서는 Spider 가 주는 값 중
`SystemId` 는 이용할 일이 없을 것이며
`NameId` 를 이용하면 된다고 함.
- Cloudit 은 테스트 완료하였으나
다른 CSP 에 대해서는 테스트가 필요함. (AI to @jihoon-seo)
> Update cspImageId field

- conf/log_conf.yaml
- conf/setup.env
- src/api/rest/server/mcis/control.go
- src/api/rest/server/server.go
- src/core/mcis/control.go
- Related issue: #541
- Related issue: #546 
---
- `ListVmId` 함수는 결과를 `mzc01-c-1-1yn8c` 형태로 리턴하도록 작성되어 있음.
- `testListVmId` REST API를 만들어 `ListVmId` 함수를 테스트해 보면, 정상적으로 처리함. (https://github.com/cloud-barista/cb-tumblebug/issues/546#issuecomment-847715413)
- 그러나, `ListVmId` 함수가 다른 함수에 의해 호출되는 경우, 
vmId 가 `/ns/ns-01/mcis/mzc01-import/vm/mzc01-c-1-1yn8c` 형태로 리턴하는 경우가 있음.
- 위의 현상이 발생한 경우, 
CBStore Get 위한 key 생성할 때
key = nsId + mcisId + vmId 하지 않고
key = vmId 하는 hotfix 임.
> Hotfix for ListVmId malfunctioning

- src/api/grpc/server/server.go
- grpc_conf.yaml 에서 Interceptos 항목이 존재하지 않을 경우 버그 발생하여 수정
> Fix interceptors nil in grpc_conf.yaml

- src/api/rest/server/mcis/control.go
- src/core/mcis/control.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/testclient/scripts/8.mcis/refine-mcis.sh
- src/testclient/scripts/conf.env
Fix #469
MCIS에 다수의 VM을 포함시, 일부 VM에 대한 생성이 실패하거나 오류가 발생하는 경우가 있음.
본 PR은 MCIS에 문제가 있는 VM을 쉽게 정리할 수 있도록 정제 기능을 제공함.
임의로 Failed, Undefined 상태의 VM이 포함된 MCIS 생성 (총 3개의 VM: 1 failed, 1 undefined, 1 running)
```
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/sequentialFullTest$ ./create-all.sh all 1 shson16 ../testSetCustom.env 
[Input parameters]
CSP: all, REGION: 1, POSTFIX: shson16,
[Parallel excution for all CSP regions]
- Create MCIR in alibaba-cn-wulanchabu
- Create MCIR in alibaba-cn-heyuan
- Create MCIR in alibaba-cn-chengdu …
```
> Add MCIS Refine feature

- src/core/mcis/control.go
- src/testclient/scripts/conf.env
- src/testclient/scripts/sequentialFullTest/deploy-jitsi-to-mcis.sh
- src/testclient/scripts/testSet.env
AWS에서만 가능하던 Jisti 배포 스크립트를
GCP, Alibaba, Azure 까지 확대
++
src/core/mcis/control.go 일부 코드 보완
> Fix jitsi script for multiple CSPs

- src/api/grpc/cbadm/cmd/config.go
- src/api/grpc/cbadm/cmd/connectinfo.go
- src/api/grpc/cbadm/cmd/credential.go
- src/api/grpc/cbadm/cmd/driver.go
- src/api/grpc/cbadm/cmd/gclient.go
- src/api/grpc/cbadm/cmd/image.go
- src/api/grpc/cbadm/cmd/keypair.go
- src/api/grpc/cbadm/cmd/mcis.go
- src/api/grpc/cbadm/cmd/namespace.go
- src/api/grpc/cbadm/cmd/network.go
- src/api/grpc/cbadm/cmd/region.go
- src/api/grpc/cbadm/cmd/root.go
- src/api/grpc/cbadm/cmd/securitygroup.go
- src/api/grpc/cbadm/cmd/spec.go
- src/api/grpc/cbadm/cmd/tbutil.go
- src/api/grpc/cbadm/cmd/version.go
- src/api/grpc/cbadm/cmd/yamlproc.go
- src/api/grpc/cbadm/proc/connectinfos.go
- src/api/grpc/cbadm/proc/keypair.go
- src/api/grpc/cbadm/proc/mcis.go
- src/api/grpc/cbadm/testclient/scripts/8.mcis/delete-mcis.sh
- src/api/rest/server/common/namespace.go
- src/testclient/scripts/8.mcis/delete-mcis.sh
- Englishfy Korean comments in cbadm codes (Related issue: #566)
- Update messages in `delete-mcis.sh` (Related issue: #586)
- Update return message in `RestDelNs`
```diff
-"The ns has been deleted"
+"The ns "+c.Param("nsId")+" has been deleted"
```
> Englishfy Korean comments in cbadm codes

- conf/log_conf.yaml
- src/core/mcis/control.go
기존에 MCIS delete 를 위해서는 
MCIS의 `terminated` 상태가 의무 조건이었으나,
MCIS를 terminate 하면, CSP의 경우 VM 정보 자체를 삭제하는 경우가 있으므로,
MCIS terminate 이후에 status를 조회하면, 문제가 있는 상태로 표시 될 수 있음.
따라서, MCIS delete의 조건에 비정상적인 VM 오브젝트도 삭제가 가능하도록
- StatusFailed
- StatusUndefined
를 추가하였습니다.
> Relieve MCIS delete condition

- src/api/grpc/cbadm/cmd/tbutil.go
- src/api/grpc/request/mcisapi.go
- list object 에서 key 가 없을 경우 전체 object 표시하게 함
- SpiderVMInfo 의 StartTime 필드가 공백일 경우 json 객체 복사할 때 time format parsing 에러 방지하기 위해 제거
=> SpiderVMInfo 의 정보는 client grpc api 에서는 필요 없음
> Fix list object and remove SpiderVMInfo field for grpc

- assets/scripts/setgame.sh
- src/testclient/scripts/sequentialFullTest/deploy-game-js.sh
Add script for deploying web game server
- Game server (MIT): https://github.com/Jerenaux/westward
How to use (1: Create MCIS, 2: Deploy Game)
- ./create-all.sh all 1 game6 ../testSetCombination.env 
- ./deploy-game-js.sh all 1 game6 ../testSetCombination.env 
How to access the Game server (access with your web browser)
- http://{{VM-Public-IP}}:8081
Note
- Tested with aws, gcp, alibaba, azure
> Add script for deploying web game server

- README.md
Here's a simple update of README for building and running cb-tumblebug from its source code.
- Add `# apt install make`
- Add `# apt install gcc`
- Set a title, "필요 패키지/도구 설치" and adjust indentation
> Update README to add the required packages

- src/core/mcis/control.go
- CreateVm() 함수에서 REST 와 GRPC 의 CSP 요청 VM ID 동일하게 수정
> Fix csp vm id for grpc method call

- src/core/common/namespace.go
- src/core/mcis/control.go
- src/testclient/scripts/conf.env
- src/testclient/scripts/sequentialFullTest/clean-mcir-ns-cloud.sh
Enhance and expedite mcis lifecycle handling.
1) 대규모 MCIS의 상태 제어시, terminated 상태가 가끔씩 undefined 상태로 처리되던 버그를 때려잡음... (데이터를 읽어와서 처리해서 다시 저장하는 중간에, 데이터를 수정하는 상황.. 그러나 락을 잡지 않고 최대한 처리함)
2) mcis, vm 등 오브젝트 데이터의 업데이트가 빈번하여, 오브젝트를 조회하여 값이 동일한 경우 업데이트하지 않도록 처리
3) 상태 조회시 public ip 를 지속적으로 업데이트(csp에서 확인)하였으나, 자원 절약을 위해 필요한 상황(vm의 상태가 변경되는 시점)에만 public ip를 조회하도록 처리하여, 처리 고속화
4) 전체 삭제 Script에서 등록된 클라우드(커넥션컨피그)는 삭제하지 않도록 처리 (등록해두어도 특별히 자원을 먹지 않음으로 편의상)
> Enhance and expedite mcis lifecycle handling

- src/api/grpc/cbadm/testclient/scripts/conf.env
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/clean-mcir-ns-cloud.sh
- src/testclient/scripts/conf.env
- #625 변경사항을 `cbadm` test script 에도 반영
- Remove removing cloud infos in script
- Change default ns name in script
- VM 이름 길이 제한 (Cloudit: 45자, NCP: 30자) 충족을 위해 conn config 이름 단축
> Update test configs

- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/utility.go
- rest call 하고 나서 connection 이 계속 살아 있어 자동 close 하게 설정
=> close 를 안하면 가끔 Unsolicited response received on idle HTTP channel ... 로그가 화면에 표시
- control.go 의 GetVmStatus() 에서 가끔 "Body length 0" 에러 발생 
=> 참고 : https://stackoverflow.com/questions/31337891/net-http-http-contentlength-222-with-body-length-0
=> for 문에서 client.Do() 를 호출할 때 request 도 새로 생성해야 함
> Fix set close connection after rest call

- go.mod
- go.sum
- src/api/grpc/cbadm/Makefile
- src/api/grpc/interceptors/authjwt/auth.go
- src/api/grpc/jwt-gen/jwt_gen.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- Replace jwt-go with currently-being-maintained ver
- As-is: https://github.com/dgrijalva/jwt-go
- To-be: https://github.com/golang-jwt/jwt
- Closes #656
- `src/api/grpc/cbadm/Makefile` 에도 `go build` 명령에 `-mod=mod` 옵션 추가
- `go.mod` 파일도 있고 `vendor/` 디렉토리도 있는 경우, `go.mod` 파일을 참고하라는 옵션임
- `src/Makefile` 에는 이미 적용되어 있음
- #658 에서 
`type Region struct` 의 각 필드에 주석을 추가했으나 Swagger doc을 업데이트하지 않아서
이 PR에서 Swagger doc 업데이트
> Replace jwt-go with currently-being-maintained ver

- src/testclient/scripts/sequentialFullTest/change-mcis-hostname.sh
- src/testclient/scripts/sequentialFullTest/gen-sshKey.sh
Update script for a better output for private VM IP
1. gen-sshKey.sh 의 출력에 private IP 추가하여, private IP 를 쉽게 확인할 수 있도록 처리
2. change-mcis-hostname.sh를 통해 hostname을 Public IP 주소(xxx.xxx.xxx.xxx)를 포함한 문자열로 제공하고 있었으나, hostname에 `.` 가 포함되면 오류가 발생할 수 있는 프로그램들이 있음을 감안하여, Public IP 대신 VM ID를 hostname으로 사용하도록 수정.
> Update script for a better output for private VM IP

- README.md
- modify v0.3.0 to v0.4.0 in README
- resolve #666
> Update version description in README

- README.md
./ cleared before make command.
I modified it to [make] because it did not run with [./make].
> fix command ./make->make

- src/api/grpc/request/test/test_api.go
fix cloud-barista/cb-tumblebug#680
jihoon-seo님께서 제안하신 issue에서는 gofmt-enabled 상태에서 파일을 저장하면 issue가 해결될 것이라고 하셨는데
제가 gofmt-enabled 상태에서 저장을 해도 file format이 변경되지 않았습니다. 
그래서 terminal에서 직접 `gofmt -s -w  test_api.go`를 입력하여 format을 맞추었습니다. 
아래는 제 저장소에서의 Go Report Card입니다.
[Go Report Card](https://goreportcard.com/report/github.com/atg0831/cb-tumblebug)
잘못된 부분이 있다면 알려주시면 감사하겠습니다.
> Fix file format with gofmt

- README.md
- src/testclient/scripts/sequentialFullTest/check-test-config.sh
This PR adds a new script to check the test configuration from given configuration file. 
This script can be used to verify a current setting before execute `./create-all.sh`
input example
```
~ cb-tumblebug/src/testclient/scripts/sequentialFullTest$ 
./check-test-config.sh -n shson01 -f ../testSet-tmp.env 
```
output example
```
// POSTFIX:shson01 // TestSetFile:../testSet-tmp.env // CSP:all // REGION:1 // OPTION01: // OPTION02: // OPTION03:
[Configuration in (../testSet-tmp.env) & (../conf.env) files]
1) TumblebugServer : localhost:1323 // SpiderServer : localhost:1024
2) NameSpace ID : tb01 // MCIS ID : cb-shson01
3) Enabled CSPs for …
```
> Add check test config script

- go.mod
- go.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/mcir/common.go
- src/core/mcir/image.go
- 본격적으로 적용하기 전에, 먼저 일부분에 대해 적용해 보았습니다.
- Adopt struct validator
- `TbImageReq` struct의 `Name`, `ConnectionName`, `CspImageId` 필드를 `required` 로 설정했습니다.
- swag-go 가 Swagger doc 에도 잘 반영해 주는 것을 볼 수 있습니다.
- `TbImageReq` struct validation 시, `Name` 필드에 대해서는 `CheckString()` 함수도 실행하도록 하였습니다.
- ~Remove JSON tags from `TbImageReq` struct~
- ~`Name`, `ConnectionName`, `CspImageId` 필드의 JSON tag를 제거했습니다.~
[테스트 결과]
1. `required` 인 필드를 비워서 보냈을 때
[Req body]
```JSON
{}
```
[Resp] - 눈에 잘 안 들어오기는 합니다.
```JSON
{
"message": "Key: 'TbImageReq.Name' Error:Field validation for 'Name' failed on the 'required' tag\nKey: 'TbImageReq.ConnectionName' Error:Field validation for 'ConnectionName' failed on the 'required' tag\nKey: 'TbImageReq.CspImageId' Error:Field validation for 'CspImageId' failed on the 'required' …
```
> Adopt struct validator

- src/testclient/scripts/common-functions.sh
- src/testclient/scripts/conf.env
- src/testclient/scripts/credentials.conf.example
- src/testclient/scripts/testSet.env
Add virtual clouds for test script
```
// POSTFIX:shson03 // TestSetFile:../testSet.env // CSP:all // REGION:1 // OPTION01: // OPTION02: // OPTION03:
cb-shson03
{
"status": {
"id": "cb-shson03",
"name": "cb-shson03",
"status": "Suspended-3(3/3)",
"targetStatus": "None",
"targetAction": "None",
"installMonAgent": "no",
"masterVmId": "",
"masterIp": "",
"masterSSHPort": "",
"vm": [
{
"id": "testcloud01-seoul-0",
"name": "testcloud01-seoul-0",
"cspVmId": "tb01-cb-shson03-testcloud01-seoul-0",
"status": "Suspended",
"targetStatus": "None",
"targetAction": "None",
"nativeStatus": "Suspended",
"monAgentStatus": "notInstalled",
"systemMessage": "Suspended==Suspended",
"createdTime": "2021-09-08 18:54:46",
"publicIp": "4.3.2.1",
"privateIp": "1.2.3.4",
"sshPort": "22", …
```
> Add virtual clouds for test script

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/mcir/common.go
- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/control.go
- src/core/mcis/monitor.go
- src/core/mcis/utility.go
- 나머지 MCIR (SecurityGroup, Spec, SSHKey, vNet) 에 대해서도 validator를 도입했습니다.
- 잘 적용되었는지 (struct tag, validation 함수, 빠진 필드가 없는지 등) 검토가 이루어지면 좋습니다.
- MCIS의 `*Req` struct 중, `TbMcisReq`, `TbVmReq`, `McisCmdReq`, `MonAgentInstallReq` 에 대해서도 validator를 도입했습니다.
- 잘 적용되었는지 (struct tag, validation 함수, 빠진 필드가 없는지 등) 검토가 이루어지면 좋습니다.
- MCIS의 `*Req` struct 중, 나머지 struct에도 적용이 필요한지 검토가 이루어지면 좋습니다.
> Adopt struct validator more

- README.md
Add warning messages.
- **Be careful!** 
- Contributors should not push files related to their personal credencials (e.g., credentials.conf) to remote repository.
- The credential file for CSPs (`src/testclient/scripts/credentials.conf`) is in the [.gitignore](https://github.com/cloud-barista/cb-tumblebug/blob/ed250835a1357784afd4c857d6bd56e0d78cd219/.gitignore#L36) condition.
- So, `credentials.conf` will not be staged for a commit.
- Anyway, please be careful.
- **Be aware!** 
- Be aware that creating VMs on public CSPs such as AWS, GCP, Azure, etc. may be billed.
- With the default setting of [`testSet.env`](https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/testSet.env), TestClouds (`TestCloud01`, `TestCloud02`, `TestCloud03`) will be used to create mock …
> Add warning messages in Readme

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/docs/v0.4.7.yaml
- src/api/rest/server/mcis/control.go
- src/core/mcis/control.go
Feature request from cb-webtool. @MZC-CSC
> MCIS 목록 조회에서
> 협의 내용대로 최초 ID 목록 조회 후 각 MCID ID 별로 상세조회하여 table에 data를 채우려고 했는데
> mcis 목록에 표시되는 내용이 MCIS ID, MCIS Name, MCIS Status 정도라
> option=simple 같은 것으로 최소 필수 값정도를 목록으로 가져오는게 있으면 좋겠습니다.
> 
> 가령 mcis status 를 가져올 때 vm을 바라보지 않아도 된다면 mcis 정보만 가져와도
> id 가져온 후 상세 조회를 일일이 던지는 것 보다 불필요한 트래픽이 줄어들고 표시하기도 용이할 것 같습니다.
According to request, this PR adds the feature to list MCIS with simple response option. 
With the option=simple, CB-TB doesn't include VM details in the response body.
GET `http://localhost:1323/tumblebug/ns/tb01/mcis?option=simple`
```
{
"mcis": [
{
"id": "cb-shson01",
"name": "cb-shson01",
"status": "Running-3(3/3)",
"targetStatus": "None",
"targetAction": "None",
"installMonAgent": "no",
"label": "generated by script", …
```
> Add list MCIS simple option

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/docs/v0.4.7.yaml
- src/core/mcis/control.go
Add a field to MCIS object to count VM status by status types.
This feature will support cb-webtool.
```
"statusCount": {
"countTotal": 7,
"countCreating": 0,
"countRunning": 0,
"countFailed": 0,
"countSuspended": 6,
"countRebooting": 0,
"countTerminated": 0,
"countSuspending": 1,
"countResuming": 0,
"countTerminating": 0,
"countUndefined": 0
},
```
```
// POSTFIX:shson02 // TestSetFile:../testSet01.env // CSP:all // REGION:1 // OPTION01: // OPTION02: // OPTION03:
{
"id": "cb-shson02",
"name": "cb-shson02",
"status": "Partial-Suspended-6(7/7)",
"statusCount": {
"countTotal": 7,
"countCreating": 0,
"countRunning": 0,
"countFailed": 0, …
```
> Add MCIS status count feature and update MCIS response field

- src/testclient/scripts/sequentialFullTest/check-test-config.sh
- src/testclient/scripts/sequentialFullTest/create-all.sh
Confirm the above configuration. Do you want to proceed ? (y/n) : n
[Command: ./create-all.sh -n shson01 -x 3] has been cancelled. See you soon. :)
```
cb-tumblebug/src/testclient/scripts/sequentialFullTest$ ./create-all.sh -n shson01 -x 3
```
```
// POSTFIX:shson01 // TestSetFile:../testSet.env // CSP:all // REGION:1 // OPTION01:3 // OPTION02: // OPTION03:
[Configuration in (../testSet.env) & (../conf.env) files]
1) Tumblebug Server : localhost:1323 // Spider Server : localhost:1024
2) Enabled CSPs and regions in ../testSet.env
- [1] testcloud01 (enabled regions : 1)
- [2] testcloud02 (enabled regions : 1)
- [3] testcloud03 (enabled …
```
> Add user input to confirm test config

- src/testclient/scripts/8.mcis/status-mcis.sh
JSON array output is hard to understand at a glance.
So, convert output of MCIS status to a table.
```
Table: All VMs in the MCIS : cb-shson01
ID                       Status   PublicIP  PrivateIP  CloudType  CloudRegion  CreatedTime
--                       ------   --------  ---------  ---------  -----------  -----------
testcloud03-frankfurt-1  Running  4.3.2.1   1.2.3.4    mock       default      2021-09-14   22:43:53
testcloud02-canada-0     Running  4.3.2.1   1.2.3.4    mock       default      2021-09-14   22:43:47
testcloud03-frankfurt-0  Running  4.3.2.1   1.2.3.4    mock       default      2021-09-14   22:43:53
testcloud01-seoul-1      Running  4.3.2.1   1.2.3.4    mock       default      2021-09-14   22:43:37
testcloud02-canada-1     Running  4.3.2.1   1.2.3.4    mock …
```
> Display output of MCIS status script in a table

- go.mod
- go.sum
fix #744
Update swag version
- **before - v1.7.0**
- **after - v1.7.1**
#742 작업을 진행할 때 swag를 `go install github.com/swaggo/swag/cmd/swag@latest`로 설치를 해서 
go.mod에 swag version이 업데이트가 안 되었습니다. 
그래서 이번에는 `go get github.com/swaggo/swag/cmd/swag` 로 swag를 설치하면서 자동으로 go.mod의 
swag version을 v1.7.1로 업데이트 하였습니다. 이 과정에서 go.sum 에서 추가적으로 변경이 되는 사항이 있는데 
혹시나 dependency 관리에 문제가 될 사항은 없는지 확인 부탁드립니다.
> Update swag version 

- src/core/common/utility.go
- src/core/mcis/orchestration.go
According to the [Go Report Card](https://goreportcard.com/report/github.com/ChobobDev/cb-tumblebug) 
gofmt section has coverage of 100% now.
I believe the desires of #747  has met by this PR.
Thank you
> [#747] Format files with gofmt

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/control.go
- src/testclient/scripts/8.mcis/refine-mcis.sh
fix #755 
* src/api/rest/server/mcis/control.go에서 `RestGetMcis(c echo.Context) error` 함수의 `action == "refine"` 조건 삭제 및 `RestGetControlMcis(c echo.Context) error` 함수에 `action == "refine"` 조건 추가
* 위 두 함수의 annotations 수정
* Swagger doc 업데이트
* src/testclient/scripts/8.mcis/refine-mcis.sh 스크립트 REST API path 수정
> Move MCIS refine feature's REST API: from GET /mcis to GET /control/mcis

- src/testclient/scripts/8.mcis/status-mcis.sh
Sorting VM list by ID to enhance readability.
```
Table: All VMs in the MCIS : cb-shson01
ID                       Status   PublicIP  PrivateIP  CloudType  CloudRegion  CreatedTime
--                       ------   --------  ---------  ---------  -----------  -----------
testcloud01-seoul-0      Running  4.3.2.1   1.2.3.4    mock       default      2021-09-24   00:47:40
testcloud02-canada-0     Running  4.3.2.1   1.2.3.4    mock       default      2021-09-24   00:47:51
testcloud03-frankfurt-0  Running  4.3.2.1   1.2.3.4    mock       default      2021-09-24   00:47:57
```
> Add sorting for VMs from status-mcis

- src/core/mcis/control.go
Use `fmt.Errorf()` for error message on line 483 in src/core/mcis/control.go
Also changed some of the lines with string concetanation in `fmt.Println()` functions, to `fmt.Printf()` lines.
> use Errorf for error msg

- src/core/mcir/common.go
Fix #783 partially. 
Task 1
Line 431: warning: exported type SpiderNameIdSystemId should have comment or be unexported (golint)
> Add comment to exported SpiderNameIdSystemId

- src/core/mcir/common.go
Add comment for exported type SpiderAllListWrapper.
To fix task-2 of #783.
> Add comment for exported type SpiderAllListWrapper

- docs/designUML/README.md
docs/designUML/README.md uses http://www.plantuml.com to visualized UMLs.
However, it seems there is an error with rendering from the site.
So, I added image link directly to readme.md (for this moment)
The image link is from PR #767
> Add UML image link in design readme

- src/testclient/scripts/8.mcis/status-mcis.sh
- src/testclient/scripts/common-functions.sh
- src/testclient/scripts/sequentialFullTest/clean-mcir-ns-cloud.sh
- src/testclient/scripts/sequentialFullTest/clean-mcis-only.sh
fix #795
Now, output message is like this..
> Apply colors to important messages in script

- src/testclient/scripts/sequentialFullTest/check-network-performance.sh
- src/testclient/scripts/sequentialFullTest/set-mcis-hosts.sh
이슈
- MCIS의 모든 VM에는 퍼블릭 IP가 할당되어 있고, 이를 활용하는 것으로만 가이드되고 있습니다.
- Private 네트워크를 활용하지 못하고 있습니다.
- 내부적으로는 동일한 vNet에 있는 VM들은 Private IP로 상호 통신이 가능합니다.
- 빠른 Private 네트워크를 사용하지 못해서 아깝습니다.
PR
- Public IP와 Private IP를 동시에 활용할 수 있도록 로컬 DNS 사용
- Private network 로 상호 연결 가능한 VM은 Private IP로 통신하고, 네트워크가 공유가 되지 않는 VM들에 대해서만 Public IP로 통신할 수 있도록 Name으로 이를 해석할 수 있도록 하였습니다. 
- 이를 위한 PoC로, /etc/hosts 를 업데이트하는 스크립트를 개발하였습니다.
- 이를 실행하면, MCIS 내부의 각 VM에 대해서 /etc/hosts 를 추가하게 됩니다. (아래 예시와 같이. 동적 업데이트는 아닙니다.)
```diff
cb-user@ip-192-168-2-241:~$ cat /etc/hosts
127.0.0.1 localhost
+ 127.0.0.1 gcp-as-east1-0
+ 192.168.2.241 aws-ap-se-1-1
+ 35.229.192.26 gcp-as-east1-1
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
``` …
> Add script for local DNS mapping for MCIS

- .github/workflows/build-amd64-container-image.yaml
- .github/workflows/publish-multi-arch-container-images.yaml
#797 이슈입니다.
docs/ 디렉토리 아래 파일들을 업데이트시 별도의 빌드테스트 X, 컨테이너 이미지 업데이트 불필요하여
paths-ignore에 docs 디렉토리의 모든 하위폴더에 대해 무시하도록 경로 설정하였습니다.
이렇게 경로 설정된 파일은 2개입니다.
build-amd64-container-image.yaml
publish-multi-arch-container-images.yaml
> Add 'paths to ignore' to auto-build GitHub workflows

- src/core/mcis/remoteCommand.go
Disable checking port open for speedup SSH
/* Code to check endpoint and port connectivity. (disabled for better speed)
// CheckConnectivity func checks if given port is open and ready.
// retry: 5 times, sleep: 5 seconds. timeout for each Dial: 20 seconds
*/
> Disable checking port open for speedup SSH

- README.md
- i18n/README-EN.md
I have fixed typos in the inner links`(Line 301,302)` in README.md so it works as we desired.
Thank you
>  [#824] Fixed typos in the inner links in README.md

- .github/workflows/make-swagger.yaml
make swagger 를 자동으로 실행해 추가 커밋을 만드는 workflow를 추가하였습니다.
이 action은 core나 rest api쪽 코드에 변화가 있을 때에만 실행됩니다.
```yaml
paths:
- 'src/core/**/**.go'
- 'src/api/rest/server/**/**.go'
```
문서 디렉토리의 파일 중 추가된 것이 있으면 자동으로 커밋합니다. 커밋 메세지는 "Update Swagger Docs" 입니다.
```yaml
- name: Commit generated Swagger docs
uses: stefanzweifel/git-auto-commit-action@v4
with:
file_pattern: src/api/rest/docs/**
commit_message: Update Swagger docs
```
author는 원 커밋 저자로, committer는 'actions-user'로 기록됩니다.
> Add 'Update Swagger doc' workflow

- src/api/grpc/server/mcis/control.go
- src/api/rest/server/mcis/control.go
- src/core/mcis/benchmark.go
안녕하세요.
관련 이슈: #834
- src/core/mcis/benchmark.go 의 CoreGetAllBenchmark 함수명을 RunAllBenchmarks 로 수정했습니다.
- src/api/grpc/server/mcis/control.go, src/api/rest/server/mcis/control.go 에서 
함수 사용 중이어서 함수명을 RunAllBenchmarks 로 수정했습니다.
감사합니다!
> Rename CoreGetAllBenchmark function to RunAllBenchmarks

- .github/workflows/make-swagger.yaml
- .gitignore
- src/core/common/utility.go
Idea from @seokho-son 😊
- Swagger doc file들을 `.gitignore`에 추가하여,
기여자가 기여 시 Swagger doc file들을 신경쓰지 않아도 되도록 변경
- `.gitignore`에 Swagger doc file들이 들어가 있어서
["Update Swagger doc" workflow](https://github.com/cloud-barista/cb-tumblebug/blob/main/.github/workflows/make-swagger.yaml) 가 실행될 때 Swagger doc file들이 ignore 될 것 같으므로
`git add -f -v` 명령을 이용하여 강제로 추가
(이후, added but uncommitted change를 `peter-evans/create-pull-request` 가 잘 처리해 주리라 기대 😊)
> Add Swagger doc files to gitignore

- src/api/rest/server/mcis/control.go
- src/testclient/scripts/8.mcis/status-mcis.sh
- GET MCIS API 에서 Control 관련 액션 삭제
- GET MCIS API 에 status는 option 파라미터 사용으로 변경
> Remove control action parameters from get mcis

- src/api/rest/server/mcir/common.go
- src/core/mcir/common.go
- Enhance return body for loadCommonRes
- Expedite LoadCommonResource in parallel (goroutine)
LoadCommonResource can be done around 5~10 secs
5 secs are used for safe parallel executions.
```
// RandomSleep for safe parallel executions
common.RandomSleep(5)
```
> Expedite LoadCommonResource in parallel

- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/securitygroup.go
- src/api/rest/server/mcir/sshkey.go
- src/api/rest/server/mcir/subnet.go
- src/api/rest/server/mcir/vnet.go
- src/testclient/scripts/1.configureSpider/register-cloud-interactive.sh
- src/testclient/scripts/testSet.env
- Provide total number of clouds to automate registration of connectionConfig
- minor: Set default NS example for mcir API
Example
cb-tumblebug/src/testclient/scripts/1.configureSpider$ .**/register-cloud-interactive.sh -n shson**
```
[Configuration in  ../testSet.env &  ../conf.env  files]
1) System Endpoints
- Tumblebug Server :  localhost:1323 
- Spider Server :  localhost:1024 
2) Enabled Clouds and Regions
- [1] Cloud : testcloud01 (enabled regions : 1)
[1,1] Region : testcloud01-seoul (Korea (Seoul)) 
- [2] Cloud : testcloud02 (enabled regions : 1)
[2,1] Region : testcloud02-canada (Canada (Central)) 
- [3] Cloud : testcloud03 (enabled regions : …
```
> Provide total number of clouds to automate registration of connectionConfig

- .gitignore
- README.md
- conf/template.credentials.conf
- scripts/generateCredencialFile.sh
- scripts/registerCloudInfo.sh
- src/api/grpc/cbadm/testclient/scripts/1.configureSpider/get-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/1.configureSpider/list-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/1.configureSpider/register-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/1.configureSpider/unregister-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/misc/get-conn-config.sh
- src/api/grpc/cbadm/testclient/scripts/misc/get-region.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/clean-mcir-ns-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/clean-mcis-only.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/create-mcir-ns-cloud.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/create-mcis-for-df.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/create-mcis-only.sh
- src/core/mcis/provisioning.go
- src/testclient/scripts/1.configureSpider/register-cloud-interactive.sh
- src/testclient/scripts/init.sh
- src/testclient/scripts/sequentialFullTest/create-mcis-for-df.sh
- src/testclient/scripts/sequentialFullTest/create-mcis-for-ws.sh
Fix #650
- 클라우드 연결 정보 등록 절차 (크리덴셜 및 리전 등) 를 **CB-TB 시스템 환경 설정**의 형태로 변경 
- 클라우드 크리덴셜 파일 기본 위치 변경 (conf/credential.conf)
- 스크립트를 통한 자동화
- 크리덴셜 기본 파일 생성 스크립트 추가
- 조사된 모든 리전 등록 스크립트 추가
- 리드미 업데이트
- 기타: .gitignore 보완
> Change workflow for Cloud connection info registration

- assets/cloudconnection.csv
- assets/cloudlocation.csv
- src/api/grpc/request/mcisapi.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcis/manageInfo.go
- src/core/mcis/provisioning.go
- src/core/mcis/recommendation.go
- src/testclient/scripts/conf.env
- src/testclient/scripts/misc/gen-csv-conn-config.sh
- src/testclient/scripts/misc/gen-csv-image.sh
- Requested by cb-webtool
- Return Geolocation for `get & list connectionConfig`
http://localhost:1323/tumblebug/connConfig
```
{
"connectionconfig": [
{
"ConfigName": "alibaba-ap-northeast-1",
"ProviderName": "ALIBABA",
"DriverName": "alibaba-driver01",
"CredentialName": "alibaba-credential01",
"RegionName": "alibaba-ap-northeast-1",
"Location": {
"latitude": "34.6895",
"longitude": "139.9917",
"briefAddr": "Japan (Tokyo)",
"cloudType": "alibaba",
"nativeRegion": "ap-northeast-1"
}
},
{
"ConfigName": "alibaba-ap-south-1",
"ProviderName": "ALIBABA",
"DriverName": "alibaba-driver01",
"CredentialName": "alibaba-credential01",
"RegionName": "alibaba-ap-south-1",
"Location": {
"latitude": "19.1761",
"longitude": "72.1774",
"briefAddr": "India (Mumbai)",
"cloudType": "alibaba",
"nativeRegion": …
```
> Add feature for connection with geolocation

- src/testclient/scripts/1.configureSpider/register-cloud-interactive.sh
- `register-cloud-interactive.sh` 에서 매 리젼 항목 마다, 중복으로 클라우드 드라이버 및 크리덴셜 등록하던 방식을 변경
> Prevent duplicated exec in register cloud script [skip ci]

- .gitignore
- assets/cloudlocation.csv
- conf/template.credentials.conf
- src/testclient/scripts/conf.env
- src/testclient/scripts/testSet.env
VM 생성 및 삭제까지 되는 것을 확인했습니다.
다만, VM terminate가 다른 CSP에 비해 오래 걸려서 (2~3분)
`clean-all.sh` 스크립트로 테스트 시
SSH key, SG, vNet 삭제에 실패합니다. (resources in use)
[Related]
- #910
- https://github.com/cloud-barista/cb-spider/issues/513
- https://github.com/cloud-barista/cb-spider/pull/514
- https://cloud-barista.slack.com/archives/CJQ7575PU/p1636090717074000
- https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1636088609079200
- https://cloud-barista.slack.com/archives/CJQ7575PU/p1636091079077200
- ...
> Add support for IBM-VPC

- scripts/initMultiCloudEnv.sh
- scripts/registerCloudInfo.sh
- src/testclient/scripts/2.configureTumblebug/create-ns.sh
- src/testclient/scripts/2.configureTumblebug/delete-ns.sh
- src/testclient/scripts/2.configureTumblebug/get-config.sh
- src/testclient/scripts/2.configureTumblebug/get-ns.sh
- src/testclient/scripts/2.configureTumblebug/load-common-resource.sh
scripts/initMultiCloudEnv.sh
만 실행하면, 
- Cloud 리전 및 크리덴셜 등록
- 공통 자원 (Image, Spec) 등록
- 기본 네임스페이스 (명칭: ns01) 등록
을 모두 수행합니다.
이를 수행하면, /ns/{nsId}/mcisDynamic 를 활용하여, MCIS를 바로 생성할 수 있습니다.
```
[Cloud Region]
RegionName                   ProviderName  Region                                    Zone
----------                   ------------  ------                                    ----
alibaba-ap-northeast-1       ALIBABA       ap-northeast-1                            ap-northeast-1a
alibaba-ap-south-1           ALIBABA       ap-south-1                                ap-south-1a
alibaba-ap-southeast-1       ALIBABA       ap-southeast-1 …
```
> Add one click init MC Env script

- src/api/grpc/server/mcir/image.go
- src/api/grpc/server/mcir/securitygroup.go
- src/api/grpc/server/mcir/spec.go
- src/api/grpc/server/mcir/sshkey.go
- src/api/grpc/server/mcir/vnet.go
- src/api/rest/server/mcir/common.go
- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/securitygroup.go
- src/api/rest/server/mcir/spec.go
- src/api/rest/server/mcir/sshkey.go
- src/api/rest/server/mcir/vnet.go
- src/api/rest/server/server.go
- src/core/common/common.go
- src/core/mcir/common.go
- src/core/mcis/provisioning.go
- substring match로 delete all mcis 에 대한 조건 지원
- default resources (sg, key, vnet) 을 순서에 맞추서 모두 삭제하는 기능 추가
- API 출력 결과를 항목별로 제공 
- idList JSON tag 를 output 으로 변경
`http://localhost:1323/tumblebug/ns/ns01/defaultResouces`
```
{
"ouput": [
"securityGroup: ns01-systemdefault-aws-ap-northeast-2  [DELETED]",
"sshKey: ns01-systemdefault-aws-ap-northeast-2  [DELETED]",
"vNet: ns01-systemdefault-aws-ap-northeast-2  [DELETED]"
]
}
```
> Add delete all default resource feature

- src/core/mcir/common.go
- check the resource is in use by associatedObjList (@jihoon-seo Thanks)
- if in use, don't request deletion to CSP
​/ns​/{nsId}​/defaultResouces (Delete all Default Resource Objects in the given namespace)
```
{
"ouput": [
"securityGroup: ns01-systemdefault-aws-ap-northeast-2  [FAILED] in use by [/ns/ns01/mcis/mcis01/vm/vm01-2, ]/ns/ns01/mcis/mcis01/vm/vm01-0, ]/ns/ns01/mcis/mcis01/vm/vm01-1",
"sshKey: ns01-systemdefault-aws-ap-northeast-2  [FAILED] in use by [/ns/ns01/mcis/mcis01/vm/vm01-2, ]/ns/ns01/mcis/mcis01/vm/vm01-0, ]/ns/ns01/mcis/mcis01/vm/vm01-1",
"vNet: ns01-systemdefault-aws-ap-northeast-2  [FAILED] in use by [/ns/ns01/mcis/mcis01/vm/vm01-2, ]/ns/ns01/mcis/mcis01/vm/vm01-0, ]/ns/ns01/mcis/mcis01/vm/vm01-1"
]
}
```
> Prevent deletion efforts for obj in use

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/common/common.go
- src/core/mcir/common.go
- src/testclient/scripts/3.vNet/delete-all-vNet.sh
- Resolves #945
- Related PR: #944
이 PR로 인해, `DelAllResources` 호출 시 다음과 같이 동작합니다.
1. `resourceType` (예: vNet) 에 대해 `resourceIdList` 추출
2. `resourceIdList` 의 각 `v` (예: `vnet-01`) 에 대해, 
3. `GetAssociatedObjectList` 조회하고, 
1. 없으면 `DelResource` 호출
1. `DelResource` 함수 안에서 `GetAssociatedObjectList` 조회
즉, `DelAllResources` 함수에서 `3. GetAssociatedObjectList 조회하고,` 와 
`a. DelResource 함수 안에서 GetAssociatedObjectList 조회` 가 중복입니다.
Optional: `DelAllResources` 함수에서 `3. GetAssociatedObjectList 조회하고,` 를 삭제할 수도 있겠습니다. 😊
> Prevent deletion of obj in use

- src/api/grpc/server/mcis/control.go
- src/api/rest/server/mcis/control.go
- src/core/mcir/image.go
- src/core/mcis/provisioning.go
- VM label 정보 누락 수정
- MCIS 프로비저닝 직후, 상태 정보 오류 수정
- CorePostMcisGroupVm 중복 함수 삭제
> Fix object information for MCIS provisioning

- assets/cloudlocation.csv
- src/testclient/scripts/conf.env
- src/testclient/scripts/testSet.env
For everyone's information:
https://github.com/cloud-barista/ktcloud/blob/main/ktcloud/main/config/config.yaml
> 주의 : KT Cloud CSP에서는 Region 단위가 없이 Zone 단위로 구분되어 서비스되나, 편의를 위해 Region 정보를 기입했음.
---
- 참고: KT Cloud는 Zone ID, Image ID, Spec ID 가 UUID 형태로 되어 있습니다.
- 모든 존의 Image ID가 `45e20478-6c24-4c32-a5e5-2ba2d464a8d1` 으로 동일한데,
- 'Seoul M2' 만 `63de6d04-7f1b-4924-8e95-1acd6581ca0c` 로 다릅니다.
- Spec ID 도 마찬가지 입니다.
- [안] 동일한 것들은 `CommonImage`, `CommonSpec` 으로 묶을 수도 있겠습니다.
- 이 PR에서 '김해' 존을 추가했는데, KT Cloud 에서는 'KOR-HA' 라는 이름으로 부르고 있습니다.
- 이전 PR에서 추가하지 않아 이 PR에서 새롭게 추가하는 것이기도 하고,
이름처럼 HA용으로 사용하는 것을 가정하고 있을까 하여
`conf.env` 에서 맨 마지막 순서로 넣었습니다.
- [안] 김해도 한국이므로, 다른 한국 존 직후에 오도록 US West 위쪽으로 순서를 바꿀 수도 있겠습니다.
[KT Cloud 웹 콘솔]
> Update KTcloud metadata [skip ci]

- src/core/mcir/common.go
```
Load common Specs and Images. Do you want to proceed ? (y/n) : y
{
"output": [
"image: alibaba-ap-northeast-1-ubuntu18-04",
"image: alibaba-ap-south-1-ubuntu18-04",
"image: alibaba-ap-southeast-1-ubuntu18-04",
"image: alibaba-ap-southeast-2-ubuntu18-04",
"image: alibaba-ap-southeast-3-ubuntu18-04",
"image: alibaba-ap-southeast-5-ubuntu18-04",
"image: alibaba-cn-beijing-ubuntu18-04",
"image: alibaba-cn-chengdu-ubuntu18-04  [Failed] {\"message\":\"Notfound: 'ubuntu_18_04_x64_20G_alibase_20210927.vhd' Images Not found\"}\n",
"image: alibaba-cn-guangzhou-ubuntu18-04",
"image: alibaba-cn-hangzhou-ubuntu18-04",
"image: alibaba-cn-heyuan-ubuntu18-04", …
```
> Append error message for load common resource

- src/api/rest/server/mcis/control.go
- src/core/mcis/control.go
- src/core/mcis/manageInfo.go
- src/core/mcis/provisioning.go
fix #948
```
DELETE "http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01?option=terminate"
```
> Add option=terminate for delete mcis

- go.mod
- go.sum
- scripts/runSpider.sh
- scripts/setcbsp.sh
- src/api/grpc/cbadm/testclient/scripts/9.monitoring/install-agent.sh
- src/api/grpc/cbadm/testclient/scripts/sequentialFullTest/command-mcis.sh
- src/core/mcir/common.go
- src/testclient/scripts/9.monitoring/install-agent.sh
- src/testclient/scripts/sequentialFullTest/change-mcis-hostname.sh
- src/testclient/scripts/sequentialFullTest/command-mcis.sh
- src/testclient/scripts/sequentialFullTest/config-hybridIP-withHosts.sh
- src/testclient/scripts/sequentialFullTest/gen-sshKey.sh
1. 
- Expedite config-hybridIP script
- Expedite gen sshkey script
- Avoid using 3rd ip retrieving service in scripts
2.
- Update CB-Spider version to v0.4.18
3.
- Increase random sleep duration for safe api call
> Expedite scripts by applying parallel execution with minor changes

- src/core/mcis/manageInfo.go
- src/core/mcis/provisioning.go
- VM 오브젝트 리스트와 VM 상태 오브젝트 리스트 간 순서의 미스매치로 인한 오류 수정
- 각자 소팅을 적용하고, 동일한 VM ID인 경우에만 값을 대입하도록 보완 
- 다소 계산량이 추가(ID가 동일한지 확인)되지만, 안정성 향상
- 향후 계산량은 개선 필요
> Hot fix vm status list mismatch bug

- src/core/mcir/image.go
- src/core/mcir/securitygroup.go
- src/core/mcir/spec.go
- src/core/mcir/sshkey.go
- src/core/mcir/vnet.go
- src/core/mcis/monitoring.go
- src/core/mcis/provisioning.go
- src/core/mcis/remoteCommand.go
- error 메시지 태그를 `NotObeyingNamingConvention`에서 err.Error()로 변경했습니다.
fix #950
> Fix error message tag for validation from 'NotObeyingNamingConvention' to err.Error()

- CHANGELOG.md
`v0.3.0` 의 태그명은 `v0.3.0-espresso` 가 맞는데,
`v0.4.0` 부터는 태그명도 `v0.4.0` 라서
이를 Changelog에 반영하였으며
그 외에도 마크다운을 약간 업데이트 하였습니다. 😊
> Tidy markdown documents

- src/testclient/scripts/sequentialFullTest/deploy-fps-game.sh
Add script to deploy FPS Game Xonotic server to MC-Infra.
What is Xonotic.
https://xonotic.org/
How to use (example)
```bash
./create-all.sh -n shson2 -f ../testSet01.env
./deploy-fps-game.sh -n shson2 -f ../testSet01.env
```
```
shson@dev:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/sequentialFullTest$ ./deploy-fps-game.sh -n shson2 -f ../testSet01.env 
MASTERIP: 13.213.58.171
Installing Xonotic to MCIS...
...
[DATE: 22/12/2021 03:50:48] [ElapsedTime: 100s (1m:40s)] [Command: ./deploy-fps-game.sh all 1 shson2 ../testSet01.env]
[MCIS Xonotic: complete] Access to
13.213.58.171:26000
```
To access the game server,
- download …
> Add usecase for FPS Game Xonotic

- src/api/grpc/server/mcir/securitygroup.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcir/securitygroup.go
- src/core/mcir/common.go
- src/core/mcir/securitygroup.go
- https://github.com/cloud-barista/cb-tumblebug/pull/990#pullrequestreview-821924918 에서 제안된 대로,
별도로 추가했던 `RegisterSecurityGroup` 함수를
`CreateSecurityGroup` 에 통합했습니다.
- 다만, https://github.com/cloud-barista/cb-tumblebug/pull/990#issuecomment-986435758 의 내용대로
'firewallRules 필드에 임의의 기본값을 넣고 struct validate' 하려고 했으나
`*u.FirewallRules = append(*u.FirewallRules, mockFirewallRule)` 부분에서 Internal Server Error 가 발생하여
- TB 코드 중에 `*returnResult = append(*returnResult, sshResultTmp)` 와 같은 코드가 있는데..
왜 여기서는 안되는걸까요.. ㅠㅠ
- 다음과 같이 하였습니다.
- `TbSecurityGroupReq` struct의 `FirewallRules` 필드의 `required` 태그 해제
- 대신, `option != "register"` 이면 `FirewallRules` 필드에 대해 따로 `required` validate 수행
> Update 'registerExistingSG' function

- src/api/grpc/server/mcir/sshkey.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcir/sshkey.go
- src/core/mcir/common.go
- src/core/mcir/sshkey.go
- src/testclient/scripts/5.sshKey/spider-get-sshKey.sh
- src/testclient/scripts/5.sshKey/test-register-sshKey.sh
앞선
- #983
- #990
에서는
`option=register` 이면 Spider 에 Get 하고 그 결과를 이용하여 TB object를 생성했지만,
SSH Key는 Spider에 Get 해도 Spider가 Private key 등을 리턴하지 않기 때문에
사용자가 TB에 registerExistingSSHKey 할 때 모든 정보를 제공하도록 하였습니다.
---
[특이사항]
- 사용자가 TB에 registerExistingSSHKey 할 때 SSH Key 정보를 제공할 수 있도록, `TbSshKeyReq` struct에 field 추가
(사용자가 모든 필드를 채워야 하는 것은 아니며, 일부만 채워도 되지만, 
register 시 `Username` 과 `PrivateKey` 는 필수 필드로 지정했음)
- `CspSshKeyName`
- `Fingerprint`
- `Username`
- `VerifiedUsername`
- `PublicKey`
- `PrivateKey`
---
기존의 "Create SSH Key"
[Request]
```JSON
{ 
"connectionName": "'${CONN_CONFIG[$INDEX,$REGION]}'", 
"name": "'${CONN_CONFIG[$INDEX,$REGION]}'-'${POSTFIX}'", 
"username": "ubuntu"
}
```
[Response]
```JSON
{
"id": "aws-ap-southeast-1-sjhtest",
"name": "aws-ap-southeast-1-sjhtest",
"connectionName": …
```
> Add `registerExistingSSHKey` feature

- .github/workflows/auto-merge.yml
- .github/workflows/build-amd64-container-image.yaml
- .github/workflows/make-swagger.yaml
- .github/workflows/prow-commands.yml
- .github/workflows/publish-multi-arch-container-images.yaml
- Resolves #1028
- Resolves https://github.com/cloud-barista/cb-tumblebug/pull/1027#issuecomment-1033268569
- Closes #1027
> Unspecify GitHub Actions' versions

- src/testclient/scripts/sequentialFullTest/change-mcis-hostname.sh
- src/testclient/scripts/sequentialFullTest/conf-ansible-env.sh
- src/testclient/scripts/sequentialFullTest/copy-file-to-mcis.sh
1) Add script for remote copy file to MCIS VMs (src/testclient/scripts/sequentialFullTest/copy-file-to-mcis.sh)
- How to use: Copy a local file to all VMs in the MCIS (-x source-file-path / -y destination-file-path)
- Ex) `./copy-file-to-mcis.sh` -n mcis02 -f ../testSet-kubespray.env -x `./sshkey-tmp/aws-ap-southeast-1-mcis02.pem` -y `/home/cb-user/`
---
2) Minor updates for scripts
> Add script for remote copy file to MCIS VMs

- README.md
- i18n/README-EN.md
- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/main.go
- Update Swagger serving URL
- Remove `/tumblebug/swaggerActive` REST API
- Remove `@host` option from Swagger conf
['Update Swagger doc' workflow](https://github.com/cloud-barista/cb-tumblebug/actions/workflows/make-swagger.yaml)가 잘 되는지 확인하기 위해, Swagger doc 을 일부러 업데이트하지 않았습니다. 😊
> Update Swagger serving URL

- src/api/grpc/server/server.go
- src/api/rest/server/server.go
- src/testclient/scripts/sequentialFullTest/command-mcis.sh
- major: [Align shutdown message](https://github.com/cloud-barista/cb-tumblebug/commit/bd76869e15bf55c3392ff0b5a55401e8358a776d)
- minor : [Update command-mcis script output](https://github.com/cloud-barista/cb-tumblebug/commit/f5a22ead3f068d3259e742cec5b7e5ad0a864907)
> Align shutdown message

- src/api/grpc/server/mcis/control.go
- src/api/rest/server/mcis/provisioning.go
- src/api/rest/server/server.go
- src/core/mcis/provisioning.go
MCIS 생성과 유사한 형태로 CSP 기존 VM을 등록합니다.
VM 등록을 요청할 때,
MCIS 명칭을 입력하게 되고, 해당 명칭이 없는 경우 신규 MCIS를 생성하게 되어 있습니다. 
(동일 명칭의 MCIS가 기존에 있는 경우, 기존 MCIS에 추가하도록 만들어 두었으나, 정상 동작 여부의 검증은 필요)
MCIS 프로비저닝 플로우에 관련된 코드들을 함께 사용하고, 
option=register 인 경우 create에서 필요한 절차들을 생략하는 형태로 코드를 구성하였습니다.
사용 방법은 아래와 같습니다.
우선, VM에 관련된 자원(vNet, SG, SSHKEY)이 미리 등록되어 있어야 합니다. (향후 개선 방안 마련 필요)
그리고 아래 API를 통해서 VM을 등록하면 됩니다.
POST ​/ns​/{nsId}​/registerCspVm
request body는 MCIS create와 거의 유사하며,
`name`, vm.`connectionName`, vm.`idByCsp`, vm.`name` 은 필수로 지정해야 하고, vmgroup 항목은 제외하여야 합니다.
나머지는 임의의 값을 넣어도 동작합니다.
요청 예시
```
{
"description": "Made in CB-TB",
"installMonAgent": "no",
"label": "custom tag",
"name": "mcis-test",
"vm": [
{
"connectionName": "aws-ap-southeast-1",
"description": "Description",
"idByCsp": "i-095afa0a0b8525fa6", …
```
> Initial codes to register existing CSP VM

- src/core/mcir/securitygroup.go
- src/core/mcir/vnet.go
- src/core/mcis/provisioning.go
> Update to prepend NS prefix to SG name

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/mcis/provisioning.go
- src/testclient/scripts/8.mcis/create-mcis.sh
- src/testclient/scripts/8.mcis/create-single-vm-mcis.sh
[Related links]
- https://github.com/cloud-barista/cb-spider/issues/348
- https://github.com/cloud-barista/cb-spider/blob/master/api-runtime/rest-runtime/test/each-test/vm-rootdisk-test.sh
- Resolves #960
[사용 방법]
MCIS/VM 생성 시, VM 명세에 다음과 같이 명시
```JSON
"rootDiskType": "",
"rootDiskSize": "77"
```
[테스트 결과]
AWS 에 대해
TB -> SP 통해서 VM 만들 때
`RootDiskSize` 를 명시하면 적용이 되는 것은 확인했습니다.
(참고: https://github.com/cloud-barista/cb-spider/issues/531 )
> Add RootDiskType, RootDiskSize handling feature

- src/core/mcis/provisioning.go
- src/testclient/scripts/3.vNet/spider-delete-vNet.sh
- src/testclient/scripts/3.vNet/spider-get-vNet.sh
- src/testclient/scripts/4.securityGroup/spider-delete-securityGroup.sh
- src/testclient/scripts/4.securityGroup/spider-get-securityGroup.sh
- src/testclient/scripts/5.sshKey/spider-delete-sshKey.sh
- src/testclient/scripts/conf.env
Closes #1051
TB가 SP에 VM 생성을 요청할 때
SG 칸에는 'Spider가 관리하는 SG name' 을 적어야 하는데
이 값은 TB SG object의 `cspSecurityGroupName` 필드에 있습니다.
이 필드의 값을 활용하도록 수정하는 PR입니다.
AWS는 VM 생성 되는 것을 확인했고,
Alibaba에서는 기존에 발생하던 `[aws-ap-southeast-1:aws-ap-southeast-1-jhseo:aws-ap-southeast-1-jhseo]` 와 같은 에러는 발생하지 않는 것을 확인했습니다.
(다만, 다른 에러인 `The resource in the specified zone is no longer available for sale. Please try other regions and zones.` 에러가 발생하여 VM 생성까지는 가지 못했음) (https://github.com/cloud-barista/cb-tumblebug/pull/974#issuecomment-1080115907)
> Fix bug on NS prefix of SG name

- go.mod
- go.sum
- Upgrade cb-larva package from v0.0.10 to v0.0.13 by
```
go get -u github.com/cloud-barista/cb-larva 
```
Issue reference: https://cloud-barista.slack.com/archives/CJQ7575PU/p1650330154118099
```bash
ubuntu@DESKTOP-L3ETGKI:/mnt/d/Dev/Cloud-Barista/cb-tumblebug$ sudo docker build -t ltb .
[+] Building 21.9s (20/20) FINISHED
=> [internal] load build definition from Dockerfile                                                                                       0.0s 
=> => transferring dockerfile: 38B                                                                                                        0.0s 
=> [internal] load .dockerignore                                                                                                          0.0s 
=> => transferring context: 2B …
```
> Hotfix cb-larva package

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/mcir/securitygroup.go
- src/core/mcis/utility.go
Foundation for #1055
POST ​`/registerCspResources` 
> Register CSP Native Resources (vNet, securityGroup, sshKey, vm) to CB-Tumblebug
Request body ex
> {
>   "connectionName": "aws-ap-northeast-2",
>   "mcisName": "mcis-csp-native",
>   "nsId": "ns01"
> }
해당 클라우드 리전에 포함된 리소스를
vNet -> SG -> SSHKey -> VM 순서로 CB-TB의 오브젝트로 등록시킴.
[보완 필요 부분]
- API return body 구조 개선
- 자원간 연관관계 및 자원 정보 재구축 필요 (일부 가능한 항목만)
- SG 등록 관련 임의의 값 임시 지정한 항목 개선 필요 (https://github.com/cloud-barista/cb-tumblebug/issues/1055#issuecomment-1112540552)
- 모든 connectionConfig 를 기준으로 등록하는 스크립트 추가 (아마도 기능으로 개발할 필요는 없을 듯..)
> Register all CSP resources to CB-TB objs

- src/api/rest/server/common/utility.go
- src/core/mcir/securitygroup.go
- src/core/mcis/utility.go
idByTb, idBySp, idByCsp, refNameOrId 등으로 id 표기 명확화.
[요청]
POST ​/inspectResources
(Inspect Resources (vNet, securityGroup, sshKey, vm) registered in CB-Tumblebug, CB-Spider, CSP)
```
{
"connectionName": "aws-ap-southeast-1",
"resourceType": "vNet"
}
```
[출력] 등록된 리로스 아이디 리스트 (등록 실패한 리소스가 있는 경우, 해당 항목의 스트링에 실패 메시지가 포함)
```
{
"connectionName": "aws-ap-southeast-1",
"resourceType": "vNet",
"resourcesOnTumblebug": [
{
"idByTb": "aws-ap-southeast-1-shson",
"idByCsp": "vpc-0a3291546ba7bc123",
"nsId": "ns01",
"objectKey": "/ns/ns01/resources/vNet/aws-ap-southeast-1-shson"
}
],
"resourcesOnSpider": [
{
"idBySp": "ns01-aws-ap-southeast-1-shson",
"idByCsp": "vpc-0a3291546ba7bc123"
}
],
"resourcesOnCsp": [
{
"idByCsp": "vpc-0a3291546ba7bc123",
"refNameOrId": …
```
> Change struct for inspectResources and registerCspResources with Err fix

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/mcis/utility.go
1. inspect resources 에 대략적인 리소스 현황을 표시
POST ​/inspectResources
Inspect Resources (vNet, securityGroup, sshKey, vm) registered in CB-Tumblebug, CB-Spider, CSP
```
{
"connectionName": "aws-ap-southeast-1",
"resourceType": "vm",
"resourceOverview": {
"onTumblebug": 0,
"onSpider": 0,
"onCspTotal": 3,
"onCspOnly": 3
},
"resources": {
"onTumblebug": {
"count": 0,
"info": null
},
"onSpider": {
"count": 0,
"info": null
},
"onCspTotal": {
"count": 3,
"info": [
{
"idByCsp": "i-014fa6ede6ada0b2c",
"refNameOrId": "kimy-etcd-host-aws"
},
{
"idByCsp": "i-0c2d783dd905dd372",
"refNameOrId": "kimy-agent-ubuntu"
},
{
"idByCsp": "i-06ea9ba67b3bcff93",
"refNameOrId": "kimy-agent-centos"
}
]
},
"onCspOnly": {
"count": 3,
"info": [
{
"idByCsp": "i-014fa6ede6ada0b2c",
"refNameOrId": …
```
> Add overview to inspect resources and registerCspResources for all connectionConfigs

- src/core/mcir/securitygroup.go
- src/core/mcis/utility.go
모든 CSP 자원 등록시, GCP의 자원 등록(VPC)이 병행되면, 
소요시간이 지나치게 늘어나는 것을 확인하였음. (전체 1시간 이상)
제외하면 약 10분 정도로 완료 가능.
해결 방안 파악될 때까지 잠시 GCP 항목을 제외한 임시 내용임.
> Temporal removal of GCP from RegisterCspResAll and hotfix

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/mcis/utility.go
**GET  ​/inspectResourcesOverview**
Inspect Resources Overview (vNet, securityGroup, sshKey, vm) registered in CB-Tumblebug and CSP for all connections
Response body
```
{
"elapsedTime": 81,
"registeredConnection": 152,
"availableConnection": 97,
"tumblebugOverview": {
"vNet": 696,
"securityGroup": 1118,
"sshKey": 231,
"vm": 20
},
"cspTotalOverview": {
"vNet": 696,
"securityGroup": 1118,
"sshKey": 240,
"vm": 24
},
"inspectResult": [
{
"connectionName": "alibaba-ap-northeast-1",
"elapsedTime": 7,
"tumblebugOverview": {
"vNet": 9,
"securityGroup": 7,
"sshKey": 10,
"vm": 0
},
"cspTotalOverview": {
"vNet": 9,
"securityGroup": 7,
"sshKey": 10,
"vm": 0
}
},
{
"connectionName": "alibaba-ap-south-1",
"elapsedTime": 12,
"tumblebugOverview": {
"vNet": 10, …
```
> Add feat for Inspect Resources Overview

- src/core/mcis/utility.go
CSP 리소스 조회시 rateLimitExceeded 가 발생하는 경우가 빈번하여, (rateLimiting: https://github.com/cloud-barista/cb-tumblebug/discussions/1081)
재시도 로직을 추가함.
- rateLimitMessage := "limit" //limit이 포함된 에러가 있는 경우
- maxTrials := 5 // 최대 5회 재수행
- common.RandomSleep(40, 80) // 수행당 40~80초 사이의 값으로 지연 수행
> 관련 애러: [CLOUD-BARISTA].[ERROR]: 2022-05-07 16:01:43 utility.go:628, github.com/cloud-barista/cb-tumblebug/src/core/mcis.InspectResourcesOverview.func1() - {"message":"googleapi: Error 403: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'compute.googleapis.com' for consumer 'project_number:'., rateLimitExceeded"}
> Trials for inspectResourcesOverview to prevent rateLimitExceeded from CSP

- src/core/common/utility.go
- src/core/mcis/utility.go
다음과 같이, registerationOverview 제공
```
{
"elapsedTime": 286,
"registeredConnection": 152,
"availableConnection": 132,
"registerationOverview": {
"vNet": 1,
"securityGroup": 0,
"sshKey": 0,
"vm": 0,
"failed": 28
},
"registerationResult": [
{
"connectionName": "alibaba-ap-northeast-1",
"elapsedTime": 104,
"registerationOverview": {
"vNet": 0,
```
참고: 발견된 문제
```
{
"connectionName": "aws-ap-northeast-2",
"elapsedTime": 34,
"registerationOverview": {
"vNet": 0,
"securityGroup": 0,
"sshKey": 0,
"vm": 0,
"failed": 2
},
"registerationOutputs": {
"output": [
"sshKey: aws-ap-northeast-2-eksctl-my-cluster-nodegroup-ng-82857a41-c2-bb-8e-22-cb-89-d7-6b-04-c2-80-c4-82-e2-35-a3  [Failed] The sshKey aws-ap-northeast-2-eksctl-my-cluster-nodegroup-ng-82857a41-c2-bb-8e …
```
> Enhance RegisterCspNativeResourcesAll usability

- src/core/common/utility.go
- src/core/mcir/securitygroup.go
To resolve following panic,
from RegisterCspNativeResourcesAll
```
panic: interface conversion: interface {} is nil, not []mcir.TbVNetInfo
goroutine 4037 [running]:
github.com/cloud-barista/cb-tumblebug/src/core/mcir.CreateSecurityGroup(0xc001fe03dc, 0x4, 0xc0020d2d80, 0x15e4e30, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcir/securitygroup.go:200 +0x3059
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RegisterCspNativeResources(0xc001fe03dc, 0x4, 0xc0032fe9d0, 0xc, 0xc002effc00, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
/home/son/go/src/github.com/cloud-barista/cb-tumblebug/src/core/mcis/utility.go:849 +0xc75
github.com/cloud-barista/cb-tumblebug/src/core/mcis.RegisterCspNativeResourcesAll.func1(0xc00331ff40, 0xc001fe03d8, 0x3, 0x0, 0x0, …
```
> Hotfix for runtime err in RegisterCspNativeRes

- go.mod
- go.sum
- src/api/rest/server/mcis/network.go
- src/api/rest/server/server.go
- src/core/mcis/network.go
cb-network APIs 변경사항을 반영하고, CB-Tumblebug에 신규 API를 추가하는 PR 입니다.
신규 API는 Cloud Adaptive Network에 클라우드 정보를 주입하기 위한 API 입니다.
Note - 클라우드 정보는 CB-Tumblebug TbVmInfo 객체의 CloudType, Region, Zone, VpcIID.SystemId, SubnetIID.SystemId를 활용 합니다.
변경사항 요약은 아래와 같습니다 ^^
- Upgrade the cb-network packages to v0.0.14
- Add a new API to inject cloud information for Cloud Adaptive Network
- Add handler functions for the new API
- Update to align with the cb-network v0.0.14 APIs
> Add and update cb-network APIs

- src/api/rest/server/mcir/common.go
- src/core/mcir/common.go
- src/core/mcir/securitygroup.go
- src/core/mcis/utility.go
- src/testclient/scripts/conf.env
Closes #1099
@seokho-son #1104 에서 제안해 주신 대로
`ListResource()` 함수를
'호출에는 문제가 없었으나 결과가 0개인 경우'
nil interface를 return하는 것이 아니라
길이 0인 `[]Tb***Info` slice를 return하는 것으로 변경하였습니다.
이에 따라, `ListResource()` 함수의 references 중에서
`resourceList == nil` 코드로 item 개수가 0인지 확인하는 부분이 있던 경우
'적절한 type으로 assertion 후 해당 slice의 len이 0인지 체크' 하도록 코드를 변경했습니다. 😊
다음 2가지 REST API (및 각각에 대응되는 core 함수) 에 대해 테스트 했습니다.
- List vNet
- Inspect resources
> Enhance `ListResource()`

- src/api/grpc/request/test/test_api.go
> Fix unmatched info in grpc test code

- scripts/initMultiCloudEnv.sh
- src/testclient/scripts/2.configureTumblebug/create-ns.sh
- src/testclient/scripts/sequentialFullTest/create-mcir-ns-cloud.sh
- src/testclient/scripts/sequentialFullTest/create-mcis-for-df.sh
- src/testclient/scripts/sequentialFullTest/create-mcis-for-ws.sh
Fix #1085
Test
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/2.configureTumblebug$ ./create-ns.sh -x t01-ns-with-x
```
{
"id": "t01-ns-with-x",
"name": "t01-ns-with-x",
"description": "NameSpace for General Testing"
}
``` 
son@son:~/go/src/github.com/cloud-barista/cb-tumblebug/src/testclient/scripts/2.configureTumblebug$ ./create-ns.sh -f ../testSet.env -x t02-ns-with-f-x
```
{
"id": "t02-ns-with-f-x",
"name": "t02-ns-with-f-x",
"description": "NameSpace for General Testing"
}
``` …
> Fix create-ns.sh error (fix #1085)

- assets/cloudimage.csv
Fix 
`    "image: azure-norwaywestest-ubuntu18-04  [Failed] {\"message\":\"azure-norwaywestest: does not exist!\"}\n",`
> Fix region name typo (norwaywestest)

- assets/cloudconnection.csv
- assets/cloudimage.csv
- assets/cloudlocation.csv
- conf/template.credentials.conf
- src/testclient/scripts/conf.env
- src/testclient/scripts/testSet.env
- `create-all.sh` 및 `clean-all.sh` 테스트 스크립트로 각종 자원 + VM 생성/삭제 되는 것을 확인했습니다. 😊
- 현재 NCP-VPC 는 한국, 싱가폴 리전에서만 사용 가능한 것으로 보입니다.
https://console.ncloud.com/vpc-compute/server
---
[Memo]
https://github.com/cloud-barista/cb-tumblebug/pull/1111#discussion_r871959331
> assets/cloudconnection.csv 정보의 소스는 src/testclient/scripts/conf.env 이며,
> 
> src/testclient/scripts/misc/gen-csv-conn-config.sh 를 실행하면,
> src/testclient/scripts/conf.env 의 내용을 assets/cloudconnection.csv CSV 형태로 변환하여 파일을 생성해줍니다.
> Add support for NCP-VPC

- src/core/mcis/manageInfo.go
mcis 전체 상태를 표시 방식을 아래와 같이 변경하여 가독성 향상.
`현재 MCIS 대표 상태`:`관련된 VM수` (R:`러닝 상태 VM수`/`전체 VM수`)
> Enhance output for mcis status

- src/api/rest/server/common/namespace.go
- src/core/common/namespace.go
- src/core/mcis/control.go
```
curl -X 'PUT' \
'http://localhost:1323/tumblebug/ns/ns01' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"description": "user ns",
"name": "ns01"
}'
```
Response body
{
"id": "ns01",
"name": "ns01",
"description": "user ns"
}
> Add updating NS functionality

- src/core/mcis/provisioning.go
https://github.com/cloud-barista/cb-tumblebug/issues/1055#issuecomment-1114214203
pfix - 자원간 연관관계 및 자원 정보 재구축 필요 (일부 가능한 항목만)
- vNet, SSHKey 에 대해 진행
{
"id": "aws-ap-southeast-1-i-0ba32d5f4856e71e0",
"name": "aws-ap-southeast-1-i-0ba32d5f4856e71e0",
"idByCSP": "i-0ba32d5f4856e71e0",
"vmGroupId": "",
"location": {
"latitude": "1.3700",
"longitude": "103.8000",
"briefAddr": "Singapore",
"cloudType": "aws",
"nativeRegion": "ap-southeast-1"
},
"status": "Running",
"targetStatus": "None",
"targetAction": "None",
"monAgentStatus": "notInstalled",
"networkAgentStatus": "notInstalled",
"createdTime": "2022-06-13 21:36:35",
"label": "not defined",
"description": "Ref name: csp01-shson. CSP managed VM (registered to CB-TB)",
"region": {
"Region": "ap-southeast-1",
"Zone": …
>  Reconstuct resource IDs for a registered MCIS

- src/testclient/scripts/sequentialFullTest/test-mcis-dynamic-all.sh
공통 Spec으로 등록되어 있는 모든 Spec을 대상으로
MCIS를 자동 모드로 생성해주는 시험 스크립트. (대규모 MCIS 테스트)
- ./test-mcis-dynamic-all.sh -f ../testSet.env -x create
- y 옵션으로 vm 레플리카 수를 지정할 수 있음
- ./test-mcis-dynamic-all.sh -f ../testSet.env -x delete
- delete 는 terminate & delete 임
> Add script for test-mcis-dynamic-all

- src/api/rest/server/mcis/provisioning.go
- src/core/mcis/provisioning.go
- src/core/mcis/utility.go
- Fix https://goreportcard.com/report/github.com/cloud-barista/cb-tumblebug#misspell
> Fix misspell

- src/api/rest/server/server.go
Extend API rate limit from 1 to 2 in a sec
클라이언트 중에, API 테스트를 위한 preflight 처리를 하는 경우가 있어서
rate limit 완화.
> Extend API rate limit from 1 to 2 in a sec

- go.mod
- go.sum
- src/core/mcis/network.go
It's a minor update to Cloud Adaptive Network API.
- Temporarily add sleep, to assign IPs consecutively to VMs in a VMgroup
- Specify the version (v0.0.15) to deploy cb-network agents (may keep this version until the next release)
I think that this PR could be reflected in the CB-Tumblebug v0.6.0 release without the v0.5.x Pre-release 😃
> Update Cloud Adaptive Network API

- src/core/mcis/recommendation.go
Recommend VM Location 에서 동일 위치(리전)의 스팩들에는 우선순위가 없으므로
랜덤으로 우선순위가 지정되었으나, 
이를 가격으로 변경 개선함.
(동일한 위치인 경우, 낮은 가격을 제시한 스팩의 우선순위가 높아짐)
> Add cost priority for specs in same location

- .github/workflows/auto-merge.yml
- .github/workflows/build-amd64-container-image.yaml
- .github/workflows/make-swagger.yaml
- .github/workflows/prow-commands.yml
- .github/workflows/publish-multi-arch-container-images.yaml
Workflows의 구동 OS 및 Go 버전을 변경하였습니다.
- `ubuntu-18.04` to `ubuntu-latest`
- `1.17` to `1.19`
CB-Tumblebug은container image build를 통해 코드 필드 성공 여부를 테스트하고 있기 때문에 큰 이슈를 없을 것으로 생각합니다. (Cloud-Barista의 개발/테스트를 위한 공식 OS(Ubuntu 22.04)와도 관련이 낮습니다.)
`make-swagger.yaml`는 환경을 탈 것 같아 로컬에서 수행해봤는데요. 이슈는 없었습니다.  적용 후 이슈가 발생하면 대응하겠습니다 ^^
(참고)
Ref: [GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
> Update OS and Go in workflows

- src/testclient/scripts/8.mcis/id-list-vmgroup.sh
- src/testclient/scripts/conf.env
- src/testclient/scripts/testSet.env
- NHN Cloud: https://github.com/cloud-barista/cb-spider/pull/740
- NCP-VPC: https://github.com/cloud-barista/cb-spider/pull/768
---
- `8.mcis/id-list-vmgroup.sh`: ~#1178 에 포함시켰으면 좋았는데 그러지 못해~ 이 PR 올릴 때 추가했습니다. 😊
> Update NCP-VPC & NHN Cloud regions & zones

- src/api/grpc/server/mcis/control.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/provisioning.go
- src/api/rest/server/server.go
- src/core/mcis/provisioning.go
MCIS에 포함되어 있는 VMGroup을 기준으로, 
MCIS를 확장(Group에 포함된 VM 추가)하는 기능 제공
- 추가되는 VM은 지정된 Group에 포함되며, 병렬로 생성 및 추가.
- VM의 ID는 기존에 있는 VM들과 유사하게 포스트픽스 숫자 증가하는 형태로 구성됨(ID 중복 방지). (ex: group0-1, group0-2, ...)
curl -X 'POST' \
'http://localhost:1323/tumblebug/ns/ns01/mcis/mc-6oghb/vmgroup/group-0' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"vmGroupSize": "3"
}'
> Add scaleOut feature for VMGroup in a MCIS

- go.mod
- go.sum
Fix https://github.com/cloud-barista/cb-tumblebug/security/dependabot/3
to use github.com/labstack/echo/v4 v4.9.0
> Fix Echo vulnerability CVE-2022-40083

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/manageInfo.go
- src/core/mcis/manageInfo.go
- src/core/mcis/provisioning.go
CSP가 관리하는 VM의 오브젝트 ID 및 Name 을 리턴하는 옵션 추가
사용방법
curl -X 'GET' \
'http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01/vm/group-0-1?option=idsInDetail' \
-H 'accept: application/json'
Request URL
http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01/vm/group-0-1?option=idsInDetail
<h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: …
> Add get VM ID Name info in detail

- conf/cloud_conf.yaml
- src/core/common/config.go
- src/core/mcis/nlb.go
- src/main.go
- 개발 과정 중에 CSP에 따라서 다른 값을 지정해야 하는 경우가 발생하고 있음. (예를 들어, NLB를 생성하기 위해서는 CSP별로 특정 다른 값을 입력해야 하는 상태). 이는 다양한 CSP에 대한 디버깅 및 개발에 어려움을 줌.
- CSP 별로 별도의 값을 미리 정의하여, 자동으로 지정할 수 있도록 conf 파일로 설정하고자 함.
- 이를 통해, CSP 구분하지 않고 테스트 코드나 값의 수정없이, 테스트가 진행될 수 있도록 처리 필요.
yaml config 파일의 로드 및 갱신은
https://github.com/spf13/viper (MIT 라이선스) 를 활용하였으며, 이는 cobra 등에서 많이 활용되는 오픈소스이므로, 신뢰할 수 있음.
main에서 로드된 yaml 파일의 정보는
cb-tumblebug/src/core/common pkg에서 전역 변수에 바인딩하여, 전역에서 사용할 수 있도록 되어 있음.
NLB 코드에 적용 필요.
> Add yaml config feature to handle different available values for each cloud

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/control.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcis/control.go
- src/core/mcis/manageInfo.go
- src/core/mcis/provisioning.go
- src/core/mcis/snapshot.go
- src/testclient/scripts/8.mcis/add-vm-to-mcis.sh
- 기존에는 각 MCIR object의 `AssociatedObjectList`에 하나 이상의 VM이 기재되어 있으면 해당 MCIR 삭제를 차단했지만
이 PR에서는 모든 MCIR에 대해 해당 제한을 해제했습니다.
- `AssociatedObjectList`에 하나 이상의 VM이 기재되어 있는 MCIR을 삭제 시도 하면
삭제할 수 없는 자원의 경우 CB-Spider 또는 CSP 수준에서 에러를 반환할 것입니다.
- CB-Spider에는 `VMReq`, `VMInfo` struct에 `ImageType` 필드가 추가되었고, 여기에 `MyImage` 라고 명시하는 방식인데
이 PR에서는 CB-Tumblebug의 `VMReq`, `VMInfo` struct에 `ImageType` 필드를 추가하지 않았습니다.
추후에 이 필드가 있는 것이 더 좋겠다고 결정되면, 추가할 수도 있겠습니다.
- VM 생성 시, `imageId` 필드에
미리 생성해 둔 TB `customImage` 객체의 ID를 입력
- TB 내부적으로, 다음 순서로 시도
- 해당 NS의 TB customImage 조회 (← 이 PR에서 추가됨)
- 해당 NS의 TB image 조회
- SystemCommonNs 의 TB image 조회
- `CreateVm` 함수의 마지막 부분에서 'RegisterConsequentVolumes' 동작 수행
- VM snapshot으로 VM을 실행했을 때, 이로 인해 생성된 CSP 볼륨 자원을 TB dataDisk object로 등록
---
(`imageId` 필드에: 미리 생성해 둔 TB `customImage` 객체의 …
> Feat: StartVmWithSnapshot + RegisterConsequentVolumes

- src/core/common/config.go
- src/core/mcir/common.go
- src/core/mcis/nlb.go
- src/testclient/scripts/10.nlb/create-NLB.sh
This PR is a follow-up PR of #1188.
'Create NLB' 요청 시, HealthChecker의 Interval / Timeout / Threshold 필드에
`default` 또는 빈칸으로 명시하면
[`cb-tumblebug/conf/cloud_conf.yaml`](https://github.com/cloud-barista/cb-tumblebug/blob/main/conf/cloud_conf.yaml) 에 기재되어 있는 값을 적용
> Implement `cloud_conf.yaml` manifest handling feat. for NLB

- scripts/installDocker.sh
> Simplify docker install script

- src/api/grpc/server/mcis/control.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/manageInfo.go
- src/core/mcis/manageInfo.go
- MCIS 삭제 시, 내부에 연관된 NLB도 모두 삭제하도록 자원 정리 자동화.
- MCIS 삭제 결과에 대한 세부 정보 제공.
Request URL
```
http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01
```
Response body
```
{
"output": [
"VM: group-0-1 [Done]",
"VM: group-0-2 [Done]",
"VM: group-0-3 [Done]",
"vmGroup: group-0 [Done]",
"NLB: group-0 [Done]",
"MCIS: mcis01 [Done]"
]
}
```
> Remove associated NLBs with MCIS del

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/control.go
- src/api/rest/server/mcis/manageInfo.go
- src/api/rest/server/server.go
- src/core/mcis/manageInfo.go
- src/testclient/scripts/11.dataDisk/attach-dataDisk.sh
- src/testclient/scripts/11.dataDisk/available-dataDisk.sh
- src/testclient/scripts/11.dataDisk/detach-dataDisk.sh
특정 VM에 대해
'GetAvailableDataDisks' REST API를 실행하면
해당 VM의 connectionName을 읽고
TB dataDisk object들 중에서
1. connectionName 이 매치되는 것
2. 상태가 `Available` 인 것
들을 filter하여 그 ID 목록을 반환합니다.
[Request]
`./available-dataDisk.sh -n jhseo -c aws -r 1`
GET `http://$TumblebugServer/tumblebug/ns/$NSID/mcis/${MCISID}/vm/${VMID}?option=availableDataDisk`
[Response]
```json
{
"dataDisk": [
"aws-ap-southeast-1-jhseo"
]
}
```
> Add 'GetAvailableDataDisks' feature

- src/core/mcis/nlb.go
- MCIS 삭제시, 관련 모든 NLB 리소스를 삭제하는 기능이 최근 포함되었음.
- 모든 NLB 리소스 삭제시, NLB가 없는 경우 Error를 리턴하고 있었음.
- 이에 의해서 MCIS 가 삭제되지 않는 문제가 발생
해당 PR은 모든 NLB 리소스 삭제시, NLB가 없는 경우, Error를 리턴하지 않도록 처리하여,
MCIS가 정상적으로 삭제되도록 처리하는 hot fix 임.
> HotFix for delete mcis err due to nlb

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/manageInfo.go
- src/api/rest/server/mcis/provisioning.go
- src/api/rest/server/server.go
- src/core/mcis/nlb.go
- src/core/mcis/provisioning.go
- 기존의 MCIS에 단일 VM을 추가하던 방식을 삭제
- VM을 1개라도 생성하면, 해당 VM은 1개의 subGroup에 기본으로 소속됨
- MCIS에 VM을 추가하는 API는 1개로 단일화함  
- POST /ns/{nsId}/mcis/{mcisId}/vm
- subGroupSize에 따라서 동종의 VM이 생성
- 만약 해당 필드를 사용하지 않거나, 값이 0 이하인 경우에도, 이 값은 1로 자체 보정하여, VM이 subGroup에 속하도록 함.
```
{
"connectionName": "aws-ap-northeast-2",
"description": "Description",
"imageId": "aws-ap-northeast-2-ubuntu18-04",
"label": "no",
"name": "g2",
"rootDiskSize": "default",
"rootDiskType": "default",
"securityGroupIds": [
"ns01-systemdefault-aws-ap-northeast-2"
],
"specId": "aws-ap-northeast-2-t3a-nano",
"sshKeyId": "ns01-systemdefault-aws-ap-northeast-2",
"subGroupSize": "3",
"subnetId": "ns01-systemdefault-aws-ap-northeast-2",
"vNetId": "ns01-systemdefault-aws-ap-northeast-2"
}
```
VM 6개에서 9개로 추가
```
{
"connectionName": …
```
> Remove historic add VM way

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcir/customimage.go
아래 REST API 에 대한 dummy 함수 + Swagger godoc 을 추가하여, Swagger 페이지에 표시되도록 변경
- GET `/ns/{nsId}/resources/customImage/{customImageId}`
- GET `/ns/{nsId}/resources/customImage`
- DELETE `/ns/{nsId}/resources/customImage/{customImageId}`
- DELETE `/ns/{nsId}/resources/customImage`
- (참고: POST `/ns/{nsId}/resources/customImage` REST API는 `?option=register` 로만 호출 가능)
> Add Swagger godoc for CustomImage REST APIs

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/manageInfo.go
Based on user request : 
https://cloud-barista.slack.com/archives/CJQ7575PU/p1666154205390509
입력 예시
```
curl -X 'GET' \
'http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01?option=id&filterKey=connectionName&filterVal=aws-ap-northeast-2' \
-H 'accept: application/json'
```
<html>
<body>
Code | Details
-- | --
200 | Response body {   "output": [     "g1-1",     "g1-2"   ] }
</body>
</html>
```
curl -X 'GET' \
'http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01?option=id&filterKey=connectionName&filterVal=gcp-asia-northeast3' \
-H 'accept: application/json'
```
<html>
<body>
200 | Response body{   "output": [     "g2-1",     "g2-2",     "g2-3"   ] }
-- | --
</body>
</html>
참고: option을 id로 한 경우에만 필터링이 적용됩니다.
> Add vm (id) list filtering feature

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/manageInfo.go
- src/core/mcis/manageInfo.go
- http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01?option=accessinfo
(기본) 프라이빗 키 항목 삭제
```
{
"McisId": "mcis01",
"McisSubGroupAccessInfo": [
{
"SubGroupId": "g1",
"McisVmAccessInfo": [
{
"vmId": "g1-1",
"publicIP": "13.125.209.56",
"privateIP": "192.168.20.133",
"sshPort": "22"
},
{
"vmId": "g1-2",
"publicIP": "43.201.72.240",
"privateIP": "192.168.20.172",
"sshPort": "22"
}
]
},
{
"SubGroupId": "g2",
```
- http://localhost:1323/tumblebug/ns/ns01/mcis/mcis01?option=accessinfo&accessInfoOption=showSshKey
(accessInfoOption=showSshKey 요청시) 프라이빗 키 제공
```
{
"McisId": "mcis01",
"McisSubGroupAccessInfo": [
{
"SubGroupId": "g1",
"McisVmAccessInfo": [
{
"vmId": "g1-1",
"publicIP": "13.125.209.56",
"privateIP": "192.168.20.133",
"sshPort": "22",
"privateKey": "-----BEGIN RSA PRIVATE …
```
> Provide show or hide option for sshKey in access info

- scripts/nlb/addTargetNode.sh
- scripts/nlb/applyConfig.sh
- scripts/nlb/deployNlb.sh
- deployNlb: "wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/deployNlb.sh"
- addTargetNode: "wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/addTargetNode.sh"
- applyConfig: "wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/applyConfig.sh"
SW 기반의 NLB를 VM에 배포하고,
MCIS의 VM 들을 backend에 추가할 수 있는 커맨드용 스크립트
아래와 같은 형태로 구성 가능.
> Add scripts to command SW NLB-HAProxy

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/recommendation.go
- src/core/mcis/recommendation.go
Enable coordinateFair option for recommend by location
예시
```
{
"filter": {
"policy": [
{
"condition": [
{
"operand": "4",
"operator": "<="
}
],
"metric": "cpu"
}
]
},
"limit": "5",
"priority": {
"policy": [
{
"metric": "location",
"parameter": [
{
"key": "coordinateFair",
"val": [
"39.1848/128.2488", "34.0599/131.5093", "36.1672/139.7769"
]
}
],
"weight": "0.3"
}
]
}
}
```
39.1848 : 128.2488
34.0599 : 131.5093
36.1672 : 139.7769 
를 지정하면, 중심 포인트를 찾은 후, 해당 중심 포인트에서 가장 가까운 리전들을 제공
> Enable coordinateFair option for recommend by location

- src/api/grpc/server/mcis/monitor.go
- src/api/rest/server/mcis/monitoring.go
- src/core/mcis/monitoring.go
- src/core/mcis/provisioning.go
[현황 - CB-TB 측면]
- CB-Dragonfly에 POST http://localhost:9090/dragonfly/agent 요청을 날릴 때,
`service_type` 필드의 값을 `const DefaultSystemLabel string` = "Managed by CB-Tumblebug" 으로 채워서 보냈습니다.
- 사용자 → TB → DF 순서로 call 하도록 하면 사용자는 다음의 TB 에러 메시지를 보게 되는데, 디테일이 표시되지 않습니다.
```
[Calling DRAGONFLY] START
cb-tumblebug                 | VM:ns01/jhseo/aws-us-east-2, URL:http://cb-dragonfly:9090/dragonfly/agent, userName:cb-user, cspType:aws, service_type:Managed by CB-Tumblebug
cb-tumblebug                 | Called CB-DRAGONFLY API
cb-tumblebug                 | HTTP Status code: 400
cb-tumblebug                 | [CLOUD-BARISTA].[ERROR]: 2022-10-24 06:48:35 monitoring.go:255, github.com/cloud-barista/cb-tumblebug/src/core/mcis.CallMonitoringAsync() - HTTP Status: not in 200-399 
cb-tumblebug …
```
> Modify 'serviceType' value in InstallMonAgentReq

- src/testclient/scripts/sequentialFullTest/copy-file-to-mcis.sh
Add StrictHostKeyChecking=no for mcis file copy
원격 파일 카피시, 인터렉티브 메시지 창을 없애기 위한 옵션
> Add StrictHostKeyChecking=no for mcis file copy

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcir/dataDisk.go
- src/core/mcis/manageInfo.go
- src/testclient/scripts/11.dataDisk/available-dataDisk-id.sh
- GET `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/dataDisk` : available한 dataDisk들의 객체들을 반환
- GET `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/dataDisk?option=id` : available한 dataDisk들의 ID들을 반환
---
`❯ ./available-dataDisk.sh -n jhseo -c aws -r 1`
GET `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/dataDisk`
```json
{
"dataDisk": [
{
"id": "aws-ap-southeast-1-jhseo",
"name": "aws-ap-southeast-1-jhseo",
"connectionName": "aws-ap-southeast-1",
"diskType": "standard",
"diskSize": "77",
"cspDataDiskId": "vol-07e0329d4f1021203",
"cspDataDiskName": "ns01-aws-ap-southeast-1-jhseo",
"status": "Available",
"associatedObjectList": [],
"createdTime": "2022-10-31T05:48:00.016Z",
"keyValueList": [
{
"Key": "Encrypted",
"Value": "false"
},
{
"Key": "MultiAttachEnabled",
"Value": "false"
}
]
}
]
}
```
---
`❯ …
> Update `availableDataDisk` REST API

- docs/images/cb-tb-call-core-mcis.svg
- docs/images/cb-tb-call-rest-mcis.svg
- src/api/grpc/server/mcis/control.go
- src/core/mcis/orchestration.go
- src/core/mcis/provisioning.go
changed function name from CorePostMcisVm to CreateMcisVm
> Change func name `CorePostMcisVm` into `CreateMcisVm`

- src/testclient/scripts/1.configureSpider/register-cloud-interactive.sh
- 1.configureSpider/register-cloud-interactive.sh 에 cloudit 크리델셜 등록을 위한 추가 파라미터를 누락하는 오류를 개선
- 향후 더 많은 크리덴셜 key/value pair가 추가될 경우를 대비하여, 3개의 index를 추가함.
> Add more parameter index for register-cloud

- src/api/grpc/server/mcis/control.go
- src/api/grpc/server/mcis/orchestration.go
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/orchestration.go
- src/api/rest/server/mcis/remoteCommand.go
- src/core/mcis/benchmark.go
- src/core/mcis/orchestration.go
- src/core/mcis/provisioning.go
- src/core/mcis/recommendation.go
- src/core/mcis/remoteCommand.go
- MCIS 자동 제어 메커니즘 개선 (MCIS에 신규 subGroup을 자동으로 추가하는 글로벌 ScaleOut)
- MCIS 추천 방식 추가 (Random)
- MCIS의 subGroup 단위의 원격 커맨드 옵션 추가
- 등
- CB-Dragonfly 배포 및 CB-TB에 설정 필수
- MCIS 자동 제어 정책 등록 (rest api)
POST [​/ns​/{nsId}​/policy​/mcis​/{mcisId}](http://localhost:1323/tumblebug/swagger/index.html#/[Infra%20service]%20MCIS%20Auto%20control%20policy%20management%20(WIP)/post_ns__nsId__policy_mcis__mcisId_) Create MCIS Automation policy
Request body 예시
```
{
"description": "Description",
"policy": [
{
"autoAction": {
"actionType": "ScaleOut",
"placementAlgo": "random",
"postCommand": {
"command": "wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/setweb.sh -O ~/setweb.sh; chmod +x ~/setweb.sh; sudo ~/setweb.sh"
},
"vmDynamicReq": {
"commonImage": "ubuntu18.04",
"commonSpec": …
```
> Enhance orchestration mechanism with various features

- src/core/mcis/nlb.go
- `cloud_conf.yaml` 파일에서 각 CSP별 interval, timeout, threshold 값을 읽어 적용하는 기능
- 기존: `cb-tumblebug/src/core/common/config.go` 파일의 `Cloud` struct에 정의해 놓지 않은 CSP (예: `NCPVPC`) 에 대해서는
`cloud_conf.yaml` 파일에 값을 기재하더라도
`src/core/mcis/nlb.go` 파일의 L382 에서 panic error 가 발생함
- 개선: 원하는 CSP를 `cb-tumblebug/src/core/common/config.go` 파일의 `Cloud` struct에 정의해 놓지 않아
(L382 →) L394 에서 panic error 가 발생하면
`cloud_conf.yaml` 파일의 `common` 필드에 기재되어 있는 값을 사용하도록 함 (L390)
- NLB Health를 조회하는 기능
- 기존: Spider의 응답인 `tempSpiderNLBHealthInfo.Healthinfo.HealthyVMs` 또는 `tempSpiderNLBHealthInfo.Healthinfo.UnHealthyVMs` 가 nil 이면
기존 L1175 또는 L1184 에서 nil (null? 😅) pointer error 발생
- 개선: `tempSpiderNLBHealthInfo.Healthinfo.HealthyVMs` 및 `tempSpiderNLBHealthInfo.Healthinfo.UnHealthyVMs` 가 nil 이 아닐 때에만
그 값을 읽도록 함
---
[오늘자 테스트 현황]
- …
> Fix bugs on NLB mgmt feature

- src/core/mcis/benchmark.go
res가 nil 인 경우에도 참조하는 오류 수정.
body, err := ioutil.ReadAll(res.Body)
> Fix nil reference error

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/provisioning.go
- src/api/rest/server/server.go
- src/core/mcis/provisioning.go
- src/core/mcis/recommendation.go
- 전 지역에 1개의 network probe를 생성하는 시스템용 MCIS 생성 기능.
- 각 CSP의 지역별 네트워크 응답 속도 (latency) 측정 용도 (admin 입장에서만 사용)
- provider (ex: "operand": "gcp"), 
- region (ex: "operand": "eu-central"), 
- specname (ex: "operand": "large") 
등 문자열 일치 조건으로 추천
참고: https://github.com/cloud-barista/cb-tumblebug/discussions/1234
> Add CreateSystemMcisDynamic for network probe

- scripts/cleanDB.sh
- scripts/runSpider.sh
- src/core/mcis/benchmark.go
- src/core/mcis/provisioning.go
- latency map 생성시, 일부 정상 동작하지 않아서 빈 라인으로 남아 있는 항목을, 행렬을 전치하여 채워 넣도록 처리
- Spider 0.6.14 버전 확인 및 스크립트 업데이트
> Enhance latency map creation

- scripts/usecases/jitsi/startServer.sh
- scripts/usecases/jitsi/statusServer.sh
- scripts/usecases/jitsi/stopServer.sh
- 기존 cb-tumblebug/src/testclient/scripts/sequentialFullTest 의 CB-TB 전용 Jitsi 스크립트를 일반화
- 최신 버전 설치 오류 수정
- ubuntu 22.04 에서만 지원
참고: 
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
https://www.digitalocean.com/community/tutorials/how-to-install-jitsi-meet-on-ubuntu-22-04
> Add Jitsi video conference script (for Ubuntu 22.04)

- conf/setup.env
- src/api/rest/server/server.go
Set CORS ALLOW_ORIGINS as ENV
```
>  # API Setting
>  # ALLOW_ORIGINS (ex: https://cloud-barista.org,xxx.xxx.xxx.xxx,*)
```
```
allowedOrigins := os.Getenv("ALLOW_ORIGINS")
if allowedOrigins == "" {
log.Fatal("ALLOW_ORIGINS env variable for CORS is " + allowedOrigins +
". Please provide a proper value and source setup.env again. EXITING...")
// allowedOrigins = "*"
}
e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
AllowOrigins: []string{allowedOrigins},
AllowMethods: []string{http.MethodGet, http.MethodPut, http.MethodPost, http.MethodDelete},
}))
```
> Set CORS ALLOW_ORIGINS as ENV

- Dockerfile
- conf/setup.env
- src/api/rest/server/server.go
chore: fix variable names and enhance ENV example guide
> chore: fix variable names and enhance ENV example guide

- src/core/common/client.go
- src/core/common/utility.go
Modularize http call client. (with an example)
Need to be applied to all codes that include http call to endpoints.
> Modularize http call client

- src/core/common/client.go
- src/core/common/utility.go
- 시스템에서 외부 서비스로 API call 을 수행하는 경우, 동일 uri 결과를 캐싱하는 기능 추가 (서버 안정성 +)
- (참고) Generic Type 활용. Golang 1.18 이상 요구사항.
> Add prototype of API Response Caching

- src/core/common/client.go
- src/core/common/utility.go
- src/core/mcis/manageInfo.go
This PR,
- Enhance API response caching mechanism
- Apply caching for get VM status
- Enable API call debug for resty (not enabled by config. will enhance next time.)
Test example. (it works nicely)
- Cached successfully!
- Cache hit! Expires:  -373.963826ms
- Cache item expired!
```
==============================================================================
Cached successfully!
2023/09/06 02:18:59.044565 DEBUG RESTY 
==============================================================================
~~~ REQUEST ~~~
GET  /spider/vmstatus/ns01-mc-8j0hg-g2-4  HTTP/1.1
HOST   : localhost:1024
HEADERS:
Accept: application/json
Content-Type: application/json
User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
BODY   :
{
"ConnectionName": "gcp-asia-northeast3"
} …
```
> API response caching for get VM status

- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
To retrieve, CB-TB API HTTP version.
<html>
<body>
Code | Details
-- | --
200 | Response bodyDownload{   "message": "HTTP/1.1" }
Response headers content-length: 23  content-type: application/json; charset=UTF-8  date: Mon,18 Sep 2023 06:31:45 GMT  vary: Origin
</body>
</html>
> Add check http version

- src/core/mcis/provisioning.go
- src/core/mcis/remoteCommand.go
- src/main.go
- VM이 Self bastion 이되어서 jump host 를 수행하도록 Jumphost 기능 초안 작성
> Add basic jumphost functionality for ssh

- src/core/mcir/vnet.go
- src/core/mcis/manageInfo.go
- src/core/mcis/remoteCommand.go
New feature for
- Set (assign) barison node to subnet for private VMs
- Get barison node list assigned to subnet
<html>
<body>
<div class="opblock-summary opblock-summary-put" style="box-sizing: border-box; align-items: center; cursor: pointer; display: flex; padding: 5px; border-bottom: 1px solid rgb(252, 161, 48); border-top-color: rgb(252, 161, 48); border-right-color: rgb(252, 161, 48); border-left-color: rgb(252, 161, 48); color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; …
> Set and get barison node assigned to subnet

- src/api/rest/server/mcis/remoteCommand.go
- src/api/rest/server/server.go
- src/core/mcis/benchmark.go
- src/core/mcis/nlb.go
- src/core/mcis/orchestration.go
- src/core/mcis/remoteCommand.go
Use universal func for remote command
- remove /ns/{nsId}/cmd/mcis/{mcisId}/vm/{vmId}
- use /ns/{nsId}/cmd/mcis/{mcisId} with Param vmId query
> Use universal func for remote command

- src/core/mcis/benchmark.go
- src/core/mcis/manageInfo.go
- src/core/mcis/monitoring.go
- src/core/mcis/network.go
- src/core/mcis/remoteCommand.go
Use PrivateIP for remote command for no-bastion
Test result
```
[Retrieve access information for MCIS:mcis01]
{
McisId: mcis01
McisSubGroupAccessInfo: [
{
SubGroupId: g1
BastionVmId: 
McisVmAccessInfo: [
{
vmId: g1-3
publicIP: 43.201.249.206
privateIP: 192.168.20.197
sshPort: 22
}
{
vmId: g1-1
publicIP: 43.202.59.92
privateIP: 192.168.20.10
sshPort: 22
}
{
vmId: g1-2
publicIP: 13.124.189.213
privateIP: 192.168.20.15
sshPort: 22
}
{
vmId: g1-5
publicIP: 3.38.193.183
privateIP: 192.168.20.101
sshPort: 22
}
{
vmId: g1-4
publicIP: 13.125.121.38
privateIP: 192.168.20.102
sshPort: 22
}
]
}
]
}
```
MCIS Command Request
Example Value
Model
{
"command": "client_ip=$(echo $SSH_CLIENT | awk '{print $1}'); echo SSH client IP is: $client_ip",
"userName": "cb-user"
}
```
[Complete: remote ssh command …
```
> Use PrivateIP for remote command for no-bastion

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/benchmark.go
- src/core/mcis/remoteCommand.go
Add command field for SshCmdResult for a reference.
> Add command field for SshCmdResult

- src/core/mcis/provisioning.go
- src/core/mcis/remoteCommand.go
- 기능 추가: MCIS 생성 또는 Scaling 할 때, 기 지정된 Bastion node가 신규 생성되는 VM들의 subnet에 지정되어 있지 않은 경우, 자동으로 가장 앞선/PublicIP를 가지고 있는 VM을 자동으로 Bastion node로 지정
> Auto-assign bastion node

- src/main.go
conf/cloud_conf.yaml 내용 변경을 watch해서, 환경변수에 반영하는 기능 추가.
활용 방식 예시: cloud_conf.yaml 수정 후 저장.
```diff
nlbsw:
sw: "HAProxy"
version: "latest"
commandNlbPrepare: "wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/deployNlb.sh; wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/addTargetNode.sh; wget https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/scripts/nlb/applyConfig.sh; chmod +x ~/deployNlb.sh ~/addTargetNode.sh ~/applyConfig.sh"
commandNlbDeploy: "sudo ~/deployNlb.sh"
commandNlbAddTargetNode: "sudo ~/addTargetNode.sh"
commandNlbApplyConfig: "sudo ~/applyConfig.sh"
nlbMcisCommonSpec: "aws-ap-northeast-2-t2-small"
nlbMcisCommonImage: "ubuntu18.04"
-  nlbMcisSubGroupSize: "2"
+  nlbMcisSubGroupSize: "4"
```
> WatchConfig for cloud_config and update dynamically

- src/api/rest/server/mcis/remoteCommand.go
- src/core/mcir/vnet.go
- src/core/mcis/remoteCommand.go
fix #1362
vNet 공유 모드에서, 서로 다른 MCIS간 Bastion Node를 공유할 수 있도록 처리하여
런타임 애러 해결.
> Fix Provisioning Global L4 NLB faces runtime error

- .github/workflows/auto-merge.yml
- CODEOWNERS
- OWNERS
This PR aims to update the ownership roles within this repository as follows:
- @jihoon-seo: transitioning from Maintainer to Emeritus.
- @yunkon-kim: transitioning from Workflow Approver to Maintainer.
Additionally, an important note has been appended to the CODEOWNERS file to acknowledge @jihoon-seo's invaluable contributions over the years as an Emeritus Maintainer:
```plaintext
> Update Repository Ownership (jihoon-seo and yunkon-kim)

- Dockerfile
- conf/setup.env
- src/api/rest/server/server.go
This PR will skip BasicAuth in the following cases:
- Host is "localhost",
- checking CB-Tumblebug health by /tumblebug/health, and
- checking HTTP version by /tumblebug/httpVersion.
I think it will make it a bit more convenient during development.
Please let me know if you have any issues.
> Skip BasicAuth in some cases and add disable option to env config

- Makefile
- src/Makefile
This PR will add Makefile in the project root directory and update the existing Makefile in `/src`.
This is simply a change for development convenience. It will likely reduce the act of going in and out of directories during development.
> Add Makefile in the project root directory

- src/api/rest/server/server.go
- 보통 API의 response header는 따로 허용하지 않는 경우, 브라우저에서 조회가 되지 않는다고 함. (개발자 도구로 확인은 가능)
- 이를 명시적으로 허용하도록 코드 개선. 
PR 적용되면, MapUI 대시보드에서 활용 가능.
> Make X-Request-Id visible to all handlers

- src/core/mcis/manageInfo.go
Refine was not working since the force delete was not effective.
This PR fixes the issue.
> Fix force refine and delete option

- src/core/common/netutil/netutil.go
- src/examples/netutil/netutil.go
#1412
This PR will provide a function to check if a network configuration is valid and its example.
> Add a function to check if a network configuration is vaild

- src/examples/netutil/netutil.go
I understand the current example is focused on checking each functionality. 
But, for a better understanding, how about providing a comprehensive output for netutil example? based on a relative usecase for cb-tumblebug?
(Global base network - VPCs - subnets)
This PR suggests modified output style.
./netutil -c "10.0.0.0/16" -s 16 -n 500
```
Starting netuil example
Divide CIDR block into subnets to accommodate at least minimum number of subnets
Divide CIDR block by a specified number of hosts
[Usecase] Get superneted VPCs and its subnets inside
- Base network: 10.0.0.0/16
- Minimum number of VPCs (subnets of the base network): 16
- Subnets in a VPC base on the number of hosts per subnet: 500
VPC[001]:       10.0.0.0/20
Subnets:        10.0.0.0/23, 10.0.2.0/23, 10.0.4.0/23, 10.0.6.0/23, …
```
> Provide comprehensive usecase output for netutil ex

- src/core/common/netutil/netutil.go
- src/examples/netutil/netutil.go
* Add models for subnetting request including CIDR block and rules
* Add SubnettingBy() and related functions
* Add GetName() which is missing member method
* (Minor) Relocate or rename some existing functions
Related to #1412 
**This PR will add a user-friendly function for subnetting a CIDR block by request rules.**
I think it's helpful to make a draft of a global muti-cloud network configuration, like the "global base network - VPCs - subnets" style. 
Note - By adding a rule, more than 3 depths are possible.
**Command**
```bash
./netutil -c "10.0.0.0/16" -s 16 -n 500
```
**Example (line 198-218)**
In this example, a CIDR Block is divided into multiple subnets by a rule `{Type: "minSubnets", Value: 16}`.
Each subnet is divided again into multiple subnets by a rule `{Type: "minHosts", …
> Add a function for subnetting by requested rules

- src/core/common/netutil/netutil.go
- src/examples/netutil/netutil.go
* Add Next/PreviousSubnet()
* Add these examples
This PR will add NextSubent() and PreviousSubent() and the following examples.
**NextSubnet() test example** - In case 4, `Error: the next subnet is outside the base network range`
```
NextSubnet() test example
[NextSubnet() Case1] Base Network CIDR: 10.0.0.0/16, Current Subnet CIDR: 10.0.0.0/18
Next Subnet: 10.0.64.0/18
[NextSubnet() Case2] Base Network CIDR: 10.0.0.0/16, Current Subnet CIDR: 10.0.64.0/18
Next Subnet: 10.0.128.0/18
[NextSubnet() Case3] Base Network CIDR: 10.0.0.0/16, Current Subnet CIDR: 10.0.128.0/18
Next Subnet: 10.0.192.0/18
[NextSubnet() Case4] Base Network CIDR: 10.0.0.0/16, Current Subnet CIDR: 10.0.192.0/18
Error: the next subnet is outside the base network range
```
**PreviousSubnet() test example** - In case 1, …
> Add Next/PreviousSubnet() to `netutil` pkg

- src/core/common/client.go
- src/core/mcir/common.go
- src/testclient/scripts/3.vNet/add-subnet.sh
- src/testclient/scripts/3.vNet/create-vNet.sh
fix #1409
Refine supernetting vNet rules to support K8s cluster provisioning.
[create-vNet.sh]
- CSP[i]-VPC: 10.i.0.0/16
- CSP[i]-Subnet[0]: 10.i.0.0/18
- CSP[i]-Subnet[1]: 10.i.64.0/18
[add-subnet.sh]
- CSP[i]-Subnet[2]: 10.i.128.0/18
- CSP[i]-VPC: 10.i.0.0/16
- CSP[i]-Subnet[0]: 10.i.0.0/18
- CSP[i]-Subnet[1]: 10.i.64.0/18
// Reserve spaces for tentative 2 subnets (10.i.128.0/18, 10.i.192.0/18)
> Refine supernetting and network provisioning rules to support k8s provisioning

- scripts/runSpider.sh
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcir/dataDisk.go
- src/api/rest/server/server.go
- src/core/mcir/datadisk.go
- src/core/mcis/manageInfo.go
---
- Add provisioning DataDisk to VM: a new function to combine create a DataDisk and attach it to specific VM.
POST `/ns/{nsId}/mcis/{mcisId}/vm/{vmId}/dataDisk`  
Provisioning (Create and attach) dataDisk
- Apply the common func (common.ExecuteHttpRequest) for internal call to DataDisk MGM 
- Enhance: DataDisk MGM error handling for #1422
---
- Minor: CB-Spider container version to 0.8.1 (and tested)
> Add provisioning DataDisk to VM (including enhancements in Disk management)

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/common/client.go
- Note: the reason why we need to use POST method for a CB-Spider GET request is that Swagger UI does not accept GET with request body.
> Add forward any (GET) request to any (CB-Spider) internal system 

- .dockerignore
- Dockerfile
- scripts/runTumblebug.sh
Dockerfile 개선
- 1 단계 빌드에 필수 파일만 포함
- `RUN go mod download` 로 중간단계 캐싱
- 코드 중복성 개선
.dockerignore 추가
- `**/credentials.conf` 를 명시적으로 제외
scripts/runTumblebug.sh
- 미활용 포트 명세 제거 (grpc 서버)
> Enhance Dockerfile and build

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/server.go
- src/api/rest/server/util/netuil.go
- src/core/common/netutil/netutil.go
- src/examples/netutil/netutil.go
This PR will provide network utility APIs.
What changes: 
* Add a API to support network design
* Add a API to support network validation
* Update Swagger docs
* Update the existing netutil pkg and example
**APIs**
I have analyzed the existing API classifications and then assigned separate API tags. It's because these APIs can be used to design and validate a network for both the MCIR and the MCIS. (I think it could be used more generally :-) )
It would be great for me to get some feedback on this, and I will quickly modify the `route` and `tag in annotation` according to the feedback :-D
**API usage example**
1) `POST /util/net/design`
This API can support network design more easily than calculating and designing all CIDR blocks. `"minSubnets"` and `"minHosts"` are supported as `type` …
> Add network utility APIs

- scripts/usecases/llm/README.md
- scripts/usecases/llm/startServer.sh
- scripts/usecases/llm/statusServer.sh
- scripts/usecases/llm/stopServer.sh
- LLM을 쉽게 배포해볼 수 있는 유스케이스 추가.
- 하기 spec, image set에서 실행 가능
- AWS,aws-us-east-2, `ami-0c616d2c080a12072`, `Ubuntu 20.04`
- AWS,aws-us-east-2, `g5.2xlarge`
This document describes a set of scripts designed to manage an LLM (Large Language Model) service. These scripts facilitate starting the service (`startServer.sh`), checking its status (`statusServer.sh`), and stopping the service (`stopServer.sh`).
- A Linux-based system
- Python 3 installed
- pip (Python package manager)
- sudo privileges or root access
Starts the LLM service by installing necessary Python packages and running a FastAPI-based service in the background.
```bash
sudo ./startServer.sh
```
To download and prepare `startServer.sh` script for execution:
```bash
wget https://example.com/path/to/startServer.sh
chmod +x …
```
> Self host LLM use case (initial code)

- assets/cloudspec.csv
- scripts/usecases/llm/llmServer.py
- scripts/usecases/llm/startServer.sh
- scripts/usecases/llm/statusServer.sh
- scripts/usecases/llm/stopServer.sh
`
[llmServer] Starting LLM service in the background...
[llmServer] Checking status of the LLM service...
[llmServer] LLM service is running. PID: 36673
[llmServer] Showing the last 20 lines of the log file (llmServer.log):
[Test: replace localhost with IP address of the server]
curl -X POST http://localhost:5001/query -H "Content-Type: application/json" -d '{"prompt": "What is the Multi-Cloud?"}'
http://localhost:5001/query?prompt=What is the Multi-Cloud?
`
`
cb-user@ip-10-11-10-23:~/llm$ curl -X POST http://localhost:5001/query -H "Content-Type: application/json" -d '{"prompt": "What is the Multi-Cloud?"}'
{"text":" Multi-cloud is the practice of using multiple cloud computing platforms or services from different providers to store and process data. This is often used as a backup or …
> Update llm usecase with easy setting

- src/core/common/client.go
fix #1447
최소한의 수정으로 #1447 의 문제를 교정함.
- Bind 오류의 경우에 http.StatusBadRequest 를 리턴하며, 
- 나머지 경우 기존대로 http.StatusInternalServerError 리턴.
> Assign StatusBadRequest code for http bind error

- scripts/usecases/llm/llmServer.py
- scripts/usecases/llm/startServer.sh
- Add swagger dashboard for LLM server
- Add API documentation
> Add swagger dashboard for LLM server

- scripts/usecases/llm/llmServer.py
- scripts/usecases/llm/startServer.sh
Add custom input for LLM token size.
Now, default for max_new_tokens is 1024
> Add custom input for LLM token size

- README.md
- i18n/README-EN.md
- src/api/rest/server/server.go
Change API dashboard URL (easy to remember)
- as is: http://localhost:1323/tumblebug/`swagger/index.html`
- to be: http://localhost:1323/tumblebug/`api`
> Change API dashboard URL into /api

- README.md
- i18n/README-EN.md
- src/api/rest/server/server.go
Swag 업스트림에 의해서
swagger 키워드 이외에 다른 Path를 지정하지 못하는 것으로 판단.
기존 설정으로 revert.
> Revert API path for Swagger UI to fix err

- scripts/exportCredentials.sh
- scripts/runTF.sh
* Align the exported AWS and Azure credentials with Tofu requirements
* Export and rename AWS, Azure, and GCP credentials
* Inject the credentials when the poc-mc-net-tf container runs
Related to #1439
> Add runTF.sh to run poc-mc-net-tf container

- src/api/rest/server/server.go
This PR will update the URL to access Swagger UI.
- Double slash issue:
`http://localhost:1323/tumblebug/swagger//index.html` appeared when I accessed the URL `http://localhost:1323/tumblebug/swagger/` on a browser. (It seems to be a bug of `swaggo/echo-swagger`.)
- Needs: 
Also, we may be needed `http://localhost:1323/tumblebug/api/index.html` as tumblebug API URL (related to https://github.com/cloud-barista/cb-tumblebug/pull/1470).
> Update the URL to access Swagger UI

- src/core/mcir/common.go
- src/core/mcis/provisioning.go
MCIS Dynamic 으로 프로비저닝 진행시, 
- 기존: 동적 리소스의 일부가 생성되지 않아도, MCIS및 VM 생성 시도
- 변경: 동적 리소스가 하나라도 준비되지 않은 경우, MCIS및 VM 생성을 시도하지 않고 오류 리턴.
- 기본 자원 전체 삭제 시도를 통해서 기본적인 rollback을 진행
> Stop and rollback for MCIS dynamic with no init

- src/api/rest/server/common/utility.go
- src/api/rest/server/mcis/remoteCommand.go
- src/api/rest/server/server.go
* Update the custom request ID middleware
* Add the custom bodydump middleware
**기존 StartRequestWithLog, EndRequestWithLog를 Middleware로 처리할 수 있도록 만든 PR 입니다.**
기존에 처리되던 매커니즘과 다르거나 지장이 있을지 몰라서 논의를 위한 PR을 열었습니다. (Draft PR)
코드 변경사항과 아래 실행 로그 확인 바랍니다. 이후, 추가 수정 보완하도록 하겠습니다.
**요약 설명:**
- Line 1-3: Request ID 미들웨어 (Request ID 발급, RequestMap 중복확인 및 저장)
- Line 4: health check 핸들러
- Line 5-9: BodyDump 미들웨어 (RequestMap 로드, 핸들러 성공/실패 확인, (실패시)RequestMap에 "Error" 및 error message 저장, (성공시) RequestMap에 "Successs" 및 resBody 저장
(참고 - 실행 이력)
```bash
{"time":"2024-03-28T23:14:07.847907353+09:00","level":"-","prefix":"echo","file":"server.go","line":"94","message":"Start - RequestLog()"}
{"time":"2024-03-28T23:14:07.847937453+09:00","level":"-","prefix":"echo","file":"server.go","line":"104","message":"Reques …
```
> [Show and discuss] Process request log in middlewares

- src/api/rest/server/middlewares/custom-middleware.go
- src/api/rest/server/server.go
* Fix response body unmarshaling error due to the type (close #1484)
- string, JSON object ("{ }"), JSON array ("[ ]") will be supported.
> Tidy up middlewares

- src/api/rest/server/middlewares/custom-middleware.go
- src/api/rest/server/server.go
Very first code ;)
skipPatterns should be injected from a higher level function.
> Add skip logging middleware by uri rule

- src/api/rest/server/middlewares/custom-middleware.go
- src/api/rest/server/server.go
- 기존 코드에는 URL.Path 로 패턴 매칭하여, 쿼리 파라미터 처리가 되지 않는 문제가 있었음.
- 이를 개선하며, 다중 스트링 중복 매칭을 지원할 수 있게 수정.
> Fix pattern unmatched issue in api log skipper

- conf/template.credentials.conf
This PR will recover CredentialName for AWS on `conf/template.credentials.conf` and resolve the issue below.
- Issue: Registration of all AWS-related items failed when running `initMultiCloudEnv.sh`.
> Fix missing CredentialName on `conf/template.credentials.conf`

- src/api/rest/server/common/utility.go
- src/core/common/client.go
- src/core/mcis/benchmark.go
- src/core/mcis/monitoring.go
Replace deprecated functions. (Deprecation of io/ioutil as of Go 1.16)
https://go.dev/doc/go1.16#ioutil
```
Deprecation of io/ioutil
The [io/ioutil](https://go.dev/pkg/io/ioutil/) package has turned out to be a poorly defined and hard to understand collection of things. All functionality provided by the package has been moved to other packages. The io/ioutil package remains and will continue to work as before, but we encourage new code to use the new definitions in the [io](https://go.dev/pkg/io/) and [os](https://go.dev/pkg/os/) packages. Here is a list of the new locations of the names exported by io/ioutil:
[Discard](https://go.dev/pkg/io/ioutil/#Discard) => [io.Discard](https://go.dev/pkg/io/#Discard)
[NopCloser](https://go.dev/pkg/io/ioutil/#NopCloser) => …
```
> Replace deprecated io/ioutil from golang

- src/core/mcir/common.go
- src/core/mcis/manageInfo.go
- src/core/mcis/nlb.go
- src/core/mcis/orchestration.go
- src/core/mcis/provisioning.go
- src/core/mcis/recommendation.go
- Enhance precondition checking in mcis dynamic
- check availability of common resources (image, spec set)
- Enhance delete mcis logic and return description
> Enhance precondition checking in mcis dynamic

- scripts/init/init.sh
- src/main.go
- 참조 credentials.yaml 파일 위치 조정
- {HOME}/.cloud-barista/credentials.yaml 이 없어도 시스템 종료하지 않음 (로그로 메시지 출력)
> Fix startup err from the new credential

- scripts/runSpider.sh
- src/core/common/client.go
- src/core/common/utility.go
- src/main.go
CB-TB 서버 안정성 향상 개선.
- CB-TB 시작시, 3초 단위로 CB-Spider의 서버 준비 상태를 확인하고
- 60번 초과시 CB-TB를 종료함. (이후 사용자가 CB-SP 서버 검토 후, 재실행 필요)
```
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 1/60
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 2/60
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 3/60
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 4/60
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 5/60
3:17AM INF main.go:187 > CB-Spider at http://localhost:1024/spider is not ready. Attempt 6/60
3:17AM INF main.go:184 > CB-Spider is now ready.
██████╗██████╗    ████████╗██████╗      
██╔════╝██╔══██╗ …
```
> Safely waiting for CB-Spider for CB-TB ready

- src/core/mcis/provisioning.go
- src/testclient/test-clis/vpn-tunnel/gcp-aws/app.go
- src/testclient/test-clis/vpn-tunnel/gcp-aws/mcisDynamic.json
* Update API to check readiness
* Update the request body of `POST /mcisDynamic`
* Update the mechanism of deleting MCIS
* Test the CLIs are working properly
* Be sure to log what is processed internally for mcisDynamic API
> Update test-cli for gcp-aws vpn tunnel

- Dockerfile
This PR will add CBLOG_ROOT to Dockerfile to make the CB-Tumblebug container work properly.
```bash
docker build --no-cache -t local-tb .
```
```bash
cd $CBTUMBLEBUG_ROOT
source conf/setup.env
./scripts/runSpider.sh
``` 
```bash
sudo docker run --rm -p 1323:1323 \
--network host \
-v /home/ubuntu/dev/cloud-barista/cb-tumblebug/container-volume/cb-tumblebug-container:/app/meta_db \
-e SPIDER_REST_URL=http://localhost:1024/spider -e DRAGONFLY_REST_URL=http://localhost:9090/dragonfly -e SELF_ENDPOINT=localhost:1323 \
--name cb-tumblebug \
local-tb
```
Note - `--network host` option is added because my environment is WSL2.
```bash
cd $CBTUMBLEBUG_ROOT
source conf/setup.env
./scripts/init/init.sh
```
```bash
cd $CBTUMBLEBUG_ROOT
source conf/setup.env
./scripts/runMapUI.sh
```
Result: 
Note - …
> Check if the CB-Tumblebug container is working without issues

- scripts/init/README.md
- scripts/init/init.sh
- scripts/init/requirements.txt
- scripts/runSpider.sh
fix #1547
- `if ! python3 -c "import venv ensurepip" &> /dev/null; then ` will fix #1547
- Define minimal python3 version
- runSpider will provide env variable to make spider runs in localhost.
> Make init.sh works for ubuntu 18.04 as well

- scripts/runTumblebug.sh
- src/api/rest/server/server.go
This PR includes two things:
1) Adding endpoint selection logic to `runTumblebug.sh`
2) Checking readiness without auth
Tumblebug users/developers can select the endpoints when running the Tumblebug container.
Option 1) Use the retrieved external IP and set the endpoints of SP, DF, TB as the previous
Option 2) Use `host.docker.internal` and `localhost`
- Note: `host.docker.internal` is used for TB container to communicate with SP/DF containers
- Note: `localhost` is used for Tumblebug `SELF_ENDPOINT` for serving APIs externally
Also, we can check TB readiness without auth.
> Update to `runTumblebug.sh` and check readiness without auth

- src/core/common/utility.go
- src/core/mcir/common.go
> Refine log messages and error handling

- src/core/common/client.go
CB-SP에서 에러를 리턴하는 경우도 왕왕(동일한 이름의 노드그룹 추가 등) 있기 때문에 requestkey 값을 확인한 후 requestDone()을 호출하도록 수정한 PR입니다.
method가 GET인 경우에 한정하여 requestDone()을 호출하는 방안도 있겠습니다.
의견 주시면 반영하도록 하겠습니다.
fix: #1557
> fix to ensure to call requestdone() when requestkey is valid

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/control.go
- src/api/rest/server/mcis/provisioning.go
- src/core/common/config.go
- src/core/common/utility.go
- src/core/mcir/common.go
- src/core/mcir/spec.go
- src/core/mcis/control.go
- src/core/mcis/nlb.go
- src/core/mcis/provisioning.go
- src/main.go
- resolve: https://github.com/cloud-barista/cb-spider/issues/1182
- ref: https://github.com/cloud-barista/cb-tumblebug/issues/1452#issuecomment-1982810347
- with "hold" option, MCIS dynamic will be holed after it creates requires resources.
- holded MCIS can be continued with control MCIS option `continue` (or `withdraw` for writhdraw)
> Korean CSP supports (MCIS dynamic hold option and preserve regionname case)

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/provisioning.go
- src/core/mcis/provisioning.go
- src/core/mcis/recommendation.go
With this PR, uses can use both Image ID and Keyword for MCIS dynamic request.
> Accept two commonImage input types

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/network.go
- src/api/rest/server/model/network.go
- src/api/rest/server/server.go
* Add structs (models) for sites info
* Add a func to extract sites info
* Add API handler and route
API response sample
```json
{
"nsId": "",
"mcisId": "",
"count": 3,
"sites": {
"aws": {
"kdemo-ns01-systemdefault-aws-ap-northeast-2": {
"csp": "aws",
"region": "ap-northeast-2",
"vnet": "subnet-0a49a31662ac3869e",
"subnet": "subnet-0a49a31662ac3869e"
}
},
"azure": {
"kdemo-ns01-systemdefault-azure-koreacentral": {
"csp": "azure",
"region": "koreacentral",
"vnet": "kdemo-ns01-kdemo-ns01-systemdefault-azure-k-cp2q6qp5e95jebpgcqbg",
"gatewaySubnetCidr": "10.46.128.0/18",
"resourceGroup": "koreacentral"
}
},
"gcp": {
"kdemo-ns01-systemdefault-gcp-asia-northeast3": {
"csp": "gcp",
"region": "asia-northeast3",
"vnet": "kdemo-ns01-kdemo-ns01-systemdefault-gcp-as-cp2q70h5e95jebpgcqgg"
}
}
}
}
```
> Add API to extract and refine sites info from MCIS info

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/mcir/subnet.go
- src/core/mcir/vnet.go
fix #1576
Response body of /ns/{nsId}/resources/vNet/{vNetId}
```
{
"id": "ns01-systemdefault-aws-ap-northeast-2",
"name": "ns01-systemdefault-aws-ap-northeast-2",
"connectionName": "aws-ap-northeast-2",
"cidrBlock": "10.34.0.0/16",
"subnetInfoList": [
{
"Id": "ns01-systemdefault-aws-ap-northeast-2",
"Name": "ns01-systemdefault-aws-ap-northeast-2",
"IdFromCsp": "subnet-01631ba5b3eccf9b5",
"IPv4_CIDR": "10.34.0.0/18",
"BastionNodes": [
{
"mcisId": "mc-hhh6d",
"vmId": "g1-1"
}
],
"KeyValueList": [
{
"key": "VpcId",
"value": "vpc-07915390e0d20f457"
},
{
"key": "MapPublicIpOnLaunch",
"value": "false"
},
{
"key": "AvailableIpAddressCount",
"value": "16379"
},
{
"key": "AvailabilityZone",
"value": "ap-northeast-2a"
},
{
"key": "Status",
"value": "available"
}
],
"Description": ""
},
{
"Id": …
```
> Add Subnet handing id generated by CSP to vNet info

- src/core/common/utility.go
- 사용자 지정 리소스 명칭에 대문자도 허용 (기존: 소문자만 허용)
- 조회시 대소문자 구분 필요
> Expand naming rule condition uppercase

- go.mod
- go.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/network.go
- src/api/rest/server/model/network.go
- src/api/rest/server/server.go
- src/testclient/test-clis/vpn-tunnel/gcp-aws/app.go
- src/testclient/test-clis/vpn-tunnel/gcp-aws/config.yaml
* Integrate and test with mc-terrarium v0.0.7
* Enhance the sites info struct and extraction mechanism from an MCIS info
* Change and provide a Site-to-site VPN instead of a GCP-AWS VPN
* Specify stream-response in the API URL
: API - `GET /ns/{nsId}/mcis/{mcisId}/site`
: Responses
```json
{
"nsId": "kimy-ns01",
"mcisId": "kimy-mcis01",
"count": 3,
"sites": {
"aws": [
{
"csp": "aws",
"region": "ap-northeast-2",
"vnet": "vpc-0f67dcae95c1aa02b",
"subnet": "subnet-04634eaad66653e24"
}
],
"azure": [
{
"csp": "azure",
"region": "koreacentral",
"vnet": "kimy-ns01-kimy-ns01-systemdefault-azure-kor-cpfb96gti87soliltnf0",
"gatewaySubnetCidr": "10.47.128.0/18",
"resourceGroup": "koreacentral"
}
],
"gcp": [
{
"csp": "gcp",
"region": "asia-northeast3",
"vnet": …
```
> Update to provide site-to-site VPN

- go.mod
- go.sum
- src/core/mcis/provisioning.go
- src/testclient/scripts/8.mcis/add-subgroup-to-mcis.sh
- src/testclient/scripts/8.mcis/create-mcis.sh
- src/testclient/scripts/sequentialFullTest/clean-mcir-ns-cloud-domestic.sh
- KTCloud VPC, NHNCloud 의 경우, 부득이하게 Network를 미리 생성하고 등록해야 함.
- Test Script에서 VM 생성시 Subnet ID를 입력해야 하지만, 외부에서 등록된 ID이고, 해당 ID가 변경될 수 있는 바, 테스트 스크립트에서는 조건부로 임의 Subnet ID를 선정하여 VM 프로비저닝을 지원하기로 함.
결과
- KTCloud VPC, NHNCloud: 테스트 스크립트(create-all)로 VM 생성 확인 완료.
> Support domestic CSPs testing (NHN, KT requires register feature)

- src/api/rest/server/middlewares/custom-middleware.go
- src/core/common/client.go
- src/core/mcis/remoteCommand.go
- ssh 수행 현황을 서버 실행 콘솔에서 확인 가능하게 수정 (향후 외부로 노출될 수 있도록 처리할 수 있음)
> Display ssh std to streaming pipe

- src/core/mcis/cluster.go
클러스터 생성시 image id에 default 값을 허용하여 공백으로 입력되도록 수정합니다.
https://github.com/cloud-barista/cb-spider/pull/1214#issuecomment-2162065250
> Allow 'default' image id for k8scluster

- src/api/rest/server/middlewares/custom-middleware.go
- src/core/common/client.go
* Check if type assertion is OK or not in
- func ExecuteHttpRequest()
- func ResponseBodyDump(), middleware
> Check if type assertion is OK or not to avoid panic

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/k8scluster.go
K8sCluster API 중 swagger comments에 일부 파라미터 항목이 기재되지 않은 부분을 업데이트합니다.
> Update some K8sCluster API's swagger comments

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/mcis/network.go
- src/api/rest/server/server.go
* Add GCP to Azure VPN configuration
* Enhance the mechanism to check if the CSP set is valid
* Make it simple to check which CSP set it is.
* Test to CRUD a GCP to Azure VPN
* Update the handler name and API ID trivially
> Support GCP to Azure VPN by site-to-site VPN API

- .gitignore
- docker-compose.yaml
* Add docker-compose.yaml to provide a stable set of subsystems
* Ignore all docker-compose files created by users, except docker-compose.yaml
Tumblebug users/contributors can make and use their copies from docker-compose.yaml.
(e.g,. `docker-compose -f my-docker-compose.yaml up`, `docker-compose -f docker-compose2.yaml up`, and so on)
docker-compose.yaml has been tested on the following environment.
- Ubuntu 22.04.3 LTS on Windows Subsystem for Linux 2 (WLS 2)
- Docker 27.0.3
- Docker Compose 1.29.2
Test completed
- Create and delete MCIS across AWS, Azure, and GCP on mapui
Please review the changes in this pull request :-)
Close #1661
> Add docker-compose

- src/main.go
This PR will enable two authentication interfaces in Swagger UI as follows.
Ref: [How to use security annotations from swaggo/swag](https://github.com/swaggo/swag?tab=readme-ov-file#how-to-use-security-annotations)
[추가 설명]
: Authorize 클릭
: BasicAuth를 기본 활용
: JWT test를 위한 API 에서 자물쇠 클릭 시
: JWT 인증 관련 팝업(현 시점에 사용되지 않음)
위 Bearer 인증 부분은 인증 서버를 엔트포인트가 필요한 상황입니다. 데모 및 테스트 용으로 MC-IAM-MANAGER에서 공유된 서버를 기재해 놓을 수 있지만, 현 상황에서는 안전하지 않은 방법이라는 생각이 듭니다. 
따라서, '([TBD] Get token in http://xxx.xxx.xxx.xxx:xxx/auth)' 으로 뼈대만을 적용해 두고, 추후 아래 방안 중 적절한 것으로 추진하면 될 것 같습니다.
* 인증 서버 연동 및 정보 수정
* 인증 서버 연동 가이드 제공
> Modify swaggo/swag `@securityDefinitions`

- README.md
- scripts/init/README.md
- scripts/init/decCredential.sh
- scripts/init/encCredential.sh
- scripts/init/init.py
to enhance security.
To protect sensitive information, `credentials.yaml` is not used directly. Instead, it must be encrypted using `encCredential.sh`. The encrypted file `credentials.yaml.enc` is then used by `init.py`. This approach ensures that sensitive credentials are not stored in plain text.
If you need to update your credentials, decrypt the encrypted file using `decCredential.sh`, make the necessary changes to `credentials.yaml`, and then re-encrypt it.
- Encrypting Credentials
```bash
scripts/init/encCredential.sh
```
- Decrypting Credentials
```bash
scripts/init/decCredential.sh
```
> Add encryption decryption script for credentials

- docker-compose.yaml
- src/api/rest/server/mcis/network.go
- src/examples/kvstore/main.go
- src/kvstore/etcd/etcd.go
- src/kvstore/kvstore/etcd.go
- src/kvstore/kvstore/kvstore.go
- src/kvstore/kvutil/kvutil.go
This PR includes the following:
* Add `kvstore.go`, which defines interfaces, structs, and types
* Add `etcd.go`, which implements functions (corresponding to interfaces) to utilize etcd
* Add `kvutil.go`, which supports utility functions to handle KeyValue easily.
* Update `docker-compose.yaml` to deploy and run etcd container locally
* Add examples to test the pkgs
**cb-store를 etcd로 대체하기 위한 작업을 진행중에 있습니다.**
* 이를 위해, cb-store 및 CB-Tumblebug의 기존 KeyValue store 관련 코드 리뷰 및 설계 의도 파악을 선행했고요.
* 관련하여, `kvstore`, `kvutil` pkg를 추가하고 `docker-compose.yaml` 업데이트를 진행하고자 합니다.
* 이는, etcd의 본래 활용 방식을 최대한 유지하면서, 기능을 보완/개선하는 방향으로 설계 및 개발하였습니다. 
**기능상으로 볼 때, 아래와 같이 매칭 가능합니다.** 
| As-Is | To-Be |
| ----- | -------|
| CBStore.Get(Key) | etcd.GetKv(key) |
| CBStore.GetList(key, true) | …
> Add `kvstore` pkg and improve functionality 

- src/core/mcis/k8scluster.go
assets/cloud.conf에 기재된 k8scluster enablement를 확인하는 코드들의 중복을 제거하고, 클러스터 버전 확인 부분을 업데이트하였습니다.
> Deduplicate code for checking k8scluster enablement

- assets/k8sclusterinfo.yaml
- src/core/common/common.go
- src/core/common/utility.go
assets/k8sclusterinfo.yaml의 내용 업데이트 및 others 키워드를 추가하여 특이한 리전과 일반 리전을 구분하여 처리할 수 있도록 하였습니다.
> Update k8sclusterinfo.yaml and add 'others' keyword

- docker-compose.yaml
- Isolate ETCD within the internal_network
- disable etcd-conf for setting id/pw for ETCD (for simplicity)
- rename the container `etcd` into `cb-tumblebug-etcd`
---
- tag version up: cb-tumblebug version 0.9.3
- disable some not important ENVs
---
note: cb-spider is also has external_network. It is for outbound access (not ideal for security)
> Simply docker compose and isolate containers

- src/core/common/logger/logger.go
- src/main.go
* Set permission to read log file in container volume
* Set relative path with line number by zerolog.CallerMarshalFunc
- This will make it easy to access the lines in the file that were logged in the IDE.
- I expect this will ensure that the log format remains consistent across different execution environments.
> Enhance logger pkg

- assets/k8sclusterinfo.yaml
- src/api/rest/server/mcis/k8scluster.go
- src/core/common/config.go
- src/core/common/utility.go
K8sCluster 생성시 노드 그룹 지정 여부를 확인할 수 있는 API를 추가합니다.
아직 테스트가 되지 않았기에 route에 등록하지 않은 상태입니다.
> [k8scluster] add CheckNodeGroupsOnK8sCreation API (no routed)

- docker-compose.yaml
docker compose . --build
enable `build` part if you wish to use your source.
```
```
```
```
> Support build option for docker compose

- src/core/mcis/k8scluster.go
- src/testclient/scripts/13.k8scluster/add-k8snodegroup.sh
- src/testclient/scripts/13.k8scluster/create-k8scluster.sh
SpecId 체계 개선 진행 전 임시로 CB-TB의 SpecId가 아닌 CSP Spec Name을 입력하도록 예제를 변경하였습니다.
> [k8scluster] update valid specId example in TbK8sNodeGroupReq

- docker-compose.yaml
- src/api/rest/server/mcir/common.go
- src/api/rest/server/server.go
- src/core/mci/k8scluster.go
- src/core/mci/provisioning.go
- src/core/mci/snapshot.go
- src/core/mcir/common.go
- src/core/mcir/datadisk.go
- src/core/mcir/securitygroup.go
- src/core/mcir/sshkey.go
- src/core/mcir/subnet.go
- src/core/mcir/vnet.go
> Simplify ID system using GenUid and no Transform

- init/init.py
- init/requirements.txt
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/common/utility.go
- src/api/rest/server/server.go
- src/core/common/common.go
- src/core/common/utility.go
Register Credential Information
```
// @Description This API is used to register credential information securely. The client must encrypt the sensitive information using a hybrid encryption method before sending it to the server.
//
// The encryption process involves the following steps:
// 1. The client generates a random AES key.
// 2. The credential data is compressed using gzip.
// 3. The compressed data is encrypted using AES (Advanced Encryption Standard).
// 4. The AES key is then encrypted using the RSA public key obtained from the `GET /credential/publicKey` endpoint.
// 5. Both the encrypted AES key and the AES-encrypted data are sent to the server in the request payload.
//
// **Hashing and Encryption Details:**
// - **RSA Key Pair Generation:** The server generates an RSA key …
```
> Provide a secure way for register credential api

- init/init.py
- init/requirements.txt
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/common/utility.go
This PR will provide additional info for credential registration with init.py.
> Enhance secure credential registeration

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/auth/auth.go
- src/api/rest/server/common/config.go
- src/api/rest/server/common/namespace.go
- src/api/rest/server/common/utility.go
- src/api/rest/server/mci/benchmark.go
- src/api/rest/server/mci/control.go
- src/api/rest/server/mci/k8scluster.go
- src/api/rest/server/mci/manageInfo.go
- src/api/rest/server/mci/monitoring.go
- src/api/rest/server/mci/network.go
- src/api/rest/server/mci/nlb.go
- src/api/rest/server/mci/orchestration.go
- src/api/rest/server/mci/provisioning.go
- src/api/rest/server/mci/recommendation.go
- src/api/rest/server/mci/remoteCommand.go
- src/api/rest/server/mcir/common.go
- src/api/rest/server/mcir/customimage.go
- src/api/rest/server/mcir/dataDisk.go
- src/api/rest/server/mcir/firewallrule.go
- src/api/rest/server/mcir/image.go
- src/api/rest/server/mcir/securitygroup.go
- src/api/rest/server/mcir/spec.go
- src/api/rest/server/mcir/sshkey.go
- src/api/rest/server/mcir/subnet.go
- src/api/rest/server/mcir/vnet.go
- src/api/rest/server/server.go
- src/api/rest/server/util/netuil.go
API 문서의 Tag (api resource group)을 전반적으로 조정 및 개선 하였습니다.
> Arrange API resource group tags

- src/core/resource/k8scluster.go
k8scluster 생성시 CB-SP의 subnet name으로 전달되도록 수정합니다.
> [k8scluster] fix cb-spider's subnet name

- assets/cloudimage.csv
- assets/cloudspec.csv
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/resource/image.go
- src/api/rest/server/resource/spec.go
- src/core/infra/provisioning.go
- src/core/model/image.go
- src/core/model/k8scluster.go
- src/core/model/mci.go
- src/core/model/spec.go
- src/core/model/subnet.go
- src/core/resource/common.go
- src/core/resource/image.go
- src/core/resource/k8scluster.go
- src/core/resource/spec.go
- src/core/resource/subnet.go
- src/core/resource/vnet.go
cspResourceId -> cspImageName
cspResourceId -> cspSpecName
명시적으로 csp 라는 표현을 붙여서, 혼동을 방지하고자 하였습니다. 
또한 pair로 있던 cspXXXId 는 TB에서 assets에 해당하는 spec과 image에 경우에는 도입하지 않도록 field에서 삭제하였습니다. (다른 리소스 군은 2개의 pair를 지니고 있음)
> Rename spec and image relatd fields

- assets/cloudinfo.yaml
- scripts/misc/update-cloudinfo.py
- Update cloud region zone info 
- Enhance the helper tool
> Update cloud region zone info and the helper tool

- src/core/infra/recommendation.go
- src/core/resource/spec.go
- src/main.go
- mciRecommend 가 spec이 8만건 이상 등록되기 시작하면서, 성능 저하 발생. (약 12초 소요)
DB 인덱스 추가를 통해서, 속도향상 시킴. 
약 12초 -> 약 3.5초
(향후 추가 개선의 소지가 있음)
> Expedite vm recommend filtering speed

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/infra/loadbalance.go
- src/core/infra/manageInfo.go
- src/core/infra/orchestration.go
- src/core/infra/provisioning.go
- src/core/infra/utility.go
- src/core/model/k8scluster.go
- src/core/model/mci.go
- src/core/resource/k8scluster.go
각 오브젝트의 기존 label string을 신규 Label 구조로 대체 (오브젝트 조회시에, label 조회 기능을 통해 내용 첨부하여 제공)
본 PR의 적용 대상
- mci, vm
- k8sCluster
나머지 오브젝트에 대해서는 향후 적용 예정.
MCI 조회 예시
> Change string label to structed label for mci

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/infra/remoteCommand.go
- src/api/rest/server/server.go
- src/core/infra/remoteCommand.go
- Cloud-Migrator 지원 기능
- 소스의 SW의 설정 파일 등을 목표 인프라로 전송(중계)해주는 보조 기능
- 대용량 파일/DB 덤프 전송하기 위한 기능 아님
- 파일 예시 (*.yaml, *.json, ENV, *.sh, *.py, …)
- 중계 전송 방식
- 사용자 -> CB-TB: REST API 기반 파일 업로드 (multipart/form-data)
- CB-TB: 파일 임시 저장 (메모리)
- CB-TB -> 목표 인프라: SSH 프로토콜 기반 파일 전송 (SCP)
- 최대 파일 크기 10MB (보안 및 안정성을 위해 제한함)
- 편의를 위한 최소 기능이며, 추가적인 자동화나 관리 기능을 제공하지 않음.
- OS 다양성 등을 지원하지 않음 (현: Linux만 지원)
- POST: /ns/{nsId}/transferFile/mci/{mciId}
```
curl -X 'POST' \
'http://localhost:1323/tumblebug/ns/default/transferFile/mci/mc-zy6w8?subGroupId=g1&vmId=g1-1' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-H 'Authorization: Basic ZGVmYXVsdDpkZWZhdWx0' \
-F 'path=/home/cb-user/' \
-F 'file=@240919-과제-Todolist.pdf;type=application/pdf'
```
(Swagger Dashboard로 파일 첨부 가능)
> Add remote file transfer feature

- src/api/rest/server/common/config.go
- src/api/rest/server/common/label/label.go
- src/api/rest/server/common/namespace.go
- src/api/rest/server/common/utility.go
- src/api/rest/server/infra/benchmark.go
- src/api/rest/server/infra/control.go
- src/api/rest/server/infra/loadbalance.go
- src/api/rest/server/infra/manageInfo.go
- src/api/rest/server/infra/monitoring.go
- src/api/rest/server/infra/orchestration.go
- src/api/rest/server/infra/provisioning.go
- src/api/rest/server/infra/recommendation.go
- src/api/rest/server/infra/remoteCommand.go
- src/api/rest/server/infra/utility.go
- src/api/rest/server/middlewares/requestIdAndDetailsIssuer.go
- src/api/rest/server/middlewares/responseBodyDump.go
- src/api/rest/server/resource/common.go
- src/api/rest/server/resource/customimage.go
- src/api/rest/server/resource/dataDisk.go
- src/api/rest/server/resource/firewallrule.go
- src/api/rest/server/resource/image.go
- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/resource/securitygroup.go
- src/api/rest/server/resource/spec.go
- src/api/rest/server/resource/sshkey.go
- src/api/rest/server/util/netuil.go
- src/core/common/client.go
* Check `X-Request-Id` in request Header and set it if it's empty in the RequestIdAndDetailsIssuer middleware
* Remove or replace common.StartRequestWithLog()
- Note: common.EndRequestWithLog() will be removed or replaced
There are a lot of changes, but most of them are similar :-)
> Improve the `X-Request-Id` and Request Details handling mechanism

- assets/k8sclusterinfo.yaml
- conf/cloud_conf.yaml
본 PR은 GCP에서 k8scluster를 사용할 수 있도록 활성화하고 관련 리전 및 버전 정보를 업데이트합니다.
> [k8scluster] enable gcp and update regions/versions

- src/core/resource/k8scluster.go
PR은 노드그룹의 이름에 UID 대신 사용자 지정 이름을 사용하도록 수정합니다.
현재는 노드그룹을 별도의 객체로 관리하지 않고 있습니다.
> [k8scluster] fix nodegroup's name

- src/core/common/logger/logger.go
> Ensure log file directory exists before creating the log file

- src/core/resource/subnet.go
- src/core/resource/vnet.go
* Due to the connection name pattern
**Tested by**
`POST /ns/{nsId}/resources/vNet`
(Case 1)
nsId: default
Request body:
```json
{
"cidrBlock": "10.0.0.0/16",
"connectionName": "aws-ap-northeast-2-ap-northeast-2a",
"description": "vnet00 managed by CB-Tumblebug",
"name": "vnet00",
"subnetInfoList": [
{
"description": "subnet00 managed by CB-Tumblebug",
"ipv4_CIDR": "10.0.1.0/24",
"name": "subnet00",
"zone": "ap-northeast-2a"
}
]
}
```
Response body:
```json
{
"resourceType": "vNet",
"id": "vnet00",
"uid": "crr9av5tv3aetsf218jg",
"cspResourceName": "crr9av5tv3aetsf218jg",
"cspResourceId": "vpc-03f6c920d0c67879c",
"name": "vnet00",
"connectionName": "aws-ap-northeast-2-ap-northeast-2a",
"cidrBlock": "10.0.0.0/16",
"subnetInfoList": [
{
"resourceType": "subnet",
"id": "subnet00",
"uid": …
```
> Replace the vNet and zone validation logic

- src/core/common/label/label.go
I checked all the files looking for corrections in the types and this was the only one I found give me a feedback
> Update label.go. Fix typo: replace 'lable' with 'label' #1838

- src/core/resource/k8scluster.go
본 PR은 AddK8sNodeGroup 호출시 ""와 "default"인 이미지 이름을 사용할 수 있도록 지원합니다.
> [k8scluster] support empty/default imagename when adding k8snodegroup

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/model/k8scluster.go
- src/core/resource/k8scluster.go
> Add csp connection info to k8s cluster info

- docker-compose.yaml
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/server.go
- src/core/model/common.go
- src/main.go
> Activate dynamic endpoint for swagger API dashboard

- docker-compose.yaml
- src/api/rest/server/middlewares/zerologger.go
- Request logging 활용도 향상을 위한 출력 구조 refine
개선
- 중복 소지가 있던 Method=OPTIONS 는 로깅에서 제외
- id, method 를 의도적으로 대문자로 변경하여, 우선 기록되도록 순서 변경
- byte in out 등 활용도가 낮은 항목 제외 등
```
cb-tumblebug       | ⇨ http server started on [::]:1323
cb-tumblebug       | 5:28AM INF src/api/rest/server/middlewares/zerologger.go:58 > request ID=1728019710091268611 Method=GET URI=/tumblebug/ns?option=id clientIP=10.0.2.2 latency="644.494µs" status=200
cb-tumblebug       | 5:28AM INF src/api/rest/server/middlewares/zerologger.go:58 > request ID=1728019710164470559 Method=GET URI=/tumblebug/ns/default/mci?option=id clientIP=10.0.2.2 latency=1.70523ms status=200
cb-tumblebug       | 5:28AM INF src/api/rest/server/middlewares/zerologger.go:58 > request ID=1728019710185217384 Method=GET …
```
> Refine API request logging struct

- docker-compose.yaml
- go.mod
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/resource/subnet.go
- src/api/rest/server/resource/vnet.go
- src/core/resource/subnet.go
- src/core/resource/vnet.go
(related to #1808)
**First of all, some parts in this PR need the next version of CB-Spider (so I opened this draft PR).**
Since it's not urgent, I'm going to wait for the next release.
**This PR includes the following updates:**
* Add RefineVNet() and RefineSubent(), which operates based on information managed by Tumblebug
* Add actions (refine, force) on the following APIs
- `DELETE /ns/{nsId}/resources/vNet/{vNetId}?action=xxx`
- `DELETE /ns/{nsId}/resources/vNet/{vNetId}/subnet/{subnetId}?action=xxx`
* Add the API to get subnet
- `GET /ns/{nsId}/resources/vNet/{vNetId}/subnet/{subnetId}`
* Improve comments in overall vNet/subnet functions and handlers
**The following was considered for the "Refine" implementation:**
1. Assume that Tumblebug, Spider, and CSP have already lost the …
> Handle the missing vNet/subnets by the unexpected outside operations

- src/testclient/scripts/3.vNet/delete-vNet.sh
- src/testclient/scripts/3.vNet/force-delete-vNet.sh
본 PR는 테스트 스크립트 중 (force-)delete-vnet.sh에 변경된 query param(action=withsubnets)가 적용되도록 합니다.
> [testscripts] update query param(action=withsubnets) in (force-)delete-vnet.sh

- src/core/common/utility.go
- src/core/resource/common.go
- src/core/resource/spec.go
- src/main.go
fix #1857
Bulk로 DB를 제어하도록 전반적으로 개선하였습니다. 
- 참고, 기존에 update를 bulk로 수행하는 기능이 없어서, 개별 레코드로 처리하였으나, 일단 전체 등록하고 중복을 전체 삭제하는 짱구를 굴려서 해결하였습니다.
- 향후 추가 개선 소지도 있습니다.
---
- 등록 속도는 약 2배 이상 증가되는 것으로 보이며
- "database is locked" 발생 가능성도 줄였습니다.
> Enhance speed and stability of spec init

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/model/vnet.go
- src/core/resource/subnet.go
- src/core/resource/vnet.go
This PR includes enhancements for the user-customized network design and configuration.
I'd like to explain this with a demo video :-)
It may take some time for the video to be ready. Also, it's possible to download it.
https://drive.google.com/file/d/1-lhxR55Mm2z1eUtiowt2scUDwIKdTDKA/view?usp=sharing
> Enhance for network design and configuration

- src/Makefile
> Add swag install guide message to MAKEFILE

- src/core/common/label/label.go
- src/core/infra/control.go
- src/core/infra/provisioning.go
- src/core/model/mci.go
ref #1873
Enhance large scale mc-infra provisioning stability
- 함께 병렬처리 되던 VM 오브젝트 생성과 VM 생성 요청/결과 처리 모듈을 분리하여, 안정성 향상
- CSP API별 콜 리밋을 고려하여, CSP 별 100 VM 동시 실행의 sleep 타이밍 조정 (현재 VM 생성 요청간 1000ms 지연 추가)
- 기타 중복된 DB 처리 구문 정리 등.
> Enhance large scale mc-infra provisioning stability

- src/core/common/config.go
Hello,
Hope you're doing well
As per the request mentioned in issue #1876, I have simple removed the redundant log statement that has been mentioned
If at all I missed something or implemented code changes incorrectly, then do let me know
Sincere apologies for any inconvenience or misunderstanding
Thanks and Regards,
Mohit Kambli
> Fix #1876: Remove the redundant code for fmt.Print

- src/core/resource/image.go
Use common.ExecuteHttpRequest to call spider
> Enhance client call code

- src/core/infra/control.go
- src/core/infra/manageInfo.go
- src/core/infra/utility.go
- src/core/resource/common.go
- src/core/resource/k8scluster.go
Fix vm status transition check bug for rebooting.
// duplicated action
if strings.EqualFold(vm.Status, targetStatus) {
if !strings.EqualFold(action, model.ActionReboot) {
return errors.New(action + " is not allowed for VM under " + vm.Status)
}
}
> Fix vm status transition check bug

- assets/cloudspec.csv
- assets/k8sclusterinfo.yaml
- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/core/infra/provisioning.go
- src/core/model/config.go
- src/core/model/k8scluster.go
- src/core/resource/k8scluster.go
본 PR은 K8s를 대상으로 mciDynamic과 유사한 k8sclusterDynamic API를 제공하며, 일부 API 이름이 변경되었습니다.
o API changes
- (rename) /tumblebug/availableK8sClusterVersion to availableK8sVersion
- (rename) /tumblebug/availableK8sClusterNodeImage to availableK8sNodeImage
- (rename) /checkNodeGroupsOnK8sCreation to checkK8sNodeGroupsOnK8sCreation
- (add) /requiredK8sSubnetCount
K8s 생성시 CSP별 필요한 서브넷 수의 차이를 파악하기 위해 assets/k8sclusterinfo.yaml에 이와 관련된 값을 기록하고 K8s 생성시 참조하고 있습니다.
- (add) /k8sclusterDynamicCheckRequest
/mciDynamicCheckRequest와 유사한 기능을 수행하며, 하나의 CommonSpec만을 허용합니다.
- (add) /ns/{nsId}/k8sclusterDynamic
/mciDynamic과 유사하게 K8sCluster 생성 요청시 shared resource를 자동으로 생성한 후 K8sCluster를 생성하며, hold 옵션을 사용하는 경우 K8sCluster 생성을 대기합니다.
- (add) /ns/{nsId}/control/k8scluster/{k8sClusterId}
생성 대기 중인 K8sCluster에 대해 생성을 …
> [k8scluster] support k8sclusterDynamic like mciDynamic

- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/core/infra/provisioning.go
- src/core/infra/recommendation.go
- src/core/model/k8scluster.go
본 PR은 k8sClusterDynamic 관련 업데이트를 제공합니다.
- For non required fields, set default values
- If no version, apply recent version in k8sclusterinfo.yaml
- Filter images with `k8s` infratype
- Fix recommend k8s node limit
- Update some json examples
K8sClusterDynamic 사용법: https://github.com/cloud-barista/cb-tumblebug/discussions/1913
> [k8scluster] update k8scluster dynamic

- go.mod
- go.work.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/common/label/label.go
- src/api/rest/server/resource/sqlDb.go
- src/api/rest/server/resource/vpn.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/core/model/common.go
- src/core/model/sqlDb.go
- src/core/resource/common.go
- src/core/resource/sqlDb.go
- src/core/resource/vpn.go
* Note - Supported AWS currently
* Upcoming CSPs: Azure, GCP, NCP
Generally speaking, we need information on DB instance specs and DB engine configuration. (cc @powerkimhub)
* In some cases, a DB instance spec ID different from the VM spec ID is used (e.g., db.t3.micro, db-f1-micro).
* It seems necessary to distinguish between information about the DB engine and a database within MySQL.
> Add APIs to manage SQL Database

- docker-compose.yaml
- go.mod
- go.sum
- go.work.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/resource/sqlDb.go
- src/api/rest/server/server.go
- src/core/model/sqlDb.go
- src/core/resource/sqlDb.go
* Support APIs to Create, Read, and Delete SQL DB
* Note - This API requires mc-terrarium.
The discussion https://github.com/cloud-barista/mc-terrarium/discussions/110 shows the API usage sample.
> Support SQL DB APIs for AWS, Azure, GCP, and NCP

- src/core/infra/provisioning.go
Note - Distributed-lock is applied, considering that multiple CB-Tumblebugs could be running.
Related to #1925
> Add dist-lock for safe in-parallel processing of MCI dynamic creation

- src/testclient/scripts/sequentialFullTest/test-mci-dynamic-all-for-one.sh
test script to be prepared for performance testing.
> Update performance test case

- docker-compose.yaml
- go.mod
- go.sum
- go.work.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/common/label/label.go
- src/api/rest/server/resource/objectStorage.go
- src/api/rest/server/server.go
- src/core/common/utility.go
- src/core/model/common.go
- src/core/model/objectStorage.go
- src/core/model/sqlDb.go
- src/core/resource/common.go
- src/core/resource/objectStorage.go
* Support APIs to create, read, and delete (CRD) Object Storage
* Note - This API requires mc-terrarium.
For the API usage sample, please refer to the discussion https://github.com/cloud-barista/mc-terrarium/discussions/117.
APIs
> Support Object Storage APIs for AWS and Azure

- conf/cloud_conf.yaml
- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/server.go
- src/core/infra/provisioning.go
- src/core/model/k8scluster.go
- src/core/resource/common.go
- src/core/resource/k8scluster.go
본 PR은 k8sclusterDynamic API를 통해 생성한 k8scluster를 대상으로 k8snodegroup을 동적으로 생성할 수 있는 k8snodegroupDynamic API를 지원합니다.
o API changes
- (add) /ns/{nsId}/k8snodegroupDynamic
o others
- enable aws for k8scluster
- fix some bugs related to k8sclusterDynamic
- when creating shared subnets, try to assign different zone
> FEAT: [k8scluster] support k8snodegroupDynamic

- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/server.go
- src/core/model/k8scluster.go
- src/core/resource/k8scluster.go
본 PR은 ListK8sCluster() API 호출시 최신 정보 확인을 위해 CB-SP에 직접 관련 정보를 요청합니다.
fixes #1933
> FIX: [k8scluster] update k8scluster infor from CB-SP for ListK8sCluster()

- go.mod
- go.sum
- src/api/rest/server/server.go
- src/core/common/label/label.go
- src/core/infra/provisioning.go
- src/core/resource/common.go
- src/core/resource/image.go
Enable MC-Infra dynamic provisioning with custom image
> Enable MC-Infra dynamic provisioning with custom image

- assets/k8sclusterinfo.yaml
- src/api/rest/server/resource/k8scluster.go
- src/core/common/utility.go
- src/core/model/config.go
- src/core/resource/k8scluster.go
본 PR은 #1941 이슈를 해결하고,
Azure에서 node group name의 제약이 발생하는 것을 사전에 방지하기 위해 assets/k8sclusterinfo.yaml에 등록된 regular expression을 체크합니다.
In the case of Azure, dashes are not allowed in node pool names.
For more details, refer to https://aka.ms/aks-naming-rules.
> Fix 1941 and validate naming rule

- docker-compose.yaml
- src/core/infra/provisioning.go
This PR will improve the shared resource handling mechanism on MCI dynamic creation.
* Remove distributed lock
* Check if there is a Shared Resource before creation
* Execute getVmReqFromDynamicReq() for the first request (i.e., vmRequest[0])
- It's necessary to create Shared Resources securely.
* Then apply an in-parallel routine for the remaining vmRequest[1:]
( It will be staged once more... ;;; )
> Improve shared resource handling mechanism on MCI dynamic creation

- assets/cloudimage.csv
- assets/k8sclusterinfo.yaml
본 PR은 NHNCloud의 이미지 중 ubuntu와 ubuntu container가 중복된 이름으로 관리되고 있기에 이를 수정하여 관련 이슈(#1951) 발생을 회피하고,
GCP용 k8s 버전을 업데이트합니다.
> Update assets/cloudimage.csv and assets/k8sclusterinfo.yaml

- assets/k8sclusterinfo.yaml
본 PR은 Tencent ap-hongkong 리전의 K8sCluster에 접근이 되지 않도록 설정한다.
현재 ap-hongkong의 K8sCluster가 생성되기는 하지만 해당 Kubeconfig로 접근 불가능한 것으로 확인되었다.
* 관련 이슈: https://github.com/cloud-barista/cb-spider/issues/1386
> CHORE: set tencent's ap-hongkong as service unavailable

- assets/k8sclusterinfo.yaml
본 PR은 중국 지역 리전에 대한 이외 지역에서의 접근 문제가 해결될 때까지 접근을 막기 위한 것입니다.
(참조: https://github.com/cloud-barista/cb-spider/issues/1386)
o Set some regions as unavailable
- Clients in korea cannot access k8scluster of regions in china
o Update K8sCluster version for tencent
> CHORE: [k8scluster] update some regions of tencent as unavailable

- go.work.sum
- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/infra/manageInfo.go
- src/core/infra/manageInfo.go
- src/core/model/mci.go
- Add individual VM access info API
This will be used by MapUI. :)
> Add individual VM access info API

- README.md
Add screenshots of using a generated encryption key file for the credential file
Ref: #1960
> Add screenshots in the README.md

- .gitignore
- Makefile
- conf/traefik.yaml
- docker-compose.yaml
- scripts/certs/generate-certs.sh
This PR will add Traefik TSL reverse proxy with self-signed certificates.
It's applied to CB-MapUI.
(Updates)
* Add `generate-certs.sh`
* Add `make certs`
* Add `traefik.yaml` for Traefik TLS setup
* Update `docker-compose.yaml`
- Add Traefik service for TLS reverse proxy
- Update cb-mapui configuration
(quick start)
```
make certs
make compose
```
(What's changing)
> (Show and discuss) Add Traefik TLS reverse proxy with self-signed certificates

- src/core/common/label/label.go
- src/main.go
- [Remove redundant prints at initialization](https://github.com/cloud-barista/cb-tumblebug/commit/456099427d784ebc3b9876fd75a02d13dfa38b0f)
- [Add error log for updating csp tags](https://github.com/cloud-barista/cb-tumblebug/commit/ab628143923330d6bc18eca66f5e4ce0c74f3ae7)
> Remove PrintCloudInfoTable during initialization

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/core/infra/provisioning.go
- src/core/infra/remoteCommand.go
- src/core/model/mci.go
- src/core/resource/k8scluster.go
This PR adds Post (bootstrapping) Command feature to MC-Infra provisioning.
Users can insert commands (scripts) that are executed remotely just after VMs in a MCI are launched.
```
cb-tumblebug       | {
cb-tumblebug       |   "name": "mc-573qa",
cb-tumblebug       |   "installMonAgent": "no",
cb-tumblebug       |   "label": null,
cb-tumblebug       |   "systemLabel": "",
cb-tumblebug       |   "description": "Made via cb-mapui",
cb-tumblebug       |   "vm": [
cb-tumblebug       |     {
cb-tumblebug       |       "name": "g1",
cb-tumblebug       |       "subGroupSize": "1",
cb-tumblebug       |       "label": null,
cb-tumblebug       |       "description": "mapui",
cb-tumblebug       |       "connectionName": "aws-ap-northeast-2",
cb-tumblebug       |       "specId": …
```
> Add MC-Infra Post (bootstrapping) Command feature and add safety features for bastion SSH

- src/api/rest/server/server.go
- src/core/resource/k8scluster.go
- Remove redundant log messages in K8s clusters.
> Remove redundant log messages

- src/api/rest/docs/docs.go
- src/api/rest/docs/swagger.json
- src/api/rest/docs/swagger.yaml
- src/api/rest/server/infra/remoteCommand.go
- src/core/infra/benchmark.go
- src/core/infra/loadbalance.go
- src/core/infra/orchestration.go
- src/core/infra/provisioning.go
- src/core/infra/remoteCommand.go
This PR enables selective parallel execution of remote commands in MCI by utilizing **labels** to target specific VMs.
> Add remote command by labelSelector

- assets/cloudimage.csv
- assets/k8sclusterinfo.yaml
본 PR은 `assets/cloudimage.csv`와 `assets/k8sclusterinfo.yaml`을 업데이트합니다.
> CHORE: update alibaba and nhncloud's cloudimage and k8sclusterinfo.yaml

- src/testclient/scripts/sequentialFullTest/cinder-sc.yaml
- src/testclient/scripts/sequentialFullTest/ebs-sc.yaml
본 PR은 AWS와 NHNCloud를 대상으로 생성한 K8sCluster에는 활용 가능한 StorageClass가 등록되어 있지 않기 때문에 기본 StorageClass로 등록하기 위한 예시를 추가합니다.
동적 볼륨 프로비저닝 시험 등을 위해 활용될 수 있습니다.
https://github.com/cloud-barista/cb-spider/issues/1487#issuecomment-2774219898
> CHORE: [k8scluster] add sample storageclass yaml files

- src/api/rest/server/resource/k8scluster.go
본 PR은 swagger에 나타나는 k8sNodeGroupName 항목의 기본값을 k8sng01로 변경합니다.
Azure의 경우 이름 길이로 인한 이슈가 발생할 수 있습니다.
> chore: change swagger's default k8snodegroup name

- src/api/rest/server/resource/k8scluster.go
- src/api/rest/server/server.go
- src/core/model/k8scluster.go
- src/core/resource/k8scluster.go
본 PR은 MCI에서 제공하는 transferFile API와 유사하게 K8Cluster 내 Container를 대상으로 임의의 파일을 전송하는 API를 추가합니다. 따라서 전송 가능한 파일 용량은 최대 10MB 이내로 제한되어 있으며, kubectl cp 기능과 동일하게 tar 기능이 사용되었습니다.
@hanizang77
> feat: [k8scluster] support to transfer file to k8scluster's container

- assets/k8sclusterinfo.yaml
본 PR은 현재 Azure에서 지원하는 쿠버네티스 버전으로 업데이트합니다.
> chore: [k8scluster] update supported k8sversion of azure

- assets/cloudimage.csv
- assets/extractionpatterns.yaml
- docker-compose.yaml
- src/api/rest/server/resource/image.go
- src/core/resource/image.go
- src/core/resource/spec.go
- src/main.go
- Update assets/cloudimage.csv and Improve assets/extractionpatterns.yaml
- Expedite image fetching speed by selectively assign parallelism
- Provide both sync and async mechanisms for the image fetching 
- Provide a method to check fetching status and prevent duplicated requests
- use cb-mapui:0.10.5 and disable pgAdmin and Metabase by default in docker-compose.yaml (they are for cb-tb developers only)
> Expedite and enhance image fetching mechanism

- src/core/infra/recommendation.go
- Set tolerance 10% for spec location recommend
Will make close CSP regions have the same priority for spec recommendation.
> Set tolerance 10% for spec location recommend

- src/core/model/securitygroup.go
- src/core/resource/common.go
- src/core/resource/securitygroup.go
- src/interface/rest/docs/docs.go
- src/interface/rest/docs/swagger.json
- src/interface/rest/docs/swagger.yaml
- src/interface/rest/server/resource/securitygroup.go
- Change firewall rule model to use Ports (string) instead of FromPort/ToPort
- Add protocol-specific handling (ICMP, ALL) and port validation logic
- Implement robust diff logic for AWS-style rule overlap/replace on update
- Add conversion functions between Spider and Tb firewall rule structs
- Implement and document REST API handler for synchronizing firewall rules
- Update Swagger docs and OpenAPI spec with new model, usage, and examples
> feat: refactor Security Group firewall rule model and update logic

- src/core/common/label/label.go
- src/core/infra/provisioning.go
- src/core/model/mci.go
- src/interface/rest/docs/docs.go
- src/interface/rest/docs/swagger.json
- src/interface/rest/docs/swagger.yaml
- src/interface/rest/server/infra/provisioning.go
🚀 Performance Improvements:
- Implement parallel VM validation in ReviewMciDynamicReq using goroutines with semaphore control (maxConcurrency: 10)
- Add concurrent resource rollback with enhanced error handling and progress tracking
- Reduce MCI review response time significantly for multi-VM configurations
📚 API Documentation Enhancement:
- Add comprehensive Swagger documentation for 8 REST API handlers in provisioning.go
- Include detailed descriptions, parameter explanations, and response examples
- Document failure policies, resource requirements, and VM lifecycle management
🔧 Core Functionality Improvements:
- Add PolicyOnPartialFailure support (continue/rollback/refine) for better failure handling
- Enhance error messages with detailed context and troubleshooting information
- …
> feat: optimize MCI review performance with parallel processing

- src/core/infra/control.go
This PR will set a longer API request timeout.
For NCP VPCs, the API request timeout is set to 45 minutes.
* Note: This time is set to account for the maximum request processing time of Spider/driver.
---
According to [Beetle's NCP test results](https://github.com/cloud-barista/cm-beetle/blob/main/cmd/test-cli/testresult/beetle-test-results-ncp.md), deleting the MCI (option: terminate) in NCP took around 13 minutes.
**Therefore, the current value of 10 minutes needs to be increased. I considered the Spider/driver request processing time and set it to 45 minutes in this PR.**
* Note: It is expected to take around 45 minutes in the worst case.
**Please review the following:**
* Is the time (45 minutes) acceptable?
* Does this need to be set for all CSPs?
> Set a longer API request timeout for the control VM in the NCP VPC

- src/core/common/config.go
- src/core/common/label/label.go
- src/core/common/namespace.go
- src/core/common/utility.go
- src/core/infra/control.go
- src/core/infra/loadbalance.go
- src/core/infra/manageInfo.go
- src/core/infra/orchestration.go
- src/core/infra/provisioning.go
- src/core/infra/remoteCommand.go
- src/core/infra/snapshot.go
- src/core/infra/utility.go
- src/core/resource/common.go
- src/core/resource/k8scluster.go
- src/core/resource/objectStorage.go
- src/core/resource/securitygroup.go
- src/core/resource/sqlDb.go
- src/core/resource/sshkey.go
- src/core/resource/subnet.go
- src/core/resource/vnet.go
- src/core/resource/vpn.go
- src/kvstore/etcd/etcd.go
- src/kvstore/kvstore/kvstore.go
This pull request introduces a more robust method for **checking key existence in our kvstore operations by using an explicit `exists` flag**. 
**Key Changes**
* **Explicit Existence Checks**: Replaced ambiguous empty struct comparisons with clear boolean flag checks
- Note - structs containing `map` cannot be directly compared like this pattern `if keyValue != (kvstore.KeyValue{})`
* **Better Error Handling**: Distinguished between actual errors and "key not found" scenarios
* **Incremental Migration**: Used `_` placeholder where full refactoring wasn't immediately feasible, marking areas for future improvement
Example Change
```diff
-	keyValue, err := kvstore.GetKv(key)
-	if keyValue != (kvstore.KeyValue{}) {
+	_, exists, err := kvstore.GetKv(key)
+	if exists {
return true, nil
}
``` …
> Enhance KV existence checks for better reliability and bugfix on creating MCI.

- src/core/infra/provisioning.go
- src/core/model/mci.go
- src/interface/rest/docs/docs.go
- src/interface/rest/docs/swagger.json
- src/interface/rest/docs/swagger.yaml
fix #2123
Reduced racing condition for mci dynamic.
Extreamly tested in parallel.
| 순위 | VM 이름 | 스펙 | 시간당 비용 | vCPU | 메모리 |
|------|---------|------|-------------|------|--------|
| 1 | vm-t3a-nano-1 | t3a.nano | $0.0061 | 2 | 0.5GB |
| 2 | vm-t3-nano-1 | t3.nano | $0.0068 | 2 | 0.5GB |
| 3 | vm-t2-nano-1 | t2.nano | $0.0076 | 1 | 0.5GB |
| 4 | vm-t3a-micro-1 | t3a.micro | $0.0122 | 2 | 1GB |
| 5 | vm-t3-micro-1 | t3.micro | $0.0136 | 2 | 1GB |
| 6 | vm-t2-micro-1 | t2.micro | $0.0152 | 1 | 1GB |
| 7 | vm-t3a-small-1 | t3a.small | $0.0245 | 2 | 2GB |
| 8 | vm-t3-small-1 | t3.small | $0.0272 | 2 | 2GB |
| 9 | vm-t2-small-1 | t2.small | $0.0304 | 1 | 2GB |
| 10 | vm-t3a-medium-1 | t3a.medium | $0.0490 | 2 | 4GB |
| 11 | vm-t3-medium-1 | t3.medium | $0.0544 | 2 | 4GB |
| 12 | vm-t2-medium-1 …
> Reduce racing condition for mci dynamic

- assets/k8sclusterinfo.yaml
- src/core/resource/common.go
NCP K8s cluster creation requires all subnets (including LB subnets) to be within the same availability zone, unlike other CSPs that support multi-AZ deployments. Current logic was assigning subnets to different zones, causing K8s cluster creation failures.
- Modified NCP subnet creation logic to use the same zone (zones[0]) instead of zones[1]
- Added explanatory comments with reference to issue #2136
- Added NCP to k8sclusterinfo.yaml
**API Used:** `k8sClusterDynamic`
**Request Body:**
```json
{
"imageId": "default",
"specId": "ncp+kr+ci2-g3",
"connectionName": "ncp-kr",
"name": "k8scluster02",
"nodeGroupName": "k8sng02"
}
```
Fixes #2136
> Configure NCP subnets to use single zone for cluster creation
